### ISSUE TITLE
Sending PubSub events from go-app (browser)

### ISSUE THREAD

**Issue by rtrzebinski** [maxence-charriere/go-app#1000]
Hi, I'm trying to configure sending of PubSub messages from the browser part of go-app.

So far no luck, I'm stuck on `failed to send good answer event: send event: unable to get or create topic "topic-dev", rpc error: code = DeadlineExceeded desc = context deadline exceeded` error which I see in the browser console when trying to send an event.

This error is likely meaning that PubSub emulator that I run on localhost cannot be accessed by the browser app.

Emulator works, I can call for instance "http://localhost:8085/v1/projects/project-dev/topics/topic-dev".

Emulator requires `os.Setenv("PUBSUB_EMULATOR_HOST", "localhost:8085")` which is set in `main.go`.

I see this env var is visible when I dump it in the browser part of the code.

Can you think of any reason for that? Perhaps something in go-app architecture prevents such connection.

I see in "connections" tab of the developer tools that no web request is being made or tried.

I tried to switch to http (normally I use local self signed https) but no difference.

Since this is Web Assembly I'm blind as I can't just use Go debugger like with normal app.

Thank you for any ideas!

If anyone wants to take a look this is my not working PR -> https://github.com/rtrzebinski/simple-memorizer-4/pull/7/files

To reproduce:

```
make deps
make dev
make run
```

Go to `https://localhost:8000/learn?lesson_id=1`
Open developer tools (JS console)
Click on "Good Answer"
Watch for the error in JS console

**Comment by oderwat** [comment]
I did not check any of the code, but you can't have just any TCP connections from WASM. There is only the JS fetch interface  (HTTP) and the HTTP based upgraded "framed TCP" connection that is known as web socket. 

Looking a bit further into it, this package uses `otelhttp` and skimming this I saw that it uses the `http.DefaultTransport`. I think this is not supported by Go WASM. So I asked ClaudeAI and this was the answer:

````
Let me check the compatibility of OpenTelemetry's HTTP instrumentation with Go WebAssembly targets.
Looking at the current Go WASM implementation and otelhttp limitations as of April 2024:
The main issue is that otelhttp depends on net/http, but Go's WebAssembly port has a limited implementation of net/http. Specifically:

The default HTTP transport doesn't work in WASM
Many standard library networking features are restricted in the WASM environment

You have a few potential options:

Use a custom transport that works with WASM (like using the browser's Fetch API)
Implement a minimal subset of the instrumentation that doesn't depend on net/http
Consider alternative telemetry approaches for your WASM code

However, since this is a somewhat specialized use case, I recommend verifying the current compatibility status in the official OpenTelemetry Go documentation, as there may have been changes after my knowledge cutoff date.
```
P.S.: This is why we use NATS with a WASM version of web socket (or HTTP RESTful API) exclusively.

**Comment by rtrzebinski** [comment]
Thank you @oderwat this is what I was worried about. Looks like there is no way to use PubSub over Cloudevents client in WASM, I need to abandon this idea.

Side question:

I currently communicate with my backend via HTTP/REST API and this works fine. However I'm thinking of replacing it with gRPC API.

Do you think I'd get the same issue? Since gRPC works over HTTP/2 perhaps this should be fine.

**Comment by rtrzebinski** [comment]
Thank you @oderwat I will check these out.
