### ISSUE TITLE
use brotli compression with static website build

### ISSUE THREAD

**Issue by BrownNPC** [maxence-charriere/go-app#1002]
i was wondering if there was a way to use a brotli compressed app.wasm.bz in the static website build to improve load times.

Im not sure how to set the correct headers though.

**Comment by oderwat** [comment]
You can use the Chi Router and add the compression middleware.

Something like this should work:

``` go
appHandler := &app.Handler{...}

// we had problems with compressing JS
compressor := middleware.NewCompressor(5, "application/wasm", "text/css", "image/svg+xml")
compressor.SetEncoder("br", func(w io.Writer, level int) io.Writer {
	params := brotli_enc.NewBrotliParams()
	params.SetQuality(level)
	return brotli_enc.NewBrotliWriter(params, w)
})
r := chi.NewRouter()
r.Use(middleware.RequestID)
r.Use(middleware.Logger)
r.Use(compressor.Handler)
r.Handle("/*", appHandler)
http.ListenAndServe(":80", r)
```

Above code is untested. This will compress on the fly and adjusts to the browsers abilities. You could also check the headers and use the compressed versions manually. Maybe there is another middleware for that too.

**Comment by BrownNPC** [comment]
Thanks for taking the time to answer this. So in conclusion, the only way to do this is to somehow have the static files host provide you the facility to use such compression.
