### ISSUE TITLE
Component is already mounted, happens only on hard refresh

### ISSUE THREAD

**Issue by mar1n3r0** [maxence-charriere/go-app#1007]
`http: panic serving 127.0.0.1:53042: {"line":"engine.go:154","message":"loading component failed","tags":{"component-type":"*main.Tutorials"},"wrap":{"line":"engine.go:219","message":"updating root failed","wrap":{"line":"node.go:428","message":"mounting child failed","tags":{"depth":0,"index":0,"tag":"body","type":"*app.htmlBody"},"wrap":{"line":"node.go:219","message":"component is already mounted","tags":{"depth":1,"parent-type":"*app.htmlBody","type":"*main.Tutorials"}}}}}`

```
tutorials := newTutorials()
app.Route("/tutorials", func() app.Composer {
	return tutorials
})
```

**Comment by maxence-charriere** [comment]
you are returning the same instance of tutorials that is already mounted. Try `return newTutorials()`.
