### ISSUE TITLE
Error: Uncaught (in promise) TypeError: Failed to fetch

### ISSUE THREAD

**Issue by dtmkeng** [maxence-charriere/go-app#308]
`The FetchEvent for "http://localhost:3000/" resulted in a network error response: the promise was rejected.
goapp.js:1 Uncaught (in promise) TypeError: Failed to fetch`

**Comment by maxence-charriere** [comment]
Hi, thanks for reporting this.

Any hint on how to reproduce?

**Comment by maxence-charriere** [comment]
A bug was fixed in #305 

Try `goapp update -v`.

**Comment by maxence-charriere** [comment]
Actually I get it.
Look like it happen in the console of a page if another tab is loaded with a newer version.

**Comment by dtmkeng** [comment]
yes alright . I use  goapp init -v and goapp run -v -b default . I found issue #212  I don’t know it woking on ubuntu 19.04

**Comment by maxence-charriere** [comment]
Hello there, I just released v6.0.0.
So far I did not see this issue again.

Closing it. Feel free to reopen if there are related problems.

Best,
Maxence
