### ISSUE TITLE
Running a standalone binary from package sources only in docker multistage build

### ISSUE THREAD

**Issue by mar1n3r0** [maxence-charriere/go-app#311]
Hello and thanks for creating this very neat framework.

I am trying to build a minimal multistage docker build running from binary without the goapp CLI. 

I have seen that a binary for mac was accomplished in older threads. Is that doable on Linux as well ? 

I am not sure what's the exact flow behind `goapp run -v -b default`  but looking at the code it's running the server only.

Example Dockerfile:
```
FROM golang:1.13 as buildenv

RUN export GOROOT=/usr/lib/go

RUN export GOPATH=$HOME/go

RUN export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

ENV CGO_ENABLED=0

WORKDIR $GOPATH/src/demo

RUN go get -u -v github.com/maxence-charriere/app/cmd/goapp

COPY cmd cmd

RUN goapp build -v

FROM scratch

COPY --from=buildenv /go/src/demo/cmd/demo-server/demo-server /go/bin/app 

ENTRYPOINT ["/go/bin/app"]
```

Example output:
```
Uncaught ReferenceError: Go is not defined
    at (index):351
```

[ReferenceError: Go is not defined error](https://groups.google.com/forum/#!topic/golang-nuts/egje1QRt_Gg)

Based on this similar topic it seems that the issue is somewhere in 

> app/internal/http/page.js

```
// -----------------------------------------------------------------------------
// Init Web Assembly
// -----------------------------------------------------------------------------
if (!WebAssembly.instantiateStreaming) {
  WebAssembly.instantiateStreaming = async (resp, importObject) => {
    const source = await (await resp).arrayBuffer()
    return await WebAssembly.instantiate(source, importObject)
  }
}
```

**Comment by maxence-charriere** [comment]
Hi there, just giving some news about this issue.

I had been working for a while on the next version of this package and I'm currently finishing up things for a near to come release.

While there will be breaking changes, a Docker example that shows how to run an app created with this package will be added to the `demo` directory. 

You can take a peek [here](https://github.com/maxence-charriere/app/tree/6.0.0).

**Comment by mar1n3r0** [comment]
Great stuff, I had a chance to briefly go through the changes. I can see that the direction the app is heading to is more or less a full-blown framework with its own bindings for all html interfaces and js events. That is quite a departure from the previous versions where it was a mere wrapper of raw markup. Would it still support raw markup as well as bindings or the focus will be towards enclosing the ecosystem in its own objects ?

**Comment by maxence-charriere** [comment]
The focus will be on its own objects. There will still be a raw element:

```go
raw := app.Raw(`<h1>Hello world</h1>`)
``` 
It takes raw HTML string argument but it will be limited compared to the current version (no event handler).

**Comment by maxence-charriere** [comment]
Hi there,

here is a docker example on how to use the package with docker:
https://github.com/maxence-charriere/go-app-demo/tree/v6/hello-docker

Gonna close this issue.
Feel free to reopen if it does not fit the need.
