### ISSUE TITLE
Hello-docker binary

### ISSUE THREAD

**Issue by mar1n3r0** [maxence-charriere/go-app#358]
Hi there,

here is a docker example on how to use the package with docker:
https://github.com/maxence-charriere/go-app-demo/tree/v6/hello-docker

Gonna close this issue.
Feel free to reopen if it does not fit the need.

_Originally posted by @maxence-charriere in https://github.com/maxence-charriere/go-app/issues/311#issuecomment-599509560_

**Comment by mar1n3r0** [comment]
Thanks was just testing that these days. It is still requiring a full-blown Go workspace to be in place which makes the actual image 800MB+. 

Here is an example Dockerfile of it being a standalone binary with no Go env needed:

```
# Set the latest golang base image:
FROM golang:latest AS buildenv

ENV CGO_ENABLED=0

# Set the Current Working Directory inside the container
WORKDIR /app

# Build server:
COPY  ./ ./
RUN go mod download
RUN go build -o /go/bin/app .

FROM scratch

COPY --from=buildenv /app/app.wasm /go/bin/app.wasm
COPY --from=buildenv /go/bin/app /go/bin/app

# Expose server port:
EXPOSE 7000

# App version (uncomment if the image is for non-development ends):
# ENV APP_VERSION "YOUR_VERSION"

# Run the server:
ENTRYPOINT ["/go/bin/app"]
```

Still it needs adaptation to the main.go file in order for the wasm file to be served as well as the binary.

**Comment by maxence-charriere** [comment]
Thanks for the clarification.

```
Still it needs adaptation to the main.go file in order for the wasm file to be served as well as the binary.
```
I don't get that though. The wasm file is a static resource. It is just required that its located in the same dir as the exec.

**Comment by mar1n3r0** [comment]
In my case based on v5 it was the wasm_exec.js that was not loaded with a correct path(by default it was /wasm_exec.js rather than /web/wasm_exec.js). Once this path was fixed I managed to build the binary executable as described above. I think taking this into consideration maybe we can close this one.

**Comment by maxence-charriere** [comment]
A lot of things changed since v5. The files required to make the web assembly run are not static resources anymore but part of the http.Handler.
