### ISSUE TITLE
Form submit/Fetch API response ? 

### ISSUE THREAD

**Issue by mar1n3r0** [maxence-charriere/go-app#362]
On form submit no matter if you use an input element or a button the default behavior is to be redirected to the action url. Is there a way not to without the use of any Ajax/JS ?

**Comment by maxence-charriere** [comment]
Did you try handling the click event and use e.PreventDefault() ?

**Comment by mar1n3r0** [comment]
```
<input class="form__button" type="submit" value="Sign up" onclick="OnSendForm"/>

func (n *Home) OnSendForm(s, e js.Value) {
	e.Call("PreventDefault")
	app.Navigate("https://github.com/maxence-charriere/app/blob/master/demo/cmd/demo-wasm/hello.go")
}
```

I have tried it like this. Didn't have any effect. The idea is not to prevent the form from submitting but to rather redirect to a welcome page instead of redirecting to the server. 

What worked so far was `http.Redirect(w, r, r.Header.Get("Referer"), 302)` on the server-side.

I am still trying to get the grasp of this whole concept of syscall/js Go to JS compiling. 
Another question stemming from this was how would one handle the server response data(ex API responses) ?

**Comment by maxence-charriere** [comment]
I m not on a computer right now but i would prevent default and use go standard http.Client to perform the request and get a proper response.

**Comment by maxence-charriere** [comment]
Also you have a typo on prevent default=> preventDefault

**Comment by mar1n3r0** [comment]
Thanks that solves it indeed.

**Comment by jorgefuertes** [comment]
Hi, I'm sorry to disturb here but I don't know where else to ask.
When I try to compile to webassembly using a call to http.Client I got the following errors:
```
../../../../gocode/pkg/mod/github.com/valyala/tcplisten@v1.0.0/socket_other.go:11:48: undefined: syscall.SOCK_NONBLOCK
../../../../gocode/pkg/mod/github.com/valyala/tcplisten@v1.0.0/socket_other.go:11:70: undefined: syscall.SOCK_CLOEXEC
```

Any ideas, please? Thanks in advance.

**Comment by oderwat** [comment]
> Hi, I'm sorry to disturb here but I don't know where else to ask.

@jorgefuertes maybe just create a new issue instead of adding something unrelated to another one?

> github.com/valyala/tcplisten

That is not the standard lib HTTP package. I wonder how your code ends up using that, but this does not support WASM. You need to know that WASM code run in the browser sandbox and that can't use TCP/IP. The standard library code uses "fetch" instead. I think you use some packages that are just not compatible with the WASM target.

**Comment by jorgefuertes** [comment]
Hi @oderwat, you are absolutely right but my concern was this is not an issue, just a question because my inexperencie with go-app, so... but yeah, I'll do a new one next time.

And thanks for your answer. The vscode changed my import I guess, I'll try again with the standard one.

Thanks again.
