### ISSUE TITLE
Possible Race Condition in http.go:init

### ISSUE THREAD

**Issue by jwmach1** [maxence-charriere/go-app#363]
I see this occasionally when hitting the browser refresh button. The page never moves beyond the spinning icon.  Hitting refresh again loads the page successfully -- usually.  In the Chrome console,

```
registering app service worker
app.js:46 Uncaught (in promise) TypeError: Cannot set property 'className' of null
    at app.js:46
```

inspecting the app.js at line 46 is the loaderIcon.classname assignment:
```
  .catch(err => {
    const loaderIcon = document.getElementById("app-wasm-loader-icon");
    loaderIcon.className = "app-wasm-icon";

    const loaderLabel = document.getElementById("app-wasm-loader-label");
    loaderLabel.innerText = err;

    console.error("loading wasm failed: " + err);
  });
```

The browser does show the icon (I'm still using your default icon) spinning.  And If I run `document.getElementById("app-wasm-loader-icon")` in the console, it does return the image. So my suspicion is that there is a race between http.go:initPage completing, and the app.js  code above.

I don't know what caused the original error that pushed the app.js into the catch block.  But I suspect it was the same thing, that "app-wasm-loader-icon" was not yet in the document.

This might trace back to http.go:init, perhaps Chrome has not finished modifying the document per `h.initPage` by the time app.js tries to use the document elements.

**Comment by maxence-charriere** [comment]
Hey @jwmach1 

Thank you for reporting this.
Unfortunately, I was not able to reproduce this issue.

I updated where the js files are included to be at the end of the body.
Could you try it and see if it resolves the issue?

```sh
go get -u github.com/maxence-charriere/go-app/v6@a07ba30
```

**Comment by jwmach1** [comment]
frustratingly, now I can't reproduce it on any branch.  I'll keep looking
for it to start up again.

**Comment by jwmach1** [comment]
After experiencing the issue last weekend while still using 6.1.0, I switched to your fix and have not experienced since.

**Comment by maxence-charriere** [comment]
Thanks for the feedback. I ll merge the fix then.
