### ISSUE TITLE
How to call javascript within a component

### ISSUE THREAD

**Issue by tw4452852** [maxence-charriere/go-app#369]
Just wondering if there's a way to call javascript within a component. For example:

```
type foo struct {
    app.Compo
}

fun (f *foo) Render() app.UI {
return app.Div().Body {
    app.Div().ID("test"),
    app.Script().Body(
        app.Text(`document.getElementById("test").style["color"] = "blue";`),
}
}
```

Something like thing, any ideas?

**Comment by maxence-charriere** [comment]
Hi @tw4452852 
There is no Script method that allows calling javascript.

I'm not on a computer right now but maybe you can try the [Raw](https://pkg.go.dev/github.com/maxence-charriere/go-app/v6/pkg/app?tab=doc#Raw) one:
```
app.Raw(`
<script>
    document.getElementById("test").style["color"] = "blue";
</script>
`)
```

I'm not sure if it is working though.

What are you trying to achieve?

If the example given above is a real case one, you can do:
```go
app.Div().
    ID("test").
    Style("color", "blue")

```

**Comment by tw4452852** [comment]
Hi @maxence-charriere 

What I'm willing to do is to load animation with [lottie.js](https://github.com/airbnb/lottie-web) 

```
type foo struct {
    app.Compo
}

fun (f *foo) Render() app.UI {
return app.Div().Body (
    app.Div().ID("test"),
    app.Script().Body(
        app.Text(`lottie.loadAnimation ({
           container: document.getElementById("test");
           ....
         `),
)
}
```

**Comment by maxence-charriere** [comment]
if the [app.Raw](https://pkg.go.dev/github.com/maxence-charriere/go-app/v6/pkg/app?tab=doc#Raw) element does not work, you can try to launch the animation by implementing the [Mounter](https://pkg.go.dev/github.com/maxence-charriere/go-app/v6/pkg/app?tab=doc#Mounter) interface:

```go
type foo struct {
	app.Compo
}

func (f *foo) OnMount() {
	test := app.Window().Get("document").Call("getElementById", "test")
	lottie := app.Window().Get("lottie")
	lottie.Call("loadAnimation", map[string]interface{}{
		"container": test,
		"renderer":  "svg",
		"loop":      true,
		"autoplay":  true,
		"path":      "ata.json",
	})
	f.Update()
}

func (f *foo) Render() app.UI {
	return app.Div().Body(
		app.Div().ID("test"),
	)
}
```

**Comment by tw4452852** [comment]
Thanks @maxence-charriere 
It works now!

**Comment by maxence-charriere** [comment]
Just curious, which solution did you ended up using?

**Comment by tw4452852** [comment]
Hi @maxence-charriere 

All three ways above work. Because I had a `display=hidden` by accident, the problem is resolved after removing it.
