### ISSUE TITLE
Missing THEAD tag

### ISSUE THREAD

**Issue by jwmach1** [maxence-charriere/go-app#373]
I didn't think I was going to come across an HTML tag you didn't implement, but now I notice that there is no thead tag. (I see `tbody`, but no `thead`).  Did I miss it?

Unless the `thead` tag has been omitted on purpose, would you rather I submit a pull request or can you whip out new tag implementations faster than a pull request?

**Comment by maxence-charriere** [comment]
Nice catch, i ll add it asap.
