### ISSUE TITLE
Concurrency example

### ISSUE THREAD

**Issue by mar1n3r0** [maxence-charriere/go-app#380]
> Performing blocking operations directly in event handlers may result in unresponsiveness in the UI. Those should be performed in another goroutine.

Based on the updated docs how would one exchange data between say the UI goroutine and newly created ones given that the event handlers are not accepting external arguments ? 

I tried creating the channel in the new goroutine and passing it to Render/Update but the UI goroutine is finished by the time the result is passed.

A basic example would be really nice to give some ideas as to how you see this working.

**Comment by maxence-charriere** [comment]
Hey @mar1n3r0 

The easiest one (but not the most elegant) would be to throw a goroutine to execute a blocking operation and then call [Dispatch](https://pkg.go.dev/github.com/maxence-charriere/go-app/v6/pkg/app?tab=doc#Dispatch) to process the result back in the UI goroutine.

```go
func (c *mycompo) OnClick(s app.Value, e app.Event){
    go func() {
        \\ Blocking operation ...

        app.Dispatch(func(){
            // Compo modifications
            c.Update()
        })
    }()
}
```

Free to you to implement your own mechanism that is more syntax sugar friendly. 

For example, before I wrote a Flux favored one. In the current project I work on, I did a resource manager that fetch data from local storage and then from HTTP and notify the components each time there is a result.

Both are built on the top of the **Dispatch** func.
