### ISSUE TITLE
Retaining in-memory state while navigating

### ISSUE THREAD

**Issue by mar1n3r0** [maxence-charriere/go-app#381]
> Changing the value of a variable used in the Render() method does not update the UI.
> 
> The way to tell the browser that the component appearance has to be updated is by calling the Compo.Update() method:
> 
> h.Update()
> Under the hood, the update method creates a new state that is compared to the current one. Then it performs a diff and updates only the HTML nodes where differences are found.

Could it be possible that we add custom fields in the struct which are not part of the `*Compo` and persist them across updates of the UI ? Essentially the idea is to have something like the state management pattern from the frontend frameworks world which can be used for keeping sensitive information like tokens in-memory only, an essential security practice for SPA applications:
[jwt-in-memory-persist](https://hasura.io/blog/best-practices-of-using-jwt-with-graphql/#jwt_persist)

Or maybe there is a better way to achieve that ?

**Comment by mar1n3r0** [comment]
Seems pretty tricky without native polymorphism and the ability to access interface type fields. Noticed the gymnastics you have used to compare them let alone to nest other structs...

```
func (c *Compo) update(n Composer) {
	aval := reflect.Indirect(reflect.ValueOf(c.compo))
	bval := reflect.Indirect(reflect.ValueOf(n))
	compotype := reflect.ValueOf(c).Elem().Type()

	for i := 0; i < aval.NumField(); i++ {
		a := aval.Field(i)
		b := bval.Field(i)

		if a.Type() == compotype {
			continue
		}

		if !a.CanSet() {
			continue
		}

		if !reflect.DeepEqual(a.Interface(), b.Interface()) {
			a.Set(b)
		}
	}
}
```

**Comment by maxence-charriere** [comment]
> Could it be possible that we add custom fields in the struct which are not part of the *Compo and persist them across updates of the UI ?

In what would it be different of putting it in your component?

**Comment by mar1n3r0** [comment]
Here is a quick example. I am sending a one-time token to the app as a query param, store it in memory and immediately remove it from the  url path. The expected behavior is this token to be retained in the app on refresh so that the user stays logged in. In reality it gets reset.

It is nothing new really just an attempt to implement a simple state management store react/vue style.

```
package main

import (
	"fmt"
	"syscall/js"

	"github.com/maxence-charriere/go-app/v6/pkg/app"
)

type hello struct {
	app.Compo
	name  string
	token string
}

func (h *hello) OnMount() {
	url := app.Window().URL()
	token := url.Query().Get("token")
	if len(token) > 0 {
		h.token = token
	}

	path := js.Global().Get("location").Get("pathname").String()
	hash := js.Global().Get("location").Get("hash").String()
	pathHash := path + hash
	js.Global().Get("history").Call("replaceState", "null", "null", pathHash)
}

func (h *hello) Render() app.UI {
	fmt.Printf("token: %v\n", h.token)

	return app.Div().Body(
		app.Main().Body(
			app.H1().Body(
				app.Text("Hello, "),
				app.If(h.name != "",
					app.Text(h.name),
				).Else(
					app.Text("World"),
				),
			),
			app.Input().
				Value(h.name).
				Placeholder("What is your name?").
				AutoFocus(true).
				OnChange(h.OnInputChange),
		),
	)
}

func (h *hello) OnInputChange(src app.Value, e app.Event) {
	h.name = src.Get("value").String()
	h.Update()
}

func main() {
	app.Route("/", &hello{})
	app.Run()
}

```

**Comment by maxence-charriere** [comment]
Keeping it between user refresh implies that it has to be saved somewhere, either local or session storage or index DB or cache. Maybe somewhere else that I am unaware of ^^.

For now, I feel that adding this kind of logic would complicate the component implementation.
Also, the component has for purpose to provide the logic of reusable tree nodes. It feels to me that this is something that could be built on the top but the responsibility of caching data between reload or tab does not belong to the component.

**Comment by mar1n3r0** [comment]
> Keeping it between user refresh implies that it has to be saved somewhere, either local or session storage or index DB or cache. Maybe somewhere else that I am unaware of ^^.

Trying to understand better, are you implying that update is not passing data on refresh ? 

```
func (c *Compo) update(n Composer) {
	aval := reflect.Indirect(reflect.ValueOf(c.compo))
	bval := reflect.Indirect(reflect.ValueOf(n))
	compotype := reflect.ValueOf(c).Elem().Type()

	for i := 0; i < aval.NumField(); i++ {
		a := aval.Field(i)
		b := bval.Field(i)

		if a.Type() == compotype {
			continue
		}

		if !a.CanSet() {
			continue
		}

		if !reflect.DeepEqual(a.Interface(), b.Interface()) {
			a.Set(b)
		}
	}
}
```

**Comment by maxence-charriere** [comment]
The refresh from javascript is overloaded to work with the package navigation but when the user presses the browser refresh button or shortcut, this is not catchable so the browser is requesting the server and reload the javascript, wasm, CSS, etc. It may seem faster since those resources are cached but the browser is, in fact, reloading everything.

**Comment by maxence-charriere** [comment]
You may have to play with cookies or storage to keep those data. Usually, it's not recommended to store the token in local storage. The local storage with this package is encrypted thought. 

To be honest, I''m not sure what is the best way to store those tokens.

It might be something I have to figure out soon.

**Comment by mar1n3r0** [comment]
Thanks, I will keep on digging. I am currently using the storage for non-sensitive data and will use the httponly cookie for the refresh token but for the access token the recommended way is to store it in memory as per this guide:
[jwt_persist](https://hasura.io/blog/best-practices-of-using-jwt-with-graphql/#jwt_persist)

**Comment by maxence-charriere** [comment]
Well thank you for asking stuff about the package. I’m curious about what you are building. Hope you ll get to your goal :).

**Comment by mar1n3r0** [comment]
It's a B2C platform but in general anything with users need that layer to be up to latest standards as the most critical part. Once released it will popularize your package too :)
