### ISSUE TITLE
Add ability to disable app.css

### ISSUE THREAD

**Issue by voldyman** [maxence-charriere/go-app#382]
I am using tailwind ui in the application and the default `app.css` files conflicts with it. 

can we have a way to disable the inclusion of `app.css`? or even make it off by default?

**Comment by maxence-charriere** [comment]
It needs app.css for loader and context menu. Maybe i can add an option to loads a light version of app.css that drops all the global styles. This should solve the compatibility issues.

Sent from my iPhone

On Apr 16, 2020, at 8:19 AM, Akshay Shekher <notifications@github.com> wrote:

﻿

I am using tailwind ui in the application and the default app.css files conflicts with it.

can we have a way to disable the inclusion of app.css? or even make it off by default?
