### ISSUE TITLE
Dismounter interface method not called

### ISSUE THREAD

**Issue by jwmach1** [maxence-charriere/go-app#383]
I think I've isolated an example application. I explicitly verified that the struct met the interface. But the `OnDismount` method is never called.  
https://github.com/maxence-charriere/go-app/wiki/Components#ondismount
```go
var _ app.Dismounter = &hello{}
```

If I read the go-app code correctly the problem lies in what is checked to be Dismounter, the root element is checked to be the Dismounter. But the `Composer` is checked to the `Mounter`.  So OnMount is called on my component, but OnDismount is never called. (from compo.go).

```go
func (c *Compo) dismount() {
	c.root.dismount()

	if dismounter, ok := c.root.(Dismounter); ok {
		dismounter.OnDismount()
	}
}
```
is `root` ever going to be a Dismounter?  Or was that meant to be `c.compo.(Dismounter)`?

Contrasted with the `Mounter` interface is checked on the Composer. Here from compo.Mount(compo Composer),
```go
	if mounter, ok := compo.(Mounter); ok {
		mounter.OnMount()
	}
```

Below is my sample main.go
```
package main

import (
	"fmt"

	"github.com/maxence-charriere/go-app/v6/pkg/app"
)

type hello struct {
	app.Compo
	name string
}
// explicitly verify interfaces to make sure I didn't typo something
var _ app.Dismounter = &hello{} 
var _ app.Mounter = &hello{}

func main() {
	app.Route("/", &hello{name: "page one"})
	app.Route("/another", &hello{name: "page two"})
	app.Run()
}

func (h *hello) Render() app.UI {
	return app.Div().Body( //<- this div is 'root' in the Compo
		app.H1().Body(
			app.Text(h.name),
		),
	).OnClick(h.clicker)
}
func (h *hello) clicker(_ app.Value, _ app.Event) {
	fmt.Println("hello clicker", h.name)
	app.Navigate("/another")
}

func (h *hello) OnMount() {  // <- works as expected
	fmt.Println("hello OnMount", h.name)
}

func (h *hello) OnDismount() { //<-- will not happen
	fmt.Println("hello OnDismount", h.name)
}
```

**Comment by maxence-charriere** [comment]
What component is loader when you navigate to `/another`?

**Comment by maxence-charriere** [comment]
Actually you are right! 
```
is root ever going to be a Dismounter? Or was that meant to be c.compo.(Dismounter)?
```

Thank you for spotting this!
