### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by alexsuslov** [maxence-charriere/go-app#388]
Hi
Firefox browser block loading files with wrong content type.
I can't find code rows for Options Method. Please help me to find.
I will repare that.
BRGD!
Alex

**Comment by maxence-charriere** [comment]
Hi @alexsuslov ,
Can you give me more info:
- What firefox version
- what file it is blocking
- tree of your repo too

**Comment by alexsuslov** [comment]
![Снимок экрана 2020-04-23 в 08 23 57](https://user-images.githubusercontent.com/3445074/80062243-efbe1d00-853b-11ea-9f4e-409da7784f3b.png)

**Comment by alexsuslov** [comment]
Found why it didn’t work. I added mux router.
