### ISSUE TITLE
New Callback after DOM Update

### ISSUE THREAD

**Issue by jwmach1** [maxence-charriere/go-app#400]
## purpose
I could really use another callback.  This one would happen after the DOM has been updated.

## usecase
I am using the Material Design Light https://getmdl.io/ CSS/JS UI "framework".  The components are upgraded by javascript functionality.  So when my Render method requests go-app to alter the DOM I need to also ask material-design-light to _upgrade_ those new components. Right now I'm achieving this by using a timer.  It's a brittle solution, and I know 1 second is longer than necessary, but I'm making SURE the DOM update is complete.
```go
func (c *MyComponent) Render() app.UI {
	time.AfterFunc(time.Second, func() {
		app.Window().Get("componentHandler").Call("upgradeDom")
	})
       return app.Div() ....
}
```

## proposed solution
So I propose a new lifecycle callback where I can drop the `time.AffterFunc`.  I'm just kind of throwing a method name out here `OnRender`.  You can likely come up with something better. Just so long as the method is called after the DOM is updated.
```go
func (c *MyComponent) OnRender {
	app.Window().Get("componentHandler").Call("upgradeDom")
}
```

**Comment by maxence-charriere** [comment]
Hi @jwmach1 , did you give a try to the [Updatable](https://pkg.go.dev/github.com/maxence-charriere/go-app/v6/pkg/app?tab=doc#Updatable) interface?

```go
func (c *MyComponent) OnUpdate() {
    app.Window().Get("componentHandler").Call("upgradeDom")
}
```

I may have to fix it though (just read back the code and found something wrong) but just to know, does this design would work?

**Comment by jwmach1** [comment]
First, I will admit I was fixed at v6.0, and did not look for a new release.  I'd only looked at the wiki to see if I'd missed something.  So I apologize for that. I updated to v6.5.0. I don't see OnUpdate getting called. I even through one of these little things in to make sure I implemented the interface right: `var _ app.Updatable = &Listing{}`.  

I took a quick look at the code, and I think I see a reason this won't work for my scenario. I only see the `OnUpdate` being called when the component changes from what is already rendered.  I also need it on first Render.

Where will Updatable fit in the [Lifecycle](https://github.com/maxence-charriere/go-app/wiki/Components#lifecycle)?

**Comment by maxence-charriere** [comment]
Thanks for trying.

I think I know how to fix it. If you can hold on a little bit, I need it fixed too so I 'll do it next week.

**Comment by maxence-charriere** [comment]
Hello @jwmach1 ,

I have this version:
```sh
go get -u github.com/maxence-charriere/go-app/v6@dd925ec
```

It has been doing the job for me. Could you give a try and tell me if it works with your scenario?

**Comment by maxence-charriere** [comment]
Oh I see you also need it at first render. Just make me think, you could use:

```go
func (c *MyComponent) Render() {
    app.Dispatch(func() {
         app.Window().Get("componentHandler").Call("upgradeDom")
    })

     return app.Div()
}
```

This should queue the given function to the UI goroutine and execute is right after Render is called.

**Comment by jwmach1** [comment]
Working Great!
