### ISSUE TITLE
Website seems to have been hacked

### ISSUE THREAD

**Issue by adsouza** [maxence-charriere/go-app#401]
See https://luck.murlok.io/

**Comment by maxence-charriere** [comment]
I don’t see anything that would make me think it has been hacked. Could you describe how it seems to have been hacked ?

**Comment by adsouza** [comment]
![Screen Shot 2020-05-31 at 6 24 15 PM](https://user-images.githubusercontent.com/275832/83364012-fa09dd00-a36b-11ea-8925-e6cbb047b923.png)
This is what I see.

**Comment by adsouza** [comment]
Ohhhh, that's a demo app!!! I was expecting to see a website about this project so that particular app threw me off because it looked too spammy!

**Comment by maxence-charriere** [comment]
It looks normal to me. What is not normal ?
