### ISSUE TITLE
Whether to consider compression support for wasm files?

### ISSUE THREAD

**Issue by golangper** [maxence-charriere/go-app#405]

**Comment by maxence-charriere** [comment]
Hello
Thanks for the feedback.
 
It was a decision to not include compression for .wasm file right out of the box.
There is a couple of reasons for this:
- app.wasm is a static resource that can be located on a remote bucket (like S3)
- Some cloud provider offers compression right out of the box (like Google Cloud App Engine) and if not implemented correctly, it can mess up compatibility with those providers (already tried in previous versions)
- `app.Handler` is a standard Go `http.Handler`. You can use a decorator from some other dedicated package that will probably be better at compressing files
