### ISSUE TITLE
Feature Request: Aria Support

### ISSUE THREAD

**Issue by jwmach1** [maxence-charriere/go-app#410]
In the same way that the DataSet  `DataSet(k string, v interface{})`  method supports data prefixed attributes, could there be an `Aria` method to support Accessible Rich Internet Applications?

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Web_applications_and_ARIA_FAQ
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA

**Comment by maxence-charriere** [comment]
Fixed in v7
