### ISSUE TITLE
app.Navigate(string) causing browser to reload app

### ISSUE THREAD

**Issue by jwmach1** [maxence-charriere/go-app#412]
sometimes it goes back to older cached versions. I've tried both leaving the `app.Handler.Version`  unspecified and also specifying a unique version.
Given that I have called `app.Route("/thing", thingComponent)` then somewhere else, I call `app.Navigate("/thing")`. I can then watch the browser dev-console make all the network calls that occur as the PWA reloads and displays the right page (but usually the wrong version)

* anchor tags that change to assigned routes have no problem -- just my data-fetch network call is made
* `app.Window().Get("history").Call("back")` has no problem -- just my data-fetch network call is made

Maybe this is just a need for an example of uring Navigate within the https://github.com/maxence-charriere/go-app/wiki/Routing documentation.

**Comment by maxence-charriere** [comment]
Hi @jwmach1 , thanks for pointing the problem.

I 'll look into it.
In the meantime, could you tell me which version are you running?

**Comment by jwmach1** [comment]
6.6.1.  I know it goes back to at least 6.5.0. It happens both on localhost and the deployed host. (I'm not ready to share the URL, not being secretive, just.... it's definitely still _alpha_ )

**Comment by maxence-charriere** [comment]
mmm, when you go to the console and click on your link that way, do you see a panic?

**Comment by walgenbach** [comment]
I am tracing something similar. I have routes local to the wasm program that try and fetch from the server that started happening with v6.5.0. It works correctly in v.6.4.1.

**Comment by jwmach1** [comment]
@maxence-charriere I'm not sure what you are asking for.

**Comment by maxence-charriere** [comment]
@jwmach1 
- go on chrome console
- trigger you link
- before it reloads you may see a quick panic

**Comment by walgenbach** [comment]
I don't get a panic.

The change in behavior that I am seeing is this:

`func main() {
        directory := NewDirectory("/")
        login := NewLogin()
        app.Route("/", directory)
        app.Route("/login", login)
        app.Run()
}`

Somewhere in the directory object, there is a call to Navigate("/login").

In v6.4.1 and lower, it calls the Render function in login. In v6.5.0, it tries to load the url http://<server:port>/login, which fails because that url doesn't exist on the server. 

It sounded similar to what was reported in this ticket, so I thought I'd add information in case it was helpful. That's all.

**Comment by maxence-charriere** [comment]
Found it, releasing a new version. Thank you again for this :)
