### ISSUE TITLE
Add Static site generator

### ISSUE THREAD

**Issue by lu4p** [maxence-charriere/go-app#415]
I would like to host a site created with go-app on gh-pages in order for this to work I would need an option to create static files from an app.handler.

I thought of something like this:
```go
package main

import (
	"github.com/maxence-charriere/go-app/v6/pkg/app"
)

func main() {
	h := &app.Handler{
		Title:  "Hello Demo",
		Author: "Maxence Charriere",
	}

	h.GenerateStatic("directory")
}
```

Where GenerateStatic writes all needed files to a directory.

**Comment by maxence-charriere** [comment]
I need to do some experiments to see if it's possible.
Thanks for the feedback.

**Comment by maxence-charriere** [comment]
Hey @lu4p ,

I dug into this issue and look like I got something working:
- [example file](https://github.com/maxence-charriere/goapp-github-pages/blob/master/main.go)
- [Working Github page](https://maxence-charriere.github.io/goapp-github-pages/)

I had to do some architecture changes to make it append so it will be available on v7.0.0.
I should release this tomorrow or Monday.

Thanks again for this feedback, 
Feel like GitHub Pages support was a super good idea!

**Comment by lu4p** [comment]
Nice looks promising

**Comment by lu4p** [comment]
Tried it, nice that you got it working this fast :+1:  

You shouldn't use absolute paths to include the files from the [`index.html`](https://github.com/maxence-charriere/goapp-github-pages/blob/37fee4fe9d5810ac852f340f02dc73a96f4f1d60/index.html#L16), [`app-worker.js`](https://github.com/maxence-charriere/goapp-github-pages/blob/37fee4fe9d5810ac852f340f02dc73a96f4f1d60/app-worker.js#L9) and [`app.js`](https://github.com/maxence-charriere/goapp-github-pages/blob/37fee4fe9d5810ac852f340f02dc73a96f4f1d60/app.js#L6) to make it more portable. I know that this works for html, I don't know if it is possible to use relative paths in the js, but you could also work around that by getting the current url `window.location.href` and appending the relative paths to it. 

I think this would then allow to remove the `app.ResourceProvider` altogether and just have a single static directory which can be hosted anywhere (correct me if I'm wrong).

**Comment by maxence-charriere** [comment]
The app.Resource provider is not used only for static website gen. It is also used to define other configurations based on http.Handler. Having it that way allows to have a common logic to handle resources, whether they are on a localhost, a remote bucket or available as a static website.

**Comment by maxence-charriere** [comment]
This is now available with version 7: https://github.com/maxence-charriere/go-app/releases/tag/v7.0.2

**Comment by lu4p** [comment]
Hey @maxence-charriere,
I built a web app for [astextract](https://github.com/lu4p/astextract) using github pages. 

Web app: https://lu4p.github.io/astextract/

Works great!

Thanks for implementing it! :tada:

**Comment by maxence-charriere** [comment]
Hey @lu4p 
Thanks again for this issue. I'm gonna implement go-app doc and deploy it as a github page too.

Also, just wanted to tell you that I just pushed an update that makes Github Pages generated PWA installable with Chrome.

If you are okay, I would like to put your app in the Live app section of the readme. Just I would like to take a screenshot that makes it run in its own window so you would likely have to bump the go-app version to v7.0.3.

Let me know if you are ok with this.

Best,
Maxence

**Comment by lu4p** [comment]
@maxence-charriere nice update.

I would like to get featured can update today.
