### ISSUE TITLE
Bug: Static site generator doesn't copy wasm 

### ISSUE THREAD

**Issue by lu4p** [maxence-charriere/go-app#424]
Hey @maxence-charriere,
I built a web app for [astextract](https://github.com/lu4p/astextract) using github pages. 

Web app: https://lu4p.github.io/astextract/

Works great, thanks for implementing it! :tada: 

I noticed that if you specify a path other than the current directory for the static site generator, the `app.wasm` isn't copied to the `web` directory automatically, but only an empty `web` directory is generated.

**Comment by maxence-charriere** [comment]
I'm glad you were able to achieve your project with the help of go-app :)

For the `app.wasm` file, It is correct, this is specified in the doc => https://pkg.go.dev/github.com/maxence-charriere/go-app/v7/pkg/app?tab=doc#GenerateStaticWebsite

The reason for this is that the library does not compile wasm binaries.

**Comment by lu4p** [comment]
Ok I thought I need to have the same directory layout as in the server directory, but the app.wasm is not needed by the generator makes sense.
