### ISSUE TITLE
Webworker

### ISSUE THREAD

**Issue by gedw99** [maxence-charriere/go-app#425]
Can your system produce a wasm running inside a webworker ? I am because webworker has access to http and and forces everything to be async

**Comment by maxence-charriere** [comment]
Hello @gedw99 
It is currently not launched in a web worker. 

What would it bring to the current implementation? 
async is done with **goroutines** and HTTP can be done with `net/http`

**Comment by gedw99** [comment]
> Hello @gedw99
> It is currently not launched in a web worker.
> 
> What would it bring to the current implementation?
I did not know the current approahc allowed http and goroutines. All good then
> async is done with **goroutines** and HTTP can be done with `net/http`
