### ISSUE TITLE
Where can I find the documents with go-app?

### ISSUE THREAD

**Issue by daniel-hutao** [maxence-charriere/go-app#435]
Where can I find the documents with go-app?

**Comment by maxence-charriere** [comment]
Hi @daniel-hutao 
The documentation is available on Godoc and Github Wiki.
- https://pkg.go.dev/github.com/maxence-charriere/go-app/v7/pkg/app
- https://github.com/maxence-charriere/go-app/wiki

I'm currently working on a dog fooded one but this is not yet ready.

**Comment by maxence-charriere** [comment]
Just released a dogfooded documentation.

=> https://go-app.dev
