### ISSUE TITLE
Supporting a "new version available" button

### ISSUE THREAD

**Issue by jwmach1** [maxence-charriere/go-app#440]
As I've used other PWAs that have the "we have a new version, click this button to update". I wanted to have that option. To support this, 
* I return the current version in a header from every service call
* In the client,  I call `app.Getenv("GOAPP_VERSION")` to get the client version
* if these do not match, I display the "new version" button
* when the button is clicked, I call `app.Window().Get("location").Call("reload", "true")` to force a page reload

What I've experienced is that Chrome does not always load up the latest version even though I watch the webpage reload.  
Secondarily, I also see the go-app `console.log("installing app worker {{.Version}}");` logs which sure, starts the latest worker, but it does not start that version of the client.  I see the old behavior, there is not a new call to `main`, and `GOAPP_VERSION` continues to report the old version.

Am I missing a step? Making it too hard?  This seems like a natural feature to support.

**Comment by maxence-charriere** [comment]
I agree, now I made [Murlok.io](https://murlok.io) run for almost 2 months, I was also thinking that it would be a better experience to make this possible.
Gonna try to find the right API for doing this and implement it.

**Comment by pojntfx** [comment]
As per https://stackoverflow.com/questions/46881906/force-reload-skipping-service-worker-in-javascript, I tried refreshing with:

```bash
navigator.serviceWorker.getRegistration().then(function(reg) {
  if (reg) {
    reg.unregister().then(function() { window.location.reload(true); });
  } else {
     window.location.reload(true);
  }
});
```

Seems to work. I might take a look at implementing this, would there be anything wrong with using the latest git commit hash to check if the app has updated or would a env variable (like the given `GOAPP_VERSION`) be preferable? The latter I believe could make deployment a bit harder (because the CI/CD system would require the env variable to be set and updated upon a new release) IMHO but would of course be a bit more flexible. The `http.handler` could serve the version number (like `/version.json`) and then, using a `fetch` call to `/version` without caching the resource (and if the client is online), unregister the service loader and force-reload the page if the version numbers don't match.

**Comment by jwmach1** [comment]
I tested with this yesterday.  And yes, it also see that it works the reload triggering a restart to the new version on the first try.  Where in my original attempt to call only `window.location.reload(true)` would take a couple tries -- the user had to press the button twice (or three times). But putting the `reload` call in javascript pointed out that the `reload(true)` is deprecated.  However, it's also not needed!  This is the method I'm calling upon clicking the "new version available" button:

```js
function reloadApp() {
    navigator.serviceWorker.getRegistration().then(function(reg) {
        if (reg) {
          reg.unregister().then(function() { window.location.reload(); });
        } else {
           window.location.reload();
        }
      });
}
```

My two cents regarding your questions about where to pull the version from to support CI/CD.  I follow the [12 factor app](https://12factor.net/) and pull config from the environment, then if not present use a _sensible_ default. Those defaults end up being my local environment. In your suggestion to just use the latest git sha (or something like `git describe --tags`) is a fine idea, but it should still be over-ride-able _somehow_ to keep go-app flexible.

**Comment by maxence-charriere** [comment]
Hey there, just a little explanation about this.
I thought a good way to integrate this feature was to have a component interface that allows listening app update events.

So there is now the [Updater](https://go-app.dev/reference#Updater) interface that allows doing this.
Here is an example of how to use it: https://go-app.dev/lifecycle#listen-for-updates

It allows customizing the way you want to notify your user that there is an update available while keeping a mechanism consistent with how things are done within this package.

Hope it will solve the issue. Don't hesitate to reopen or submit another issue with it does not solve your problem.
