### ISSUE TITLE
Information request for a rather complex scenario

### ISSUE THREAD

**Issue by SoftExpert** [maxence-charriere/go-app#441]
Hello,

Is it possible to implement the following scenario with the current app level :
- have a button on the UI
- user clicks the button
- button becomes disabled
- the click also triggers a number of different Go Routines tho be executed on the server
- each routine will update some shared variable for the current session (i.e. a counter for OK routines, a counter for KO routines and a slice of strings for some "log messages")
- when the counters are updated, corresponding progress bars are updated as well
- when the last Go Routine has been finished, the button becomes active again and a text message is displayed

Thank you in advance for any feedback !

Best regards,
SoftExpert

**Comment by maxence-charriere** [comment]
Hello @SoftExpert.

Yes this kind of scenario can be implemented.
Here is a basic example.

## Code

```go
type complexScenario struct {
    app.Compo

     Total int
     OK    int
     KO    int
     Logs  []string
}

func (c *complexScenario) Render() app.UI {
     return app.Div().
          Body(
               app.H1().Text("Complex scenario"),
               app.P().Text("Example for a complex scenario"),
               app.P().Body(
                    app.Button().
                         Disabled(c.OK+c.KO != c.Total). // This could also be done with css class.
                         OnClick(c.onButtonClick).
                         Text("Start"),
                ),

               app.H2().Text("Progress"),
                    app.P().Body(
                         app.Progress().
                              Value(c.OK+c.KO).
                              Max(c.Total),
                    ),

               app.H2().Text("Logs"),
                    app.P().Body(
                         app.Range(c.Logs).Slice(func(i int) app.UI {
                              return app.Div().Text(c.Logs[i])
                        }),
                    ),
            )
}

func (c *complexScenario) onButtonClick(ctx app.Context, e app.Event) {
     c.Total = 5
     c.OK = 0
     c.KO = 0
     c.Logs = nil
     c.Update()

     go c.fakeJob(1, true)
     go c.fakeJob(2, true)
     go c.fakeJob(3, true)
     go c.fakeJob(4, true)
     go c.fakeJob(5, false)
}

func (c *complexScenario) fakeJob(id int, result bool) {
     c.log("launching job %v", id)

     d := time.Duration(rand.Intn(5)+1) * time.Second
     time.Sleep(d)

     if !result {
          c.incKO()
          c.log("job %v failed", id)
          return
    }

     c.incOK()
     c.log("job %v succeeded", id)
}

// Functions below are the ones that update the UI. Since they are called from
// new goroutines, Dispatch() function is used to ensure the component field
// are updated on the UI goroutine.

func (c *complexScenario) incOK() {
     app.Dispatch(func() {
          c.OK++
          c.Update()
    })
}

func (c *complexScenario) incKO() {
     app.Dispatch(func() {
          c.KO++
          c.Update()
    })
}

func (c *complexScenario) log(format string, v ...interface{}) {
     app.Dispatch(func() {
          c.Logs = append(c.Logs, fmt.Sprintf(format, v...))
          c.Update()
    })
}
```

## Rendering
I tested it on my work in progress documentation app:
<img width="1075" alt="Screen Shot 2020-08-25 at 7 21 28 AM" src="https://user-images.githubusercontent.com/2692731/91126228-d07afc00-e6a3-11ea-8f3a-88adadacc375.png">
<img width="1075" alt="Screen Shot 2020-08-25 at 7 21 34 AM" src="https://user-images.githubusercontent.com/2692731/91126238-d53fb000-e6a3-11ea-8ed1-d2570f55c9ee.png">
<img width="1075" alt="Screen Shot 2020-08-25 at 7 21 40 AM" src="https://user-images.githubusercontent.com/2692731/91126291-f1435180-e6a3-11ea-9a73-d3b0661afb2e.png">

**Comment by SoftExpert** [comment]
Wonderful, many thanks !

But the Go Routines are executed by the WASM on the client and not by the server - the proof being that I could stop the server and the routines were still executing.
Will this mean that I need to implement some REST methods to really execute the routines on the server ?

Best regards,
SoftExpert

**Comment by maxence-charriere** [comment]
Well, it is a progressive web app that runs on WebAssembly.
All the code provided runs on the browser.

You will have to implement a rest API if that is what you need.

**Comment by SoftExpert** [comment]
I see , thanks for the confirmation.

In this case, how can I define additional handlers on the server so that I can have it also process REST requests ?
Adding `http.HandleFunc("/test", testHandler)` will fetch the page code instead of the real response; actually the app will hijack the response before my custom handler can be called.

Would this require a change in the app code ? Or is there another way ?

Best regards,
SoftExpert

**Comment by maxence-charriere** [comment]
you can implement your own `http.Handler` or use something like: 
```go
http.HandleFunc("/test", testHandler)
http.Handle("/", app.Handler{})
err := http.ListenAndServe(":8080", nil)
```

**Comment by SoftExpert** [comment]
With this answer I have everything I need; thank you very much !

Best regards,
SoftExpert

**Comment by maxence-charriere** [comment]
You are welcome, I hope You will be able to build what you want with this package. And don’t forget to send a link When you are done 😊!

**Comment by SoftExpert** [comment]
A link I cannot, because the app is not exposed to Internet, but a screenshot, yes.
![image](https://user-images.githubusercontent.com/1254018/91541787-27d7d100-e91d-11ea-9915-d42576b3b2df.png)

I wonder if it is possible to package in a single file my custom CSS, JS, images and the GO binary, so that I can deploy a single file containing everything ...
