### ISSUE TITLE
app.Window().CursorPosition() allways returns 0,0

### ISSUE THREAD

**Issue by RELAXccc** [maxence-charriere/go-app#444]
Hello, idk. if it's only for me, but calling 

`x,y := app.Window().CursorPosition()`

always returns 0,0 for me.

I am using 	github.com/maxence-charriere/go-app/v7 v7.0.5
but my app does not use the usual rendering that was intended. 
What does this use internally? The "onmousemove" event?
If it workes for everyone else except me, maybe it should be hooked on the document directly and 
not the usual <div>? Idk

Greetings,

**Comment by RELAXccc** [comment]
ok, i got it to work. Before I created a canvas with go-canvas or using` return app.Canvas()` and i could not get .CursorPosition

now i added an empty EventListener to the canvas (with .OnMouseMove(...)) now suddenly app.Window().CursorPosition() can register the cursor position on the canvas

**Comment by maxence-charriere** [comment]
Hey, yes, i got this whenever a mouse event is subscribed with go.
