### ISSUE TITLE
Linked CSS

### ISSUE THREAD

**Issue by charles-d-burton** [maxence-charriere/go-app#448]
I think I have CSS working with the local server by placing the .css files in the `web/` directory of my project.  The question I have is whether it's possible to load a ref link?  For instance I'd like to use the material icon set but I'm not sure how I could get the .woff files to work or rather how to use this `<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">` instead.

**Comment by maxence-charriere** [comment]
Just put the address in the Styles field on the handler.

**Comment by charles-d-burton** [comment]
That did it!
