### ISSUE TITLE
use too much memory

### ISSUE THREAD

**Issue by ruanwenfeng** [maxence-charriere/go-app#452]
Refresh the page frequently
![image](https://user-images.githubusercontent.com/27943586/97704860-1b731e80-1aee-11eb-855c-ab6c07b011c7.png)

**Comment by maxence-charriere** [comment]
Might be linked to how I implemented this one, I tried it on my other websites:
- https://murlok.io
- https://lofimusic.app

And I did not notice that issue.
With multiple refreshes, it goes up but the memory is regularly free by the garbage collector.

I tested it on MacOS though.
I'll take a look further to see what did I mess up.

Thanks for reporting this.

**Comment by ruanwenfeng** [comment]
@maxence-charriere It seems a chrome bug. 
https://github.com/emscripten-core/emscripten/issues/8126
