### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [recovered]

### ISSUE THREAD

**Issue by gepengscu** [maxence-charriere/go-app#453]
I create a child component, and got runtime error when I click close button.  Icons.Close() return a icon component. Why does Icons.Close().Render() method must be called?
```go
type (
	tabItem struct {
		tabControlElement
		index   int
		Icon    string
		ID      string
		Caption string
		Page    app.UI
	}
)
func (a *tabItem) close(ctx app.Context, e app.Event) {
	a.Caption = "closed"
	//a.control.Remove(a.index)
	a.Update()
}

func (a *tabItem) Render() app.UI {
	return app.Div().
		ID(a.ID).
		Body(
			app.Div().Body(
				app.Span().
					Body(
						Icons.ByName(a.Icon),
						app.Text(a.Caption),
					),
			),
                        // app.Button().Text("E").OnClick(a.close), //OK!
                        // Icons.Close().OnClick(a.close).Render(), //OK!
			Icons.Close().OnClick(a.close), // failed!!!!!
		)
}
```

**Comment by maxence-charriere** [comment]
```
Icons.Close().Render() method must be called?
```
It should not.

I need to see your `Icons.Close()` implementation to help you with this.

**Comment by gepengscu** [comment]
var Icons AntIcons

type AntIcons int

func (a AntIcons) Close() *AntIcon {
	return Icon().
		Style("aria-label", "close").
		Style("tabindex", "-1").
		Class("anticon-close").
		Body(
			app.Raw(`<svg viewBox="64 64 896 896" focusable="false" class="" data-icon="close" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M563.8 512l262.5-312.9c4.4-5.2.7-13.1-6.1-13.1h-79.8c-4.7 0-9.2 2.1-12.3 5.7L511.6 449.8 295.1 191.7c-3-3.6-7.5-5.7-12.3-5.7H203c-6.8 0-10.5 7.9-6.1 13.1L459.4 512 196.9 824.9A7.95 7.95 0 00203 838h79.8c4.7 0 9.2-2.1 12.3-5.7l216.5-258.1 216.5 258.1c3 3.6 7.5 5.7 12.3 5.7h79.8c6.8 0 10.5-7.9 6.1-13.1L563.8 512z"></path></svg>`),
		)
}

**Comment by maxence-charriere** [comment]
I would also need the implementation of Icon.
That is a lot how nested things for a simple icon component.

**Comment by gepengscu** [comment]
Icons.Close().OnClick(a.close) create new AntIcon component dynamically when tabItem.Render(). Panic is triggered on the second tabItem.Render() call. I save icon as a field of tabItem struct after the first create, and the panic disappeared.  
type tabItem struct {
		app.Compo
		Caption string
		closeIcon       *AntIcon
	}
func (a *tabItem) init() *tabItem {
	a.closeIcon = Icons.Close().OnClick(func(ctx app.Context, e app.Event) {
		// todo remove the tab
	})
	return a
}

func (a *tabItem) Render() app.UI {
	return app.Div().
		Body(
		    app.Text(a.Caption+"123"),
                    a.closeIcon,
		)
}
I create icon in tabItem.Render() func and node.mount(ui) mount the first icon only which caused the exception. 
Is it right?
