### ISSUE TITLE
How to use the Docs

### ISSUE THREAD

**Issue by morpheus747** [maxence-charriere/go-app#454]
i'm realy trying to excecute the documentation from the godoc branch in my pc, but i can't i modify some files that show /go-app to the base because in the server show 404 not found. 
Change some other .css to work 
At least found a website gray with modules but can't load anyone. Can guide me please.

**Comment by maxence-charriere** [comment]
You should be able to try it by:
- checkout the branch
- go to the repo root dir
- launch it by typing make run

**Comment by morpheus747** [comment]
Wow, i'm able to run the docs, is amazing.

I have many problems compiling it, because i use windows 10, i will update the make script to detect
if windows use .exe to excecute, use $Env:GOOS to set the environment variables and so on.
And will update the readme to explain people how to use the docs.

Is a great doc! realy but is so hidden! I need to dig into the repo to found, i think this project is awesome but need to expose the docs to attract people.

If you see the other wasm golang frameworks only vugu have docs visible and this is very attractive to a project.
I see you put too much effort in this almos extensive documentation but is not "easy available" to end users.

I Will work on this i think this project have bright future.

Thanks maxence-charriere

**Comment by maxence-charriere** [comment]
It is because the doc is a work in progress. I plan to put it online on github pages very soon :).

**Comment by morpheus747** [comment]
how can i help?

**Comment by maxence-charriere** [comment]
Thanks for proposing your help. There is not that much remaining but once I release it, should be probably by the end of next week. By reviewing articles and opening PR :).

**Comment by maxence-charriere** [comment]
Hey @morpheus747 
I just put the documentation online. You can see it on https://go-app.dev.

Thanks again for the kind words and proposing help :)
