### ISSUE TITLE
Legacy Website

### ISSUE THREAD

**Issue by morpheus747** [maxence-charriere/go-app#455]
I have an old "wordpress-like" website, and i need to implement a Quote system with input type=range...

The website already exist and i want to create a <div> tag or something like that and mount the wasm app inside tha tag.
after that the  app will create the inputs body etc etc inside that tag and work like expected.

I don't see an example on how can i "mix" "blend" with an already existing html application.

Is there a way i can "bind" the app to load inside an already created html tag ?

**Comment by maxence-charriere** [comment]
This is hardly possible right now. What makes the usage of wasm easy here is that the app.Handler is doing the magic of providing all the support file and mechanisms to make it work.

Mixing it with a legacy website would require that you manually add those files in your current webpage and it would require some modifications in how the dom elements are inserted to ensure it does not get outside the scope.

Would be interesting to have it but this is not small modifications that I have time to prioritize right now, and it does not solve the first issue of providing the wasm support files.
