### ISSUE TITLE
FileSystem API abstraction?

### ISSUE THREAD

**Issue by drognisep** [maxence-charriere/go-app#463]
I might be missing something about how this works, but would it be possible to provide an abstraction to the [FileSystem API](https://developer.mozilla.org/en-US/docs/Web/API/FileSystem) callable from the WASM side? It seems like it would be fairly doable since support is pretty great these days.

**Comment by maxence-charriere** [comment]
Look like it is still prefixed and experimental.
I ll add it to the nice to have list.

Just to have and idea, what is your use case with this?

**Comment by drognisep** [comment]
@maxence-charriere
Got it, that's works for me. From what I understand, I could use the sandboxed virtual filesystem in a way that is very similar to how I would use an actual filesystem in an installed native app, which is more of what I'm used to, and opens up a lot of possibilities from the WASM side. Consider the idea of a web based IDE or data processor that mostly works off of the user's local environment, even in an offline context. Then optionally uses the server for syncing and sharing information/code/whatever when a network connection is available.

I don't know how persistent the virtual filesystem is, but if it's long lasting then it seems like that would be possible. Still lot's of unknowns for me, and I'll need to do more research to see if what I'm going for is even doable.

Keep in mind that I'm a back end dev looking for more flexible, native-like deployment models for easy to make UIs, so feel free to tell me that this just isn't how all this works. :)

**Comment by drognisep** [comment]
It looks like Chrome specifically [provides the ability to interact with the actual local file system](https://web.dev/file-system-access/), but I don't think it's reasonable to add a Chrome only feature to a more holistic PWA framework. In which case this issue might unfortunately be DOA until we get more standards based support from browsers. :(
