### ISSUE TITLE
How to kill the localhost running on port 8000

### ISSUE THREAD

**Issue by zaferkadi** [maxence-charriere/go-app#464]
Hello, 
I ran my first example following [Getting Started](https://go-app.dev/start), ran the make build, ran make run and everything is working great.
After I hit ctrl+c on terminal to stop the program, my app is still running on localhost:8000, how do I kill the app?

**Comment by maxence-charriere** [comment]
Ctrl + c should term the server. There is no magic here it is a standard http handler.

Does it do the same with another go server?

**Comment by maxence-charriere** [comment]
You can also try to properly shutdown the server. See standard net/http documentation for this.

**Comment by maxence-charriere** [comment]
Oh sorry, your app is a pwa. That mean it is available offline. It is cached in the browser.

**Comment by zaferkadi** [comment]
@maxence-charriere yes, it's cached, I eventually cleared the cache from the dev tools and the app is gone.
I also noticed that everytime I make a change inside my go code and repeate the same process (make build, make run) it wouldn't take effect, not sure if my browser is not picking up the new changes for a reason I'm not aware of.

**Comment by maxence-charriere** [comment]
When you change the code, the browser detect the changes and recache everything in background. The modifications are visible at next load so you have to reload the page 2 times.

Sent from my iPhone

On Dec 16, 2020, at 12:34 AM, Zafer <notifications@github.com> wrote:

﻿

@maxence-charriere<https://github.com/maxence-charriere> yes, it's cached, I eventually cleared the cache from the dev tools and the app is gone.
I also noticed that everytime I make a change inside my go code and repeate the same process (make build, make run) it wouldn't take effect, not sure if my browser is not picking up the new changes for a reason I'm not aware of.

**Comment by zaferkadi** [comment]
@maxence-charriere when I change the code, chrome does not pick up the changes, I followed the getting started page, I don't think I have missed any step.
So basically I need to rebuild and run everytime.

**Comment by maxence-charriere** [comment]
Yes, because the browser is detecting changes on   app-worker.js to know if the website is updated. When launching the server, the handler provide a app-worker.js with a different version number. So you have to relaunch the server to see the change.

Look like there is some doc missing that explains that.
