### ISSUE TITLE
How to integrate with a charting library

### ISSUE THREAD

**Issue by dilipkk-foyernet** [maxence-charriere/go-app#469]
Hi @maxence-charriere,
Thanks for this library and this looks interesting for our use-case, we would like to integrate with https://github.com/go-echarts/go-echarts. Can you please guide me with this?

Thanks again,
Dilip

**Comment by dilipkk-foyernet** [comment]
```go
func (c *myCompo) Render() app.UI {
	return app.Raw(`
	<svg width="100" height="100">
		<circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
	</svg>
	`)
}```

This is useful I feel and we can reference CSS files: https://go-app.dev/static-resources#in-css-files

**Comment by maxence-charriere** [comment]
I'm don't understand what you want to do.
If you want to add a css file just drop it in the web directory and reference it into the handler => https://go-app.dev/static-resources#in-handler

**Comment by dilipkk-foyernet** [comment]
I got it, I will give it a try.
