### ISSUE TITLE
app.wasm URL is incorrect when using Resources

### ISSUE THREAD

**Issue by dmitryrn** [maxence-charriere/go-app#474]
I have that code
```go
func main() {
	resources := app.RemoteBucket("https://cdnjs.cloudflare.com")
	styles := []string{"/ajax/libs/materialize/1.0.0/css/materialize.min.css"}
	scripts := []string{"/ajax/libs/materialize/1.0.0/js/materialize.min.js"}

	http.Handle("/", &app.Handler{
		Name:      "Game list",
		Resources: resources,
		Styles:    styles,
		Scripts:   scripts,
	})
	http.Handle("/game", &app.Handler{
		Name:      "Game page",
		Resources: resources,
		Styles:    styles,
		Scripts:   scripts,
	})

	err := http.ListenAndServe(":8000", nil)
	if err != nil {
		log.Fatal(err)
	}
}
```

In Chrome I'm getting this error when I use cmd+shift+r (hard reload):
<img width="666" alt="image" src="https://user-images.githubusercontent.com/25539852/103180120-dd9f3600-48a3-11eb-8d80-73dbd43943f2.png">

But when I don't use hard reload, it both fetched app.wasm from localhost and from cloudflare.

While in Safari it works fine. 

Also, for me, external CSS and JS is only loading on the /game page and not on the / page

**Comment by maxence-charriere** [comment]
Your styles and scripts does not point to the web directory. 

Should be /web/ajax/...

https://go-app.dev/static-resources
