### ISSUE TITLE
<a> tag handling bug: target="_blank" property unsupported.

### ISSUE THREAD

**Issue by beanpole135** [maxence-charriere/go-app#481]
There appears to be something in the go-app handling that is disabling the ability to have A links open in a new tab using the target="_blank" property. 
I have tried using `HTMLRaw('<a href="test_url" target="_blank">TEST</a>')` and `app.A().Target("_blank")`.
The HTML code in the browser appears to be generated correctly when I inspect the page, but clicking the link (with valid URLs/syntax as tested on another site) within the go-app appears to get intercepted and blocked somewhere.

Version: "github.com/maxence-charriere/go-app/v7 v7.0.4"

**Comment by maxence-charriere** [comment]
That is correct. Navigation is hijacked for single app purpose. Every links that does not have the same host should be launched in a new tab. The contrary should not behave as you describe so there is a bug to fix. Will take a look on it.

**Comment by beanpole135** [comment]
Thanks for the quick fix!!
