### ISSUE TITLE
Documentation issues in start.md

### ISSUE THREAD

**Issue by herzo1** [maxence-charriere/go-app#492]
The instructions under **Build and run** are slightly incorrect. 
The command to build the user interface should specify the app.go file:

```bash
# Build the wasm program that contains the user interface.
GOARCH=wasm GOOS=js go build -o web/app.wasm app.go
```

The command to build the server should specify the main.go file and the name of the binary, hello in this case:

```bash
# Build the wasm program that contains the user interface.
go build -o hello main.go
```

The makefile under **Tips** would need the same changes.

**Comment by maxence-charriere** [comment]
The default behavior of go build (without -o) is to take the directory name for the resulting binary. In that case hello.
