### ISSUE TITLE
compileerror [not work]

### ISSUE THREAD

**Issue by prospero78** [maxence-charriere/go-app#494]
```text
compileerror: webassembly.instantiatestreaming(): expected magic word 00 61 73 6d, found 7f 45 4c 46 @+0
```
Google Chrome (official build 88.0.4324.9, 64 bit, linux)
Server find main ("server" as ELF) and load into browser as "app.wasm". "app.wasm"  compiled as ELF(!???)

Hmmmm.... Im modify "Makefile" (splitted string with GOOS and command to build join to one string. Its solved my problem).

Issue closed.

**Comment by maxence-charriere** [comment]
Are you sure app.wasm is compiled for wasm architecture?
