### ISSUE TITLE
Fragment based routing

### ISSUE THREAD

**Issue by chwevans** [maxence-charriere/go-app#495]
Is it possible to support fragment based routing instead of pure path based routing? The use case is serving the application in a static website context. If we wanted to support path based routing, we would need to have a 404 handler serve the WASM on every load rather than just leaving it to /.

**Comment by maxence-charriere** [comment]
Not sure about what you mean by fragment-based routing. Do you have an example of the use case like what URL wuld serve what vs what it is doing right now ?
