### ISSUE TITLE
Component Reuse During Rendering Does Not Replace Event Handlers

### ISSUE THREAD

**Issue by jwmach1** [maxence-charriere/go-app#499]
I've setup an example with 2 items. The user wishes to delete both of these items by clicking the delete icon. If the user deletes them in the order of first 2, and then 1 everything is fine.  However, if the user deletes 1 first, then the click handler of the now remaining only element is wrong.

<img width="527" alt="example" src="https://user-images.githubusercontent.com/1198324/107850269-c7ebbe80-6dc6-11eb-9748-7eac50a86346.png">

I've inspected the html, and the elements render correctly but the click listener is not applied.  When the click event fires I see that the action that occurs is from the element one, that was already deleted.  My understanding of what happened here:

 1. user clicks element 1
 2. the event fires, I send a DELETE call to the server to delete the record, response completes
 3. component.Update() calls Render() and now there is only one item is in the list -- what used to be element 2 -- renders correctly
 4. user clicks the only element in the list
 5. the event fires, I send a DELETE call for element 1, repeating the DELETE that was already sent, the call fails

I don't know if this is because my event handler functions are curried:
```golang
func (c *TeamComponent) deleteEventHandler(id string) app.EventHandler {
	return func(ctx app.Context, e app.Event) {
		....
	}
}
```

I believe the problem is the `!current.equal(new)` https://github.com/maxence-charriere/go-app/blob/v7/pkg/app/element.go#L337.  If I remove this optimization and always `setJsHandler` for existing handlers like this:
```golang
	for k, new := range handlers {
		if current, exists := e.events[k]; exists {
			e.delJsEventHandler(k, current)
		}

		e.events[k] = new
		e.setJsEventHandler(k, new)
	}
```

**Comment by maxence-charriere** [comment]
Can you copy paste the full example. It’s gonna be easier for me to test and fix :)

**Comment by jwmach1** [comment]
```diff
diff --git a/pkg/app/element.go b/pkg/app/element.go
index 80e7344..defdcbb 100644
--- a/pkg/app/element.go
+++ b/pkg/app/element.go
@@ -334,14 +334,11 @@ func (e *elem) updateEventHandler(handlers map[string]eventHandler) {
 	}
 
 	for k, new := range handlers {
-		if current, exists := e.events[k]; !current.equal(new) {
-			if exists {
-				e.delJsEventHandler(k, current)
-			}
-
-			e.events[k] = new
-			e.setJsEventHandler(k, new)
+		if current, exists := e.events[k]; exists {
+			e.delJsEventHandler(k, current)
 		}
+		e.events[k] = new
+		e.setJsEventHandler(k, new)
 	}
 }
 
```

**Comment by maxence-charriere** [comment]
What i meant is the component or a test component with similar behavior. It’s quite hard for me to grasp all the context without seing the Render().

**Comment by jwmach1** [comment]
oh, sure. I'll have to extract something smaller

**Comment by jwmach1** [comment]
```golang
package main

import (
	"fmt"

	"github.com/maxence-charriere/go-app/v7/pkg/app"
)

func main() {
	app.Route("/", CreateBaseComponent())
	app.Run()
}

type BaseComponent struct {
	app.Compo
	stuff []data
}
type data struct {
	ID    int
	Value string
}

func CreateBaseComponent() *BaseComponent {
	return &BaseComponent{
		stuff: []data{
			{11, "one"},
			{22, "two"},
			{33, "three"},
		},
	}
}
func (c *BaseComponent) Render() app.UI {
	fmt.Println("rendering ", c.stuff)
	return app.Div().Class("wasm-wrapper").Body(
		app.Div().Class("mdl-layout mdl-js-layout mdl-layout--fixed-header").Body(
			app.H1().Text("Base Component"),
			app.Div().Body(
				app.Range(c.stuff).Slice(func(i int) app.UI {
					return app.Div().ID(fmt.Sprintf("elem-%d", c.stuff[i].ID)).Body(
						app.Text(c.stuff[i]),
						app.Button().Text("remove").OnClick(c.listener(c.stuff[i].ID)),
					)
				}),
			),
		),
	)
}
func (c *BaseComponent) listener(id int) app.EventHandler {
	return func(_ app.Context, _ app.Event) {
		didRemove := false
		for i, d := range c.stuff {
			if d.ID == id {
				c.stuff = append(c.stuff[:i], c.stuff[i+1:]...)
				didRemove = true
				break
			}
		}
		if !didRemove {
			fmt.Println("error: no element exists with id ", id)
		}
		c.Update()
	}
}
```

**Comment by maxence-charriere** [comment]
Thanks for the example, i ll look into it.

**Comment by maxence-charriere** [comment]
is it a simplified version of the code and you are trying to do something similar or it is the code as it is ?

**Comment by maxence-charriere** [comment]
Ok so I reproduced it and in fact, it is not updated. Right now it uses a key generated from the event name and the func pointer to check equality. In that case, the pointer is always the same:

```
registering app service worker
(3) wasm_exec.js:50 create event handler: 0x36500000 
wasm_exec.js:50 trying to remove elem 33
(2) wasm_exec.js:50 create event handler: 0x36500000 
```

Seems to be a priority to fix to me. Thanks for reporting this.

**Comment by maxence-charriere** [comment]
Hey, just solve this by giving the possibility to add a scope when setting an event handler:

```go
type issue499Data struct {
	ID    int
	Value string
}

type issue499 struct {
	app.Compo

	data []issue499Data
}

func newIssue499Data() *issue499 {
	return &issue499{}
}

func (c *issue499) OnMount(app.Context) {
	c.data = []issue499Data{
		{11, "one"},
		{22, "two"},
		{33, "three"},
		{44, "four"},
		{55, "five"},
		{66, "six"},
		{77, "sever"},
		{88, "eight"},
		{99, "nine"},
	}
	c.Update()
}

func (c *issue499) Render() app.UI {
	return app.Div().Body(
		app.H1().Text("Issue 499"),
		app.Div().
			Body(
				app.Range(c.data).Slice(func(i int) app.UI {
					d := c.data[i]
					return app.Button().
						ID(fmt.Sprintf("elem-%v", d.ID)).
						OnClick(c.newListener(d.ID), d.ID). // HERE the element ID is added in order to trigger the handler update since the func pointer returned by newListener is always the same.
						Text(d.Value)
				}),
			),
	)
}

func (c *issue499) newListener(id int) app.EventHandler {
	return func(app.Context, app.Event) {
		for i, d := range c.data {
			if id == d.ID {
				c.data = append(c.data[:i], c.data[i+1:]...)
				c.Update()
				return
			}
		}
	}
}
```
