### ISSUE TITLE
how to get KeyboardEvent

### ISSUE THREAD

**Issue by simulot** [maxence-charriere/go-app#503]
Bonjour Maxence. 

Pardon my incompetence. I would like to intercept "enter"  key on an Input field. I have set OnKeyPress.

How to get the  keycode from the event? 
May be there something I have missed?

Thanks for your work.

**Comment by maxence-charriere** [comment]
Hello, can get it from the Event since it is a [JS value](https://go-app.dev/reference#Value).

```go
func (c *myCompo) OnKeyPress(ctx app.Context, e app.Event) {
    code := e.Get("key").Int()
}
```

Refer to [javacript keyboard event](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent) object for other properties.

**Comment by simulot** [comment]
Thanks, 

For the sake of precision, a way to get enter key is:
``` go
code := e.Get("key").String()
if code == "Enter" {
	c.saveItem(id)
}
```
