### ISSUE TITLE
Implementation with something like Wails?

### ISSUE THREAD

**Issue by imdaveho** [maxence-charriere/go-app#505]
Hi @maxence-charriere, very interesting project. I like the fact that you can define markup and components with Go (vs javascript framework fatigue), but I was wondering if there was a possibility of wrapping the wasm output to be served by something like [Wails](https://github.com/wailsapp/wails). I know you wrapped the built-in http to set up the webworkers and such, but is there a way to manually do it to be served by a webview? Perhaps this is unrealistic as these two projects differ too much....

**Comment by maxence-charriere** [comment]
Not sure but if i read well what they are saying: `Use standard Go for the backend
Use any frontend technology to build your UI
`, it should. Go-app satisfy the standard http.Handler interface and on the client side, any browser that run wasm. I think it would be same as making work with electron, have to make a local server serve static file and that would do the job. Look like wails is about this so I would say it is possible. I did not get a use case though and I m too busy right now with releasing V8 but if you arrive to somewhat make it work, let me know :)
