### ISSUE TITLE
Simple Form Example

### ISSUE THREAD

**Issue by Darwinium** [maxence-charriere/go-app#506]
Hello 👋

I love your solution and just started to learn how to build apps using wasm.

I haven't found any examples of the form with a few fields and a button in your documentation. Or the explanation of how to do that and how to work with user data. 

That's why may I ask you to provide a simple example of it?

Here are what I've tried, and this code prints as a result 0. So, it looks like I'm missing some binding or smth like this.

```golang
package main

import (
	"fmt"
	"strconv"

	"github.com/maxence-charriere/go-app/v7/pkg/app"
)

type application struct {
	app.Compo
	X string
	Z string
}

func (a *application) Render() app.UI {
	return app.Div().Body(
		app.Div().Body(
			app.Input().Value(a.X),
			app.Input().Value(a.Z),
			app.Button().Text("Calculate").OnClick(a.Calculate),
		),
	)
}

func (a *application) Calculate(ctx app.Context, e app.Event) {
	x, _ := strconv.Atoi(a.X)
	z, _ := strconv.Atoi(a.Z)
	result := x + z
	fmt.Println(x, z, result)
}
```

I'm sorry for, might be, stupid question, but I don't understand how to access the data that a user entered.

I really appreciate any help you can provide. 🙂

**Comment by maxence-charriere** [comment]
You can either set the `OnChange` event from input
```go
type application struct {
	app.Compo

	X int
	Z int
}

func (a *application) Render() app.UI {
	return app.Div().Body(
		app.Div().Body(
			app.Input().
				Value(a.X).
				OnChange(a.onXChange),
			app.Input().
				Value(a.Z).
				OnChange(a.onZChange),
			app.Button().
				Text("Calculate").
				OnClick(a.Calculate),
		),
	)
}

func (a *application) onXChange(ctx app.Context, e app.Event) {
	x := ctx.JSSrc.Get("value").String()
	a.X, _ = strconv.Atoi(x)
}

func (a *application) onZChange(ctx app.Context, e app.Event) {
	z := ctx.JSSrc.Get("value").String()
	a.Z, _ = strconv.Atoi(z)
}

func (a *application) Calculate(ctx app.Context, e app.Event) {
	x := a.X
	z := a.Z
	result := x + z
	fmt.Println(x, z, result)
}
```
 or put an id on those and get it with the JS API:
```go
type application struct {
	app.Compo

	X int
	Z int
}

func (a *application) Render() app.UI {
	return app.Div().Body(
		app.Div().Body(
			app.Input().
				ID("inX").
				Value(a.X),
			app.Input().
				ID("inZ").
				Value(a.Z),
			app.Button().Text("Calculate"),
		),
	)
}

func (a *application) Calculate(ctx app.Context, e app.Event) {
	inX := app.Window().GetElementByID("inX").String()
	inZ := app.Window().GetElementByID("inZ").String()

	x, _ := strconv.Atoi(inX)
	z, _ := strconv.Atoi(inZ)
	result := x + z
	fmt.Println(x, z, result)
}
``` 

This makes me realize that there should be something easier to deal with stuff like this. Maybe some binding mechanism. I may have an idea for this. I ll try to make it come in V8.

**Comment by Darwinium** [comment]
Thanks for the answer!

And I'd agree that it would be great to have something similar to a state in react. Because when you have a huge form with a lot of fields it'd be messy 🙂

**Comment by Darwinium** [comment]
I just tried your solution, and the result wasn't as expected. What am I doing wrong?

<img width="1298" alt="Screenshot 2021-03-03 at 22 17 01" src="https://user-images.githubusercontent.com/52569/109873950-c0556200-7c6e-11eb-83e8-4fe56c9c0275.png">

**Comment by maxence-charriere** [comment]
I made a mistake, the element is a dom node so you have to access its value. 

	inZ := app.Window().GetElementByID("inZ").Get("value").String()

**Comment by Darwinium** [comment]
Now it works. Thanks again

**Comment by maxence-charriere** [comment]
Had been working on something to make this easier on v8 by adding a `BindTo` method to `app.Compo` that works like `json.Unmarshal`. Let me know what you think, here is the hello example:
```go
type hello struct {
	app.Compo

	name string
}

func newHello() *hello {
	return &hello{}
}

func (h *hello) Render() app.UI {
	return app.Div().Body(
		app.H1().Body(
			app.Text("Hello, "),
			app.If(h.name != "",
				app.Text(h.name),
			).Else(
				app.Text("World!"),
			),
		),
		app.P().Body(
			app.Input().
				Type("text").
				Value(h.name).
				Placeholder("What is your name?").
				AutoFocus(true).
				OnChange(h.BindTo(&h.name)), // <--- we give the name field addr to BindTo
		),
	)
}
```

**Comment by Darwinium** [comment]
Does it mean that we'll be able to something like this?

```go

...
		app.P().Body(
			app.Input().
				Type("text").
				Value(h.name).
				Placeholder("What is your name?").
				AutoFocus(true).
				OnChange(), // <--- we give the name field addr to BindTo
		),
...

func (h *hello) OnChange(ctx app.Context, e app.Event) {
        h.BindTo(&h.name)
        h.name = h.name + " Somestring"
	a.Update()
}

```

And do you know ETA for v8?

**Comment by maxence-charriere** [comment]
No the BindTo returns an event handler, calling it in another event handler does nothing. With it you dont need the OnChange function. It generate an event handler that automatically map the input value to whatever field you want.

**Comment by maxence-charriere** [comment]
End of the month for v8, i need to update documentation but implementation is nearly done.

**Comment by Darwinium** [comment]
> No the BindTo returns an event handler, calling it in another event handler does nothing. With it you dont need the OnChange function. It generate an event handler that automatically map the input value to whatever field you want.

Hmmm... I have a case when I have a textarea and a button. When I click on the button I need to do something with the entered text (call API and send it there). So, I'd need to use OnChange to bind text to a struct. But at the same time, when a user enters text I need to count characters (that's why I need to use OnChange and call a func where I'll calculate length as well as generate an error if it more then needed).

How do I do this?

_Example of the textarea with characters counter:_
<img width="506" alt="Screenshot 2021-03-05 at 16 08 37" src="https://user-images.githubusercontent.com/52569/110133871-1809df80-7dcd-11eb-9f07-cfe69af5d606.png">

**Comment by maxence-charriere** [comment]
That case looks more complicated than just a binding, this should be donne with a normal event handler. Also i think the value in a text arrea is the innertext ir innerhtml. Have to use js api to get the value and use len builtin

**Comment by Darwinium** [comment]
This is what I do now.

```go
              ...
			app.Div().Class("form-floating").Body(
				app.Textarea().
					ID("Message").
					Text(a.Message).
					Class("form-control").
					OnInput(a.CountLength),
				app.Div().
					Class("form-text").
					Text(a.messageLength+"/500 characters"),
			),
			app.Button().
				Text("Send message").
				OnClick(a.SendMessage),
		),
              ...
              func (a *application) OnChangeMultiple(ctx app.Context, e app.Event) {
	              a.Multiple = app.Window().GetElementByID("Mulitple").Get("checked").Bool()
	              a.Update()
              }

              func (a *application) SendMessage(ctx app.Context, e app.Event) {
	              a.Message = app.Window().GetElementByID("Message").Get("value").String()
                      // Do something with a.Message or a
              }
```

Is that the right way to deal with it?

**Comment by Darwinium** [comment]
Sorry, changed my answer — miscopied the wrong func

**Comment by maxence-charriere** [comment]
In that case, you could use the new stuff but I'm not sure if it works with textarea since the `value` is the innerText. Gonna make some tests and see if I can take content for textarea or other tags with contenteditable set to true.
