### ISSUE TITLE
HTML tag Legend is mispeleld as Legends

### ISSUE THREAD

**Issue by simulot** [maxence-charriere/go-app#509]
Hi Maxence,
I think that app.Legend() should be named app.Legend(). 

The HTML <legend> element represents a caption for the content of its parent fieldset  [See MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend)

Thanks your work.

**Comment by maxence-charriere** [comment]
Thanks for reporting this. This will be corrected on v8 (coming soon).
