### ISSUE TITLE
v8 Question: How to generate an app.Context structure?

### ISSUE THREAD

**Issue by beanpole135** [maxence-charriere/go-app#516]
With the "Navigate()" and "Reload()" functions moved to the app.Context structure in v8, how can I generate a "basic" app.Context structure to use those functions?

Context:
One my my apps has a persistent websocket connection in the background to get notifications/triggers from the server. These websocket handlers are separate from the go-app system (but within the same binary), and need to be able to "reach in" to the go-app system to trigger a page change or reload the go-app completely (if something drastic changed on the server side).
With v7, I just had those triggers call `app.Reload()` or `app.Navigate(<url>)`, and I am trying to figure out the easiest way to convert those over within go-app v8.

**Comment by maxence-charriere** [comment]
do you create the websocket from a component?

**Comment by beanpole135** [comment]
No. The websocket structure is initiated from within main.go and has it's own event loop started by something like: `go Websocket.Start()`

**Comment by beanpole135** [comment]
I do have a global "SESSION" component (app.Compo struct) which lets me run things like "SESSION.Update()" as needed, if that helps.

**Comment by maxence-charriere** [comment]
```
I do have a global "SESSION" component (app.Compo struct) which lets me run things like "SESSION.Update()" as needed, if that helps.
```

You could get the context from your session's component `OnMount` method and save it somewhere.

**Comment by beanpole135** [comment]
That seems like an easy enough option - thanks!

**Comment by maxence-charriere** [comment]
Or just copy the pointer of the Navigate and Reload function from your session `OnMount` context.

**Comment by beanpole135** [comment]
OK, I got this working after a little hiccup: It appears that the "OnMount" function is getting called AFTER the Render() function. I just had to do a quick check/init of the globals in both places to ensure the WASM did not segfault on init in that Render() function.

Here is a quick example of what my end-code looks like in case anybody else runs into this:
```
var SESSION *Session //only ever one session struct for the entire app
var SCTX *app.Context //Context structure for the SESSION object

type Session struct {
	app.Compo
}

func (S *Session) OnMount(ctx app.Context){
	fmt.Println("Session Mounted")
	SESSION = S
	SCTX = &ctx
}
// ==== MAIN RENDER ROUTINE ====
func (S *Session) Render() app.UI {
	if SESSION == nil {
		fmt.Println("Render Before Mount")
		SESSION = S
	}
	return app.Div() //this is just a stub for the example
}
```

Now I can just call `SCTX.Reload()` or `SCTX.Navigate(<some-url>)` from non-app structures as needed.
