### ISSUE TITLE
Update sometime miss elements

### ISSUE THREAD

**Issue by simulot** [maxence-charriere/go-app#522]
I'm trying to build a page with elements received one at a time from a websocket connection.
The idea is to build dynamically a tree of objects as results arrive. At the end of incoming flow, the page should looks like:

-  Content
   - Elements
     - Element
        - Tags
      - Element
        - Tags
            ...

My code is not working. So I have made a self containing example to show the point: https://gist.github.com/simulot/dd1362b1a44e9f6c93c187c2b837ee74

Click Search to build the page with the full set of result works as expected (except  a small problem, see below). 

On freshly loaded page (important), click on one of "Progressive" buttons, the page is not updated with elements. However, it works at second run. It seams that Content.Elements must not be nil before running the query. This is confirmed by setting up Elements at Content.Mount.

The small problem is with Tags. Only one tag is set on screen despite Tags.Render function renders all tags as log shows. I can't figure it out.

go-app V8 and V9 behave same.

**Comment by maxence-charriere** [comment]
Look like you are adding a lot of complexity here. You just need 2 component for this: 
- a container
- a item

Here is the refactored code I tried to make it work:
```go
type content522 struct {
	app.Compo

	results []result522
}

func newContent522() *content522 {
	return &content522{}
}

func (c *content522) Render() app.UI {
	return app.Div().Body(
		app.H1().Text("My app"),
		app.P().Body(
			app.Button().
				OnClick(c.fullSearch).
				Text("Search"),
			app.Button().
				OnClick(c.progressiveSearch(time.Second)).
				Text("Progressive Search 1s"),
			app.Button().
				OnClick(c.progressiveSearch(time.Millisecond*500)).
				Text("Progressive Search 500ms"),
			app.Button().
				OnClick(c.progressiveSearch(time.Millisecond*5)).
				Text("Progressive Search 5ms"),
		),
		app.P().Body(
			app.Range(c.results).Slice(func(i int) app.UI {
				return newElement522(c.results[i])
			}),
		),
	)
}

func (c *content522) fullSearch(ctx app.Context, e app.Event) {
	generateResult522(ctx, 0, c.AddResult)
}

func (c *content522) progressiveSearch(d time.Duration) func(ctx app.Context, e app.Event) {
	return func(ctx app.Context, e app.Event) {
		c.results = nil
		generateResult522(ctx, d, c.AddResult)
	}
}

func (c *content522) AddResult(ctx app.Context, r result522) {
	c.results = append(c.results, r)
}

type element522 struct {
	app.Compo

	Result result522
}

func newElement522(r result522) *element522 {
	return &element522{Result: r}
}

func (e element522) Render() app.UI {
	return app.Div().Body(
		app.H2().Text(e.Result.Title),
		app.P().Body(
			app.Range(e.Result.Tags).Slice(func(i int) app.UI {
				return app.B().Text(e.Result.Tags[i] + " ")
			}),
		),
		app.P().Text(e.Result.Description),
	)
}

type result522 struct {
	ID          int
	Title       string
	Description string
	Tags        []string
}

func generateResult522(ctx app.Context, interval time.Duration, onResult func(app.Context, result522)) {
	// Simulate your websocket on another goroutine.
	ctx.Async(func() {
		for i := 0; i < 5; i++ {
			// This simulate the time interval result:
			time.Sleep(interval)

			r := result522{
				ID:          i + 1,
				Title:       fmt.Sprintf("Result %v", i+1),
				Description: "Ut ipsum excepteur esse commodo anim et irure culpa laborum elit irure. Ullamco nisi nulla nostrud commodo eiusmod qui labore laboris.",
				Tags:        generateResult522Tags(),
			}

			// Calling the component modification on the UI goroutine and
			// ensuring update:
			ctx.Dispatch(func(ctx app.Context) {
				onResult(ctx, r)
			})
		}
	})
}

func generateResult522Tags() []string {
	availableTags := []string{"red", "blue", "brown", "white", "yellow"}
	count := rand.Intn(3)
	tags := make([]string, count)

	for i := range tags {
		tags[i] = availableTags[rand.Intn(len(availableTags))]
	}

	return tags
}
```

Here is how it look like:

https://user-images.githubusercontent.com/2692731/116055515-5e820900-a6af-11eb-9fd4-c7a4ec5a7e66.mov

Note that I built this example with v9 since you originally posted on the #519 

Hope it help. Feel free to ask some explanation if you don't understand something.

**Comment by simulot** [comment]
Thanks, this helps.  

In your code, parent element don't have a pointer to it children. The children are created at rendering time. 
I was thinking allocating components during render time was bad. 

Maybe you can add some words on this on component nesting documentation.
Thanks for this awesome library.
++

**Comment by maxence-charriere** [comment]
The rendering just create a node tree that is compared to the current one. The real dom and html elements are only modified when a diff is found.

**Comment by simulot** [comment]
May be rendering is not called as often I'm thinking, and allocation isn't a big issue after all.
