### ISSUE TITLE
removing page element makes problem when element is a component 

### ISSUE THREAD

**Issue by simulot** [maxence-charriere/go-app#524]
I'm working on notification system for my application. The initial design was a notification list that create and remove notifications after a timeout or by clicking on close button. This works as expected until I close the first notification. 1st remains visible, while the 1st notification in data structure has been removed. 

So I have strip down the code to work on this. When the notifications are managed by one component, deletion of the 1st item is correctly rendered. When notifications are managed by a list component managing  notification components, this isn't correctly rendered, like DOM structure was out of synchronization with objects tree.

I have tested both implementations side by side. The code is here https://github.com/simulot/test-go-app 

Initial state:
![image](https://user-images.githubusercontent.com/5980377/116784145-f2c6e400-aa92-11eb-97ab-c7d9218a7342.png)

Now, lets close 1st element of each list
![image](https://user-images.githubusercontent.com/5980377/116784182-2d308100-aa93-11eb-9a05-bb79428d75b9.png)

I have written tests using app.TestMatch that confirms:
- The underlying message list shared by both implementation is working as expected.
- After closing the 1st element if the list, the screen elements are not correct when using component nesting.

Flatten components is always possible at the price of not enabling code reusing.  
I think this worth be checked. 
++

**Comment by maxence-charriere** [comment]
Did you try by giving a scope to the event handler? Take a look on the list example: https://go-app.dev/examples/list

**Comment by simulot** [comment]
Yes, the notification ID is given as context. And log trace shows that the right handler is called. 
Anyway, this is reproduced in testings, where OnClick isn't used.

**Comment by maxence-charriere** [comment]
In your notification component, the field are no exported so when the component is updated, the handler and message are the one set when the list was initialized.

I exported them and make it work as expected.

see https://go-app.dev/components#fields

**Comment by simulot** [comment]
Of course! 
I had to make all  fields exportable for the leaf component, including the call back function. Now, my test is working.

Thanks
Sorry for the noise.
