### ISSUE TITLE
Tinygo needs non reflection based JSON encoder

### ISSUE THREAD

**Issue by gedw99** [maxence-charriere/go-app#525]
There’s is an excellent chance that this framework will compile with tinygo  if the JSON encoder is replaced with the one recommended by them.

Genji now works with tinygo which provides a backend and front end dB all in golang.

has anyone else tried to compile this framework with tinygo yet ?

**Comment by gedw99** [comment]
Genji

https://github.com/genjidb/genji.js

https://github.com/genjidb/genji.js/blob/master/scripts/buildgo.sh

**Comment by gedw99** [comment]
JSON Alternative 

https://github.com/buger/jsonparser

**Comment by gedw99** [comment]
Another JSON Alternative but uses code gen 

https://github.com/moznion/go-json-ice

**Comment by gedw99** [comment]
Here is what genji uses 👍 


https://github.com/genjidb/genji/blob/adf452135d082b959f9235902eb44b17e255eb7e/go.mod#L6

**Comment by maxence-charriere** [comment]
I'm not sure I understand what worker you are talking about. Wasm code does not run in a service worker.

**Comment by maxence-charriere** [comment]
> There’s is an excellent chance that this framework will compile with tinygo if the JSON encoder is replaced with the one reco

I don't want to impose any encoder or 3rd party library with this package.

Tinygo looks promising but right now it is not supported and it is not in my priorities to do so. There are too many go features that are not supported (https://tinygo.org/docs/reference/lang-support https://tinygo.org/docs/reference/lang-support/stdlib/#nethttp) for me to spend the time on this for now.

Going to close it for now. Never say never.

**Comment by gedw99** [comment]
True it has its compromises.

my hunch is that with time tinygo will “ just work” with resorting to workarounds. The tinygo team are officially a golang team so there is a good chance it will with time.

**Comment by maxence-charriere** [comment]
I ll implement it as soon as It is become enough mature.
