### ISSUE TITLE
How can I open a file and read its content

### ISSUE THREAD

**Issue by ShaypValentine** [maxence-charriere/go-app#527]
This might sounds pretty dumb as a question but since I'm quite new to Go and webdev, the answer might be obvious but since I'm stucked here I go.

I'm following the get started code and I wanted to replace the Input field  and the OnChange event that goes with it by a button that when clicked would read the content of a file and replace  the Hello World text.

I did something like that 

main.go
```package main

import (
	"log"
	"net/http"

	"github.com/maxence-charriere/go-app/v8/pkg/app"
)

func main() {

	app.Route("/", &hello{})
	app.RunWhenOnBrowser()

	http.Handle("/", &app.Handler{
		Name:        "Hello",
		Description: "An Hello World! example",
	})

	if err := http.ListenAndServe(":8000", nil); err != nil {
		log.Fatal(err)
	}
}
```
hello.go
```
package main

import (
	"fmt"
	"io/ioutil"

	"github.com/maxence-charriere/go-app/v8/pkg/app"
)

type hello struct {
	app.Compo

	name string
}

func (h *hello) OnNav(ctx app.Context) {
	fmt.Println("component navigated:")
}
func (h *hello) Render() app.UI {
	return app.Div().Body(
		app.H1().Body(
			app.Text("Hello, "),
			app.If(h.name != "",
				app.Text(h.name),
			).Else(
				app.Text("World!"),
			),
		),
		app.P().Body(
			app.Button().
				Text("ClickMe").
				AutoFocus(true).
				OnClick(h.onClickBeep),
		),
		app.Img().Src("/web/Capture.png"),
	)
}

func (h *hello) onClickBeep(ctx app.Context, e app.Event) {
	name, err := ioutil.ReadFile("test.txt")
	if err != nil {
		fmt.Println("File reading error", err)
		return
	}
	// name := "ded"
	h.name = string(name)
	h.Update()
}
```
But I get the following error :

>  File reading error open test.txt: not implemented on js

As I understand it since we set the GOOS env var to js  the ioutil and os package can't do what I want since they are not made to work on it.

How should I handle the processing of the file ?

**Comment by maxence-charriere** [comment]
Your code is being ran in a web browser where there is no access to the filesystem. So ioutil package will fail with this scenario. You have to serve the file from http to make it work.

**Comment by ShaypValentine** [comment]
Thanks you for answering even though it was hardly related this repo
