### ISSUE TITLE
Implementing Save button 

### ISSUE THREAD

**Issue by simulot** [maxence-charriere/go-app#528]
Hi

I'm trying to add a save button on the application to let the user saving his work into a local file, not on the server
Have you some idea for implementing such button?

Thanks in advance

**Comment by maxence-charriere** [comment]
You should use Context.LocalStorage. Be careful though because the space is limited.

**Comment by simulot** [comment]
File need to be available locally, for integration in another application. So 

I'm exploring a way to distribute a small tool for checking and converting files. I have done a CLI tool that do the job, but:
1- Antivirus doesn't respect my work. The EXE is discarded when downloaded by the user
2- Opening powsershell is not easy for most of accountants... 🤔  

So I have explored the weird idea to provide the converter as web application, running in the browser... Zero deployment, no network configuration, no server... But it's not as easy than expected.

**Comment by simulot** [comment]
I'm giving up.
Thanks for your attention

**Comment by maxence-charriere** [comment]
You would have to host the logic on a server and provide an url to download the processed file. For the upload you would have to use an html form and probably interropt with js.

make me think i could do a helper for this. But still, the rest is ordinary server job. the download is a url with a simple http request.

**Comment by simulot** [comment]
The idea was to not using any server and produce document in the browser. I was expecting a quick win. 

I have read following article https://web.dev/file-system-access/ 
There is a demo here https://googlechromelabs.github.io/text-editor/
This works with chrome specific API and use some fallback with other browsers.

Difficulties for me was :
- Calling APIs, dealing with Promises and File and Blog, and interpreting panics, too much javascript
- The SaveAs fallback uses an in A and  reference to a blob that interferes with app Navigation
