### ISSUE TITLE
Exported Input Fields Not Updated in UI

### ISSUE THREAD

**Issue by nekrondev** [maxence-charriere/go-app#532]
Hello Maxence,

working with go-app recently for an internal tool I found an input field bug clearing the form but not updating  the UI, i.e. the input field's text is still visible on the web page even if internally cleared and component updated.

To show you my issue I created a small showcase for you. You can find it here: https://github.com/nekrondev/ui_input_clear_bug 

Cheers and keep up the great work!
Nek

**Comment by nekrondev** [comment]
Ok I think I solved my problem (RTFM). go-app is not updating DOM node attributes automatically but someone needs to do this by hand. Text, which is not a DOM attribute, can be updated by changing the bound struct variable and go-app renders the modifed value on update.

I modified my "bug" showcase  so it is no longer a bug.

**Comment by maxence-charriere** [comment]
Look like this a js behavior related to the `setAttribute` function. => https://stackoverflow.com/questions/31482807/modifying-value-attribute-of-text-input-not-working-using-javascript

I'll take a look at using the `value` field rather than the `setAttribute` for this.

**Comment by maxence-charriere** [comment]
I fixed it on the V9 branch =>
```
go get -u -v github.com/maxence-charriere/go-app/v9@919dd2c
```

The code can be simplified like this:
```go
// Root stores the current displayed page and is the main navbar navigation
type Root struct {
	app.Compo

	FormData string // input form property value
}

// Render will render the main navigation page
func (p *Root) Render() app.UI {
	app.Log("Render(): Root page rendered.")
	return app.Body().Body(
		app.Div().Body(
			app.Div().
				Text("Example shows a go-app workaround clearing an input field 'value' property."),
			app.Div().
				Text("Text entered into input field is stored inside components exported 'FormData' variable using input fields OnChanged() event and reading DOM node 'value' property."),
			app.Div().
				Text("However if another event like OnClick() from a button is clearing the exported 'FormData' variable bound to input field DOM node 'value' property and updating the component the 'value' property inside the input field DOM node is not cleared."),
			app.Div().
				Body(
					app.Br(),
					app.Text("Plain text (rendered by go-app): "+p.FormData),
					app.Br(),
					app.Label().
						Text("Input field with DOM node 'value' property"),
					app.Div().
						Body(
							app.Input().
								ID("formdata").
								Value(p.FormData).
								OnChange(p.ValueTo(&p.FormData)), // <= can map it to a field with this
						),
					app.Div().
						Body(
							app.Button().
								Text("Clear Form").
								OnClick(p.onButtonClicked),
						),
				),
		),
	)
}

// onButtonClicked evemt will be triggered if button has been clicked
func (p *Root) onButtonClicked(ctx app.Context, e app.Event) {
	p.FormData = ""
}
```

**Comment by nekrondev** [comment]
Many thanks for the fast bugfix and your pointers to simply structure value update. 
I have updated my demo repository with your bugfix so the issue can be closed.
