### ISSUE TITLE
Generated wasm too large

### ISSUE THREAD

**Issue by iarkaroy** [maxence-charriere/go-app#534]
Thank you for your contribution. This looks pretty awesome to work with. I just started playing around with it.

I started with minimal example:
```
package main

import (
	"log"
	"net/http"

	"github.com/maxence-charriere/go-app/v8/pkg/app"
)

type home struct {
	app.Compo
}

func (h *home) Render() app.UI {
	return app.H1().Text("Hello World!")
}

func main() {
	app.Route("/", &home{})
	app.RunWhenOnBrowser()
	http.Handle("/", &app.Handler{
		Name:        "Hello",
		Description: "An Hello World! example",
	})

	if err := http.ListenAndServe(":8000", nil); err != nil {
		log.Fatal(err)
	}
}
```

Generated wasm with:
```
GOARCH=wasm GOOS=js go build -o web/app.wasm
```

But the generated wasm is a whooping 11.5 MB. Any suggestion to reduce the file size?

Go version: `1.16.4`

**Comment by maxence-charriere** [comment]
You can serve it gzipped.

**Comment by iarkaroy** [comment]
Yes. Still it will be around 3 MB. I will experiment with `tinygo` to see if that helps.

**Comment by maxence-charriere** [comment]
If you dont use http you can separate client code in another package. It the http package that add a lot.

**Comment by iarkaroy** [comment]
Thanks for the suggestion. I have been trying to build with tinygo but it seems to have some issues. I have added the issue https://github.com/tinygo-org/tinygo/issues/1886.

**Comment by maxence-charriere** [comment]
Tinygo is not supported by this package for now.

**Comment by thepudds** [comment]
FWIW, there has been some progress on the tinygo side of this, e.g.:

https://github.com/tinygo-org/tinygo/issues/1886#issuecomment-846629254

**Comment by ignishub** [comment]
Just make two files that contains "serve" function. In GOOS=js target this function will be empty. 

Without it : 12 Mb
With it(without http package): 5 Mb

Then use brotli to reduce it again:

Result: 985 Kb

**Comment by oderwat** [comment]
I am experimenting with go-app right now. To get the sizes down I made two targets for the HTTP server and one is a stub. In addition, I experimenting in using the chi router and with that, I have a compression middleware for the wasm. This brings the size to 1.3 MB (from >16 MB) and lets me add the backend code using chi. I also experiment with "live reloading" (through a javascript HEAD checking and using reflex for recompilation). This is a bit rough about the edges but I am actually pretty happy with how everything works so far. You may want to look at https://github.com/oderwat/go-guess-the-number-app (this is not meant to be public for real, but I thought I want to share this as example and maybe get comments)

**Comment by mar1n3r0** [comment]
@oderwat You are right. We might end up needing to separate the http package and still use Tinygo to achieve js world bundle sizes. Thanks for the example. The wasm ends up being 13.3 MB when I build it though.

**Comment by oderwat** [comment]
13.3 MB compressed? My testing (a lot of stuff) app has currently 13.8 MB which ends up as 3.2 MB with on-the-fly compression middleware. I also use my #631 PR to show people a loading indicator, which makes its loading time "more accepted" as it shows the progress to the user.

But I hope that we get TinyGo to work. Sadly I just came from my vacation and my day job has different priorities at the moment.

**Comment by mar1n3r0** [comment]
Hey not a problem. I don't see any difference in the wasm size after splitting into two files actually. That's why I asked.

**Comment by oderwat** [comment]
Well, I use HTTP clients in the frontend anyways. But there are other packages that could be used (maybe https://github.com/golangee/wasm-net). But I did not have time to try it yet.

**Comment by mar1n3r0** [comment]
> Well, I use HTTP clients in the frontend anyways. But there are other packages that could be used (maybe https://github.com/golangee/wasm-net). But I did not have time to try it yet.

One more as well: https://github.com/hajimehoshi/wasmserve

**Comment by oderwat** [comment]
That is as a wasm server, not an HTTP client library to use in the frontend? The Server is fine in go-app as it is just the server binary where size matters less.

**Comment by oderwat** [comment]
Sure. But when you access APIs from the frontend you need to use one or more HTTP clients in the code.

**Comment by mar1n3r0** [comment]
Yes, my misconception.

**Comment by oderwat** [comment]
Never mind: https://github.com/golangee/wasm-net is not what I meant. This also includes `net/http`. I found something else but can not dig up the link right now. Basically, it works by calling the functions in the browser as js does it.

**Comment by mar1n3r0** [comment]
A gRPC client? We already have an example of using that in go-app: https://github.com/maxence-charriere/go-app/issues/447

**Comment by oderwat** [comment]
It is about "net/http" in the frontend part and you can not just use a gRPC client to access an HTTP API. I am not talking only about the client/server communication of the app itself.

> Even if we use that we still serve requests from net/http and need a lightweight alternative to it.

No, we don't? It does not change the WASM size at all that you use net/http for the server-side.

**Comment by oderwat** [comment]
And btw. gRPC uses HTTP/2. I would rather use something like https://github.com/twitchtv/twirp

**Comment by mar1n3r0** [comment]
> And btw. gRPC uses HTTP/2. I would rather use something like https://github.com/twitchtv/twirp

Yeah I am not speculating about that, anything as an alternative to a smaller final size.

**Comment by mar1n3r0** [comment]
> Without it : 12 Mb
> With it(without http package): 5 Mb

It was stated previously that the net/http package adds 7 MB.

**Comment by mar1n3r0** [comment]
> You can not use gRPC for an HTTP API. We need to access a lot of different APIs and not all of them are made by us. The key to a smaller size will be TinyGo until the Go compiler gets optimized for WASM.

Please read the pull request discussion. Tinygo successfully compiled but the final size was 6.5 MB. So Tinygo doesn't solve the problem with size.

**Comment by oderwat** [comment]
> It was stated previously that the net/http package adds 7 MB.

And I say you can probably use the browsers XMLHttpRequest() for this and don't need `net/http` in the frontend. But I don't have time to try it.

**Comment by mar1n3r0** [comment]
> > It was stated previously that the net/http package adds 7 MB.
> 
> And I say you can probably use the browsers XMLHttpRequest() for this and don't need `net/http` in the frontend. But I don't have time to try it.

How are we going to serve the wasm file to the browser without http.ListenAndServe?

**Comment by mar1n3r0** [comment]
> If you dont use http you can separate client code in another package. It the http package that add a lot.

I hope @maxence-charriere can clarify the basics here since.

**Comment by oderwat** [comment]
@mar1n3r0 you simply build two times. One for the WASM not containing the server and one for the server itself (which simply uses net/http).

**Comment by mar1n3r0** [comment]
> @mar1n3r0 you simply build two times. One for the WASM not containing the server and one for the server itself (which simply uses net/http).

They are the same package how do you split them? In your example the final size remains unchanged from before the split.

**Comment by oderwat** [comment]
main.go

```go
func main() {
	// Frontend routing
	app.RouteWithRegexp("/.*", &appControl{})

	// this concludes the part which goes into the front-end
	app.RunWhenOnBrowser()

	// this will depend on the target (wasm or not wasm) and
	// it starts the servers if it is not the wasm target.
	AppServer()
}
```

wasmstub.go

```go
// Our empty version of the httpServer for usage with the wasm target
// this way we will not include any of the related code
//go:build wasm

package main

func AppServer() {
}
```

server.go
```go
// Our empty version of the httpServer for usage with the wasm target
// this way we will not include any of the related code
//go:build !wasm

package main

import (
....
)

func AppServer() {
	// the actuall server code
......
```

**Comment by oderwat** [comment]
I reverted my sample since I posted this here as it contained to much "tech" which I did for the company.

**Comment by mar1n3r0** [comment]
> main.go
> 
> ```go
> func main() {
> 	// Frontend routing
> 	app.RouteWithRegexp("/.*", &appControl{})
> 
> 	// this concludes the part which goes into the front-end
> 	app.RunWhenOnBrowser()
> 
> 	// this will depend on the target (wasm or not wasm) and
> 	// it starts the servers if it is not the wasm target.
> 	AppServer()
> }
> ```
> 
> wasmstub.go
> 
> ```go
> // Our empty version of the httpServer for usage with the wasm target
> // this way we will not include any of the related code
> //go:build wasm
> 
> package main
> 
> func AppServer() {
> }
> ```
> 
> server.go
> 
> ```go
> // Our empty version of the httpServer for usage with the wasm target
> // this way we will not include any of the related code
> //go:build !wasm
> 
> package main
> 
> import (
> ....
> )
> 
> func AppServer() {
> 	// the actuall server code
> ......
> ```

Will give it a try.

**Comment by mar1n3r0** [comment]
Thanks, that worked like a charm. Here are the results and the example code based on the hello example:
https://github.com/mar1n3r0/hello-wasm

1. Original size - 12 MB
After multi-stage and omitting net/http in wasm
1. Go compiler - 5 MB
2. TinyGo compiler - 1.8 MB
3. TinyGo + gzipped - 574KB

An error occurred of course after removing the env variables but it shows what would be possible once SetEnv is included in the next TinyGo release. 
![Screenshot from 2022-01-10 15-51-20](https://user-images.githubusercontent.com/11375673/148777175-f792cee9-7def-446e-90ff-3ab15e04a49d.png)

**Comment by oderwat** [comment]
I don't think that "setenv" has anything to do with the error (besides that I already wondered what "setenv" in WASM may even mean). If you compile with TinyGo you also need to use the TinyGo WASM framework variant. You can not just use this WASM with the WASM of the standard Go compiler.

**Comment by mar1n3r0** [comment]
Yeah you are right: https://tinygo.org/docs/guides/webassembly/ It needs the wasm_exec.js version from TinyGo.

**Comment by oderwat** [comment]
I already have a wasm module loader in my go-app tests which can load additional wasm modules generated by the original or the TinyGo compiler. This is why I know that :)

**Comment by mar1n3r0** [comment]
That's fixed now here: https://github.com/maxence-charriere/go-app/blob/master/pkg/app/gen/scripts.go#L31
No further errors from wasm. It's now the envs that are remaining.

![Screenshot from 2022-01-10 16-39-43](https://user-images.githubusercontent.com/11375673/148784244-240bf1a5-fc2a-4fdf-97f9-5bf3c326be5d.png)

**Comment by oderwat** [comment]
If that uses my "template" replacement it may need `{{.Env }}` changed to `{{.Env}}` because I just replace later one.

**Comment by oderwat** [comment]
Yes. I just checked. You need to change the second `{{.Env }}` too.

**Comment by oderwat** [comment]
> SetEnv has nothing to do with WASM but it has to be implemented in TinyGo in order to be used.

But I only want to use TinyGo for the WASM part and that hardly ever needs to use "SetEnv" as (afaik) there is nothing like "env variables" in WASM. I didn't hat time what this "SetEnv" actually is used for.

The error you get is also template-related.

**Comment by mar1n3r0** [comment]
This is the original go-app code. Haven't touched anything there.

**Comment by oderwat** [comment]
How can you compile using TinyGo without a replacement for `text/template`? ... if you removed that part it will surely not work :)

**Comment by mar1n3r0** [comment]
I used your hard-coding from the PR and also commented this:

`func (h *Handler) makeAppJS() []byte {
	if h.Env == nil {
		h.Env = make(map[string]string)
	}
	// internalURLs, _ := json.Marshal(h.InternalURLs)
	// h.Env["GOAPP_INTERNAL_URLS"] = string(internalURLs)
	// h.Env["GOAPP_VERSION"] = h.Version
	// h.Env["GOAPP_STATIC_RESOURCES_URL"] = h.Resources.Static()
	// h.Env["GOAPP_ROOT_PREFIX"] = h.Resources.Package()

	// for k, v := range h.Env {
	// 	if err := os.Setenv(k, v); err != nil {
	// 		Log(errors.New("setting app env variable failed").
	// 			Tag("name", k).
	// 			Tag("value", v).
	// 			Wrap(err))
	// 	}
	// }

	env, err := json.Marshal(h.Env)
	if err != nil {
		panic(errors.New("encoding pwa env failed").
			Tag("env", h.Env).
			Wrap(err),
		)
	}

	s := appJS
	s = strings.ReplaceAll(s, "{{.Env}}", btos(env))
	s = strings.ReplaceAll(s, "{{.Wasm}}", h.Resources.AppWASM())
	s = strings.ReplaceAll(s, "{{.WorkerJS}}", h.resolvePackagePath("/app-worker.js"))
	return []byte(s)
}`

So yeah it's normal that it's not working since the env variables are set here by SetEnv.

**Comment by oderwat** [comment]
No there is a `{{.Env }}` in the output, you show and that is the "syntax error" and related to the templates not correctly translated. 
![image](https://user-images.githubusercontent.com/719156/148789283-3a71e53f-bd85-4d3e-93a4-6b423aa5f874.png)

`s = strings.ReplaceAll(s, "{{.Env}}", btos(env))`

Looks to me as if generate did not run or that somewhere a `{{.Env }}` is hiding or reintrocuded.

**Comment by oderwat** [comment]
And please don't comment out:

```
// internalURLs, _ := json.Marshal(h.InternalURLs)
// h.Env["GOAPP_INTERNAL_URLS"] = string(internalURLs)
// h.Env["GOAPP_VERSION"] = h.Version
// h.Env["GOAPP_STATIC_RESOURCES_URL"] = h.Resources.Static()
// h.Env["GOAPP_ROOT_PREFIX"] = h.Resources.Package()
```

It is just os.SetEnv() which does not work (and looks useless to me. I don't understand what this is good for when the target is WASM. But maybe it is compiled twice. I don't know (yet)

**Comment by mar1n3r0** [comment]
```
// Getenv retrieves the value of the environment variable named by the key. It
// returns the value, which will be empty if the variable is not present.
func Getenv(k string) string {
	if IsServer {
		return os.Getenv(k)
	}

	env := Window().Call("goappGetenv", k)
	if !env.Truthy() {
		return ""
	}
	return env.String()
}
```

**Comment by oderwat** [comment]
{{.Env}} is not replaced by an Env variable but with the value of the map which is defined about.

**Comment by oderwat** [comment]
BTW: My main testing app still does not compile with TinyGo (after getting rid of the os.SetEnv()) because of `/libexec/src/encoding/xml/typeinfo.go:114:29: f.Index undefined (type *reflect.StructField has no field or method Index)` so yeah, more to do. But I "index" the problem with the `{{.Env }}` in my latest PR #680 I believe. Maybe I am going to use a much smaller example later. But using TinyGo can not mean that we can't use a majority of modules.

**Comment by mar1n3r0** [comment]
{{.Env }} is unchanged in my test so not taken from your template. I have no idea where the xml error comes from maybe send a full trace of the running code or a repo with it.

**Comment by mlctrez** [comment]
>  I found something else but can not dig up the link right now.

Here's a lighter weight http client for wasm :  https://github.com/marwan-at-work/wasm-fetch

**Comment by oderwat** [comment]
@mlctrez yep this is exactly the one I had in mind

**Comment by maxence-charriere** [comment]
A common pattern is to have a server configurable from environment variables.

Things like api endpoint can be configured and be automatically relayed to a client.

**Comment by maxence-charriere** [comment]
I also made a try for tinygo support. Here is the code: https://github.com/maxence-charriere/go-app/pull/682

I was able to compile but look like there is still some issues to figure out.

note that this is pure hacking and is far from being stable.

**Comment by mar1n3r0** [comment]
@maxence-charriere Please keep the Tinygo issue open as it is quite close to being completed.

**Comment by maxence-charriere** [comment]
@mar1n3r0 i don’t give up. I got that a lot of you folks want this to happen.

**Comment by oderwat** [comment]
If the compile times are longer but the result is (much) smaller it may just be good enough to use it for deployment. I also experienced quite long compile times while working on WASM "plugins" with TinyGo (and I am not sure if I wanna trust it to create stable code).

**Comment by mar1n3r0** [comment]
@oderwat same here but I don't consider 1 min compile time to be a show stopper if the benefit is 50% + reduced binary size. To be honest I also expected 10 times reduction so a bit disappointed.

**Comment by suntong** [comment]
Some important links / milestones, to save time the next person trying to read through the whole thread --

> To get the sizes down I made two targets for the HTTP server and one is a stub. In addition, I experimenting in using the chi router and with that, I have a compression middleware for the wasm. This brings the size to 1.3 MB (from >16 MB) and lets me add the backend code using chi. I also experiment with "live reloading" (through a javascript HEAD checking and using reflex for recompilation). This is a bit rough about the edges but I am actually pretty happy with how everything works so far. You may want to look at https://github.com/oderwat/go-guess-the-number-app (this is not meant to be public for real, but I thought I want to share this as example and maybe get comments)

> Here are the results and the example code based on the hello example: https://github.com/mar1n3r0/hello-wasm
> 
> 1. Original size - 12 MB
>    After multi-stage and omitting net/http in wasm
> 2. Go compiler - 5 MB
> 3. TinyGo compiler - 1.8 MB
> 4. TinyGo + gzipped - 574KB

- tinygo: https://tinygo.org/docs/guides/webassembly/ 
- lighter weight http client for wasm : https://github.com/marwan-at-work/wasm-fetch, to replace net/http which would otherwise add ~4 MBs to your wasm binary.

> I also made a try for tinygo support. Here is the code: #682
> 
> I was able to compile but look like there is still some issues to figure out.
> 
> note that this is pure hacking and is far from being stable.

**Comment by g4bwy** [comment]
Hi @mar1n3r0,

I'm reviving this thread a little bit, since you mention tinygo is working, but I'm still having a link-time issue with ```time.modTimer```:

```
tinygo:wasm-ld: error: /tmp/tinygo3209131542/main.o: undefined symbol: time.modTimer
failed to run tool: wasm-ld
error: failed to link /tmp/tinygo3209131542/main: exit status 1
```

how exactly did you manage to get past this one ?

cheers,

**Comment by mar1n3r0** [comment]
> Hi @mar1n3r0,
> 
> I'm reviving this thread a little bit, since you mention tinygo is working, but I'm still having a link-time issue with `time.modTimer` using tinygo 0.28.1:
> 
> ```
> tinygo:wasm-ld: error: /tmp/tinygo3209131542/main.o: undefined symbol: time.modTimer
> failed to run tool: wasm-ld
> error: failed to link /tmp/tinygo3209131542/main: exit status 1
> ```
> 
> how exactly did you manage to get past this one ?
> 
> cheers,

Sadly not yet there, see: https://github.com/maxence-charriere/go-app/pull/682

**Comment by g4bwy** [comment]
well that's too bad :cry:

in the meantime, did you try brotli or zstd compression instead of gzip ?

**Comment by mar1n3r0** [comment]
Nope, gzip only so far.

**Comment by maxence-charriere** [comment]
That cannot really be handled on go-app side.
A good practice is to separate the client code (wasm) and the server (part that use app.Handler).
