### ISSUE TITLE
UI Update / Render bugs (follow up #532)

### ISSUE THREAD

**Issue by nekrondev** [maxence-charriere/go-app#535]
Hi Maxence,

this is a follow-up from #532 as I have found three additional issues with UI rendering / updating of elements while doing some more UI stuff using your framework.

Please see my showcase at https://github.com/nekrondev/ui_input_clear_bug for an update.

Cheers and keep your good work!
Nek

**Comment by nekrondev** [comment]
The  interesting part is however if I push the reset form button the DOM is updated but UI still shows text or the wrong item in select box.

![2021-05-17 21_09_29-Mozilla Firefox](https://user-images.githubusercontent.com/13854802/118543300-6126ca00-b754-11eb-9367-461cb7f946a2.png)

**Comment by nekrondev** [comment]
Workaround is like previous bug to clear the values by JS DOM call (I added IDs to selector, textarea and checkbox):
```go
app.Window().GetElementByID("select").Set("value", p.Selector)
app.Window().GetElementByID("check").Set("checked", p.BoxEnabled)
app.Window().GetElementByID("textarea").Set("value", p.TextArea)
```
It's a bit confusing to have to different worlds (DOM and JS DOM) whereas DOM shows the correctly rendered content but JS DOM is still lagging behind and needs a JS call to get updated.

**Comment by maxence-charriere** [comment]
I'll take a look at this. Thanks for reporting it.

**Comment by maxence-charriere** [comment]
Hey @nekrondev, I had made some changes that fix all the stuff in your example repo.

```
go get -u -v github.com/maxence-charriere/go-app/v9@dfb5822
```

Thank you very much for reporting all of this. Please let me know if you find some other things.

**Comment by nekrondev** [comment]
Hi Maxence, 

Thanks for fixing this ASAP! I'll keep you posted if I find other issues while continuing development of my frontend stuff.

Cheers,
Nek

**Comment by maxence-charriere** [comment]
Just to let you know, the tag I gave had a bug.

This is fixed in

```
go get -u -v github.com/maxence-charriere/go-app/v9@9b096a0
```
