### ISSUE TITLE
How to pass a initial value to a Component field?

### ISSUE THREAD

**Issue by skhwhu** [maxence-charriere/go-app#538]
Hi, Maxence, I want to pass a initial value to a component field, but it doen't work. My code like this:

```go
type hello struct {
	app.Compo
	name string
}

func (h *hello) Render() app.UI {
	return app.H1().Text(h.name)
}

func main() {
	app.Route("/", &hello{name: "**GO-APP-TEST**"})
	app.RunWhenOnBrowser()
}
```

I want it display GO-APP-TEST, but nothing displayed!  thank you very much!

**Comment by maxence-charriere** [comment]
Hello,

> https://go-app.dev/reference#Route

Route is just associating a component type with a given path. When you go to a new page, a new instance is created. it does not matter if you set your field here or not. This is not the instance used when the page is loaded.

If you need to initialize this variable, do it by implementing the [Mounter](https://go-app.dev/components#mount) interface.


```go
type hello struct {
    app.Compo

    name string
}

func (h *hello) OnMount(ctx app.Context) app.UI {
    h.name = "GO-APP-TEST"
    h.Update()
}

func (h *hello) Render() app.UI {
    return app.H1().Text(h.name)
}
```

**Comment by skhwhu** [comment]
Hi, maxence, Thank you very much for you prompt reply. But I want use two instacnes of the hello component with diffentent intial field values,  for example one instance to dispaly "GO-APP-TEST", another instance to display "GO-APP IS AWESOME" how can I solve it?

**Comment by maxence-charriere** [comment]
You can:
- Duplicate your component
- Make your component content change depending on the browser path => https://go-app.dev/components#nav

**Comment by skhwhu** [comment]
Yes, it works, but it is not a natural way of dealing with it. Could you impove it in the future. Go-App is so cool, Thank you very much.

**Comment by maxence-charriere** [comment]
> it is not a natural way of dealing with it

How reacting to an URL is not natural?

> Could you impove it in the future

How would you like it to be improved?

There are reasons why having it settable in the Route as you tried is not possible:
- Implementation would require overplaying with reflection which opens a lot of room for errors and bugs
- It will take time to implement this and it seems to have less value than other things I want to improve or bring.
- In terms of API design, I don't want to have 2 different places where you initialize a component. Components matter should be dealt with in the component implementation. 
- I want to stick to SRP: here is about setting routes, not initializing components

**Comment by skhwhu** [comment]
OKey,I got it.  Thank you very much!

**Comment by maxence-charriere** [comment]
Thanks for the kind words.
