### ISSUE TITLE
Creating simple app adds div app-wasm-loader and others

### ISSUE THREAD

**Issue by mission-peace** [maxence-charriere/go-app#544]
I created a sample app using examples shown in your documentation. I have a newbie question. How do I get rid of below divs which get added automatically.

&lt;div&nbsp;id="app-wasm-loader"&nbsp;class="goapp-app-info"&gt;
--
&nbsp; | &lt;img&nbsp;id="app-wasm-loader-icon"&nbsp;class="goapp-logo goapp-spin"&nbsp;src="https://storage.googleapis.com/murlok-github/icon-192.png"&gt;
&nbsp; | &lt;p&nbsp;id="app-wasm-loader-label"&nbsp;class="goapp-label"&gt;
&nbsp; | Loading
&nbsp; | &lt;/p&gt;

**Comment by maxence-charriere** [comment]
You can’t. Those are automatically removed when the wasm file is loaded.

**Comment by maxence-charriere** [comment]
You can customize it in the app.Handler too. => Icon and loading label.

**Comment by mission-peace** [comment]
got it. I was doing it totally wrong. Thank you.
