### ISSUE TITLE
Unknown click listener cause  a herf download failed.

### ISSUE THREAD

**Issue by MakDon** [maxence-charriere/go-app#550]
My code:
```Golang
app.Div().Body(
    app.A().Text("click to download").Href("/web/statics/template.xlsx").Download(true),
)
```

which rendered into 
```
<div><a href="/web/statics/template.xlsx" download="">click to download</a></div>
```
everything looks good except that the `<a>` has a click event listener, which changes the windows.location to `http://127.0.0.1:8000/web/statics/template.xlsx`. When i click the `<a>`, the page navigate to `http://127.0.0.1:8000/web/statics/template.xlsx` and return 404.

If i remove the event listener manually, the `<a>` works as expected that directly download the file.

How could i remove the event listener by code?

Thanks very much.

**Comment by maxence-charriere** [comment]
The event handler cannot be removed because it is the way the package work with the component routing.

A working solution would be that i modify that event handler to use the default behavior when the download attributes is set.

Gonna look into this. 

Thanks for reporting that issue.

**Comment by maxence-charriere** [comment]
Hey there,
Just fixed it.

```sh
# v8
go get -u -v github.com/maxence-charriere/go-app/v8

# v9 (currently in development)
go get -u -v github.com/maxence-charriere/go-app/v9@3653b5c
```

**Comment by MakDon** [comment]
The problem seems to be solved. Thanks very much.
