### ISSUE TITLE
Race Condition keeps Component Update Stalled

### ISSUE THREAD

**Issue by nekrondev** [maxence-charriere/go-app#552]
Dear Maxence,

here is another interesting bug I found adding more stuff into my WASM application.

**Go mod:** 
v9.0.0-20210522022017-692ebc622535

**Context:**
I have a root component which renders a navigation menu. Root component includes a page component placeholder that is automagically exchanged with the specific page component request by URL navigation `OnNav` event so in the end all URL mappings refer to root component which does the actual page component loading.

To make things a bit clearer I did ...
```go
// +build wasm
// WASM routing initialization

package main

import (
	"nekrondev_ui/page"

	"github.com/maxence-charriere/go-app/v9/pkg/app"
)

func main() {
	app.Route("/", &page.Root{})
	for _, url := range page.Pages() {
		app.Route("/"+url, &page.Root{})
	}
	app.RunWhenOnBrowser()
}
```
And in root component:

```go
// Snippet from root component fetching OnNav events and restoring the requested page from pagestage map --> this saves the complete state of the page and its components models.
// OnNav will route the main URLs to the proper page components if navigation changed
func (p *Root) OnNav(ctx app.Context) {
	app.Logf("Root: Nav changed to '%s'.", ctx.Page().URL().Path)
	if p.pagestate == nil {
		p.pagestate = make(map[string]app.UI)
	}
	switch ctx.Page().URL().Path {
	case "/" + MASTERDATA, "/":
		if comp, ok := p.pagestate[MASTERDATA]; !ok {
			p.page = &masterdata{
				messenger: p,
			}
			p.pagestate[MASTERDATA] = p.page
		} else {
			p.page = comp
		}
	case "/" + AUTOCONF:
		if comp, ok := p.pagestate[AUTOCONF]; !ok {
			p.page = &autoconf{
				messenger: p,
			}
			p.pagestate[AUTOCONF] = p.page
		} else {
			p.page = comp
		}
	default:
		p.page = &notfound{}
	}
}
```
The pages itself include some custom-made components. 

**Issue:**
Now comes the interesting part. Everytime I switch from "masterdata" page to "autoconf" page and back, the masterdata page is only initially updated by go-app (Mount event) restoring the page state from the pagestate cache.  That's okay but once the mount has happend masterdata page events are no longer updating the DOM.

**Analysis**:
I put a bunch of debug `Logf()` into component and engine framework files and found the culprit.
It's basically a race condition between mounting and mount checks and invalidation of go-app update cache.

First off when switching from masterdata page to autoconf page masterdata page component is submitting an event which is processed by engine.go `scheduleComponentUpdate()` function. 
Here you check if the component that issued the event is mounted or not and discards queueing the event for later processing if the component is unmounted.

```go
func (e *engine) scheduleComponentUpdate(n UI) {
	if !n.Mounted() {
		return
	}
...
```
Now the race between root components `OnNav()` event handler and engines update scheduler starts.
Since the root components `OnNav()` event hasn't yet fired the masterdata page components update event has been cached to engines update queue.

Meanwhile root components `OnNav()` event has been fired changeing the pages placeholder component to autoconf page component dismounting masterdata page component.

Next the go-app engines `updateComponents()` ticker has triggered an update flush.

```go
func (e *engine) updateComponents() {
	if len(e.updates) == 0 {
		return
	}

	sortUpdateDescriptors(e.updateQueue)
	for _, ud := range e.updateQueue {
		compo := ud.compo
		if !compo.Mounted() {
			continue
		}

		if _, isNotUpdated := e.updates[compo]; !isNotUpdated {
			continue
		}

		if err := compo.updateRoot("updateComponents " + compo.name()); err != nil {
			panic(err)
		}
		e.componentUpdated(compo)
	}

	e.updateQueue = e.updateQueue[:0]
}
```
Here you gonna check if the component is mounted which in case of the race is false for masterdata page component. Thus the loop is continued without any masterdata component updates because the component is not visible to the DOM. However at  the end of the loop after you processed all cached update events the cache is reset removing the unprocessed masterdata page event but still keeping the e.updates[compo] update is scheduled state.

Now if I switch back from autoconf page to masterdata page any masterdata page events will not be queued because of e.updates[] check as go-app thinks that the component update is still in the pipe.

```go
// engine.go scheduledComponentUpdate()
...
	for {
		if c, isCompo := n.(Composer); compo == nil && isCompo {
			if _, isScheduled := e.updates[c]; isScheduled {
				return
			}
			compo = c
		}
...
```

**Bugfix:**
I added the updates cache removal if a component had been found unmounted  so new masterdata page events can be processed.

```go
func (e *engine) updateComponents() {
	if len(e.updates) == 0 {
		return
	}

	sortUpdateDescriptors(e.updateQueue)
	for _, ud := range e.updateQueue {
		compo := ud.compo
		if !compo.Mounted() {
			// remove component from queued check as scheduling of an unmounted component should be impossible
                        // however in a special race condition this could be possible to better clean up here to prevent stalled components
			e.componentUpdated(compo)
			continue
		}

		if _, isNotUpdated := e.updates[compo]; !isNotUpdated {
			continue
		}

		if err := compo.updateRoot("updateComponents " + compo.name()); err != nil {
			panic(err)
		}
		e.componentUpdated(compo)
	}

	e.updateQueue = e.updateQueue[:0]
}
```

Cheers,
Nek

**Comment by maxence-charriere** [comment]
Hello there, thanks for taking time with this.

Could it be possible to see the `Root.Render()` method too?

**Comment by maxence-charriere** [comment]
Look like you are right about the update. nice catch!

**Comment by maxence-charriere** [comment]
Thank you so much for this. I just pushed a fix.
```sh
go get -u -v github.com/maxence-charriere/go-app/v9@7981ffb
```

**Comment by nekrondev** [comment]
Hi Maxence,

Thanks for your fast merge. I upgraded to your new commit and after recompilation of my UI everything seems to work fine  👍
