### ISSUE TITLE
feature request: attribute binding

### ISSUE THREAD

**Issue by MakDon** [maxence-charriere/go-app#558]
It is not so convenient to reach the attirbute value of a dom so far.     

Could go-app support something like vue's mvvm that support binding go variable with dom value, which update the go variable when the dom's value is changed.
Just used like this:
```
type foo struct{
app.Compo
value int
}

func (c *foo) Render() app.UI {
app.Input().Bind("value", &c.value)
}
```

When user change the `<input>`'s value, the variable `foo.value` is updated according the change.

It can be implemented like the following pseudo code:

```
func (c *Compo) Bind(target string, dst interface{}){
c.OnChange(func(ctx app.Context, e app.Event) {
    if changedAttributeName == target{
        setValue(dst, changedAttributeValue)
    }
})
}

```

with `bind()` method, we use go struct's attirbute as is, instead of writing js code to reach the dom's attribute value.

Thanks.

**Comment by maxence-charriere** [comment]
Did you check https://go-app.dev/reference#Compo.ValueTo?

**Comment by MakDon** [comment]
> Did you check https://go-app.dev/reference#Compo.ValueTo?

Thanks. It seems that it meets my demand.
