### ISSUE TITLE
linkerror: webassembly.instantiate(): import #5 module="go" function="runtime.walltime" error: function import requires a callable

### ISSUE THREAD

**Issue by AvikantSrivastava** [maxence-charriere/go-app#574]
I get this error 
```linkerror: webassembly.instantiate(): import #5 module="go" function="runtime.walltime" error: function import requires a callable```

When I try to run the server 

Screenshot of `http://localhost:8000/`
![image](https://user-images.githubusercontent.com/41926176/132256401-5c295bc1-6956-49fd-9963-946ced8698dc.png)

**Comment by maxence-charriere** [comment]
Hello, this is an issue related to go 1.17, See https://github.com/maxence-charriere/go-app/issues/569
Working on releasing v9 right now, this will go live soon.

**Comment by Virgil-N** [comment]
I got the same error.
