### ISSUE TITLE
Documentation issues in start.md

### ISSUE THREAD

**Issue by pizzalord22** [maxence-charriere/go-app#577]
running the example code from getting started gives the following error: 

linkerror: webassembly.instantiate(): import #5 module="go" function="runtime.walltime" error: function import requires a callable

**Comment by maxence-charriere** [comment]
Hello, this is an issue related to go 1.17 => https://github.com/maxence-charriere/go-app/issues/569
Currently working on releasing v9. This gonna be fixed on main branch soon.

**Comment by pizzalord22** [comment]
thanks for your quick response, since this issue is related to go 1.17 and not your awesome library i will close it
