### ISSUE TITLE
Provide html head edit

### ISSUE THREAD

**Issue by Virgil-N** [maxence-charriere/go-app#578]
I want to change windows tab title, but there is no method to solve.

**Comment by maxence-charriere** [comment]
When you implement [Navigator](https://go-app.dev/reference#Navigator), use:

```go
func (c *myCompo) OnNav(ctx app.Context) {
    ctx.Page().SetTitle("YOUR TITLE")
}
```

**Comment by Virgil-N** [comment]
> When you implement [Navigator](https://go-app.dev/reference#Navigator) in your component, use:
> 
> ```go
> func (c *myCompo) OnNav(ctx app.Context) {
>     ctx.Page().SetTitle("YOUR TITLE")
> }
> ```

Got it. Thanks.
