### ISSUE TITLE
How can i send some data from a components to others?

### ISSUE THREAD

**Issue by Virgil-N** [maxence-charriere/go-app#579]
How can i send some data from a components to others?

Can U show me some examples?

**Comment by maxence-charriere** [comment]
If you use v9, you can use `ctx.NewAction()` to send and  `ctx.Handle()` to receive.


Component that sends:
```go
func (c *compoA) OnClick(ctx app.Context, e app.Event) {
    ctx.NewActionWithValue("broadcast-msg", "Hello")
}
```

Component that receives:
```go
func (c *compoB) OnMount(ctx app.Context) {
    ctx.Handle("broadcast-msg", c.handleMsg)
}

func (c *compoB) handleMsg(ctx app.Context, a app.Action) {
    msg, ok := a.Value.(string)
    if !ok {
        fmt.Println("bad msg type")
        return
    }

    fmt.Println(msg) // or whatever you need
}
```

**Comment by Virgil-N** [comment]
> If you use v9, you can use `ctx.NewAction()` to send and  `ctx.Handle()` to receive.
> 
> 
> Component that sends:
> ```go
> func (c *compoA) OnClick(ctx app.Context, e app.Event) {
>     ctx.NewActionWithValue("broadcast-msg", "Hello")
> }
> ```
> 
> Component that receives:
> ```go
> func (c *compoB) OnMount(ctx app.Context) {
>     ctx.Handle("broadcast-msg", c.handleMsg)
> }
> 
> func (c *compoB) handleMsg(ctx app.Context, a app.Action) {
>     msg, ok := a.Value.(string)
>     if !ok {
>         fmt.Println("bad msg type")
>         return
>     }
> 
>     fmt.Println(msg) // or whatever you need
> }
> ```

I'll try. Thanks.

**Comment by mar1n3r0** [comment]
@maxence-charriere I see you have utilized the Broadcast Channel API concept in an interesting way. 

Went through the commits implementing it and wanted to note and ask a few questions:

1. I have noticed that you mimic the API concept but you are not using the actual Broadcast Channel API underneath?
2. Looking at the naming convention it seems that you have found your usage with it as actions between components rather than update global state async?
3. The value is converted to string - maybe it can be type hinted and using reflection we can send more complex data types between components?
4. Does the fact that it is not using Broadcast Channels API mean that keeping global state between independent components still require centralized async requests ? https://github.com/maxence-charriere/go-app/issues/436#issuecomment-815628948

**Comment by maxence-charriere** [comment]
> I have noticed that you mimic the API concept but you are not using the actual Broadcast Channel API underneath?

No need to use the broadcast channel API for a simple msg between components.

> Looking at the naming convention it seems that you have found your usage with it as actions between components rather than to actually maintain global state?

Actions is a different concept than global states. It is to trigger a function when a given action is created. This function can be inside or outside a coponent. Its msg based nature can also be used to notify change to component. It up to how you want to use it.

Global state are achieved by those context calls:
- `SetState(state string, v interface{}, opts ...StateOption)`
- `GetState(state string, recv interface{})`
- `ObserveState(state string) Observer`

There is also a state option that  uses the Broadcast channel and allow to propagate a state to other tabs:
```go
ctx.SetState("my-state", "foo", app.Broadcast)
```

> The value is converted to string - maybe it can be type hinted and using reflection we can send more complex data types between components?

No, the value is an `interface{}`

> Does the fact that it is not using Broadcast Channels API mean that keeping global state between independent components still require centralized async requests ?

See responses above.

**Comment by Virgil-N** [comment]
```
func (home *Home) OnMount(ctx app.Context) {
	fmt.Println("mounted")
	ctx.Handle("click-me", home.handleMsg)
}

func (home *Home) handleMsg(ctx app.Context, a app.Action) {
	fmt.Println(a.Value)
	if msg, ok := a.Value.(string); ok {
		fmt.Println("get msg: ", msg)
	} else {
		fmt.Println("error")
	}
}

```

I found there is no message printed.
It's the OnMount function has some problem?

**Comment by maxence-charriere** [comment]
Did you create an action ?

**Comment by maxence-charriere** [comment]
It is not supposed to. are you checking in the terminal or the browser console?

**Comment by Virgil-N** [comment]
Action is here:

```
func (login *Login) withClick(ctx app.Context, e app.Event) {
	fmt.Println(ctx) // ok
	fmt.Println(e) // ok
	ctx.NewActionWithValue("click-me", "from login")
}
```

Seem OnMount is not work.

**Comment by Virgil-N** [comment]
All code is here:

```
// home
type Home struct {
	app.Compo
	name string
}

func (home *Home) Render() app.UI {

	return app.Div().Body(
		&components.Nav{},
		&Login{},
		app.Div().Class("main").Body(
			app.Aside().Class("aside").Body(),
			app.Section().Class("section").Body(
				app.Input().
					Value(home.name). // The name field used as current input value
					OnInput(home.OnInputChange),
				app.Br(),
				app.Text(home.name),
				app.Br(),
				app.Button().Class("waves-effect waves-light btn").Body(
					app.Text("go"),
				).OnClick(home.Go)),
		),
	)
}

func (home *Home) OnInputChange(ctx app.Context, e app.Event) {
	home.name = ctx.JSSrc().Get("value").String()
	home.ValueTo(&home.name)
	home.Update()
}

func (l *Home) Go(ctx app.Context, e app.Event) {
	ctx.Navigate("/home")
}

func (home *Home) OnMount(ctx app.Context) {
	fmt.Println("mounted")
	ctx.Handle("click-me", home.handleMsg)
}

func (home *Home) handleMsg(ctx app.Context, a app.Action) {
	fmt.Println(a.Value)
	if msg, ok := a.Value.(string); ok {
		fmt.Println("get msg: ", msg)
	} else {
		fmt.Println("error")
	}
}

// login
type Login struct {
	app.Compo
	Name     string
	password string
}

func (login *Login) Render() app.UI {
	return app.Div().Class("ui grid container center middle aligned").Body(
		app.Div().Class("login-wrap").Body(
			app.H2().Class("ui header").Body(
				app.Div().Class("content").Body(
					app.Text("Login"),
				),
			),
			app.Div().Class("ui large form").Body(),
			app.Div().Class("ui message").Body(
				app.Text("新用户？"),
				app.A().Href("#").Text("注册"),
			),
			app.Button().Body(
				app.Text("click me"),
			).OnClick(login.withClick),
		),
	)
}

func (login *Login) withClick(ctx app.Context, e app.Event) {
	fmt.Println(ctx)
	fmt.Println(e)
	ctx.NewActionWithValue("click-me", "from login")
}


```

**Comment by maxence-charriere** [comment]
That is weird I don't see the error. Do you have a repo that I could clone to try ?

**Comment by maxence-charriere** [comment]
```go
func (home *Home) OnInputChange(ctx app.Context, e app.Event) {
	home.name = ctx.JSSrc().Get("value").String()
	home.ValueTo(&home.name) // This is to be used in a Render method, does nothing here
	home.Update() // In v9 no need to call this anymore
}
```

**Comment by Virgil-N** [comment]
> ```go
> func (home *Home) OnInputChange(ctx app.Context, e app.Event) {
> 	home.name = ctx.JSSrc().Get("value").String()
> 	home.ValueTo(&home.name) // This is to be used in a Render method, does nothing here
> 	home.Update() // In v9 no need to call this anymore
> }
> ```
> 

I'll send a link a few hours later.

**Comment by Virgil-N** [comment]
> That is weird I don't see the error. Do you have a repo that I could clone to try ?

Link is here: https://github.com/Virgil-N/go-app-project-1.git

**Comment by Virgil-N** [comment]
> ```go
> func (home *Home) OnInputChange(ctx app.Context, e app.Event) {
> 	home.name = ctx.JSSrc().Get("value").String()
> 	home.ValueTo(&home.name) // This is to be used in a Render method, does nothing here
> 	home.Update() // In v9 no need to call this anymore
> }
> ```

It's my fault. I was in wrong page.
