### ISSUE TITLE
V9 demo - state  management

### ISSUE THREAD

**Issue by mar1n3r0** [maxence-charriere/go-app#580]
Noticed that the demos are a bit behind and up to V7. Can we have a demo of V9 when completed?

I am specifically interested in the following scenario:

1. We have 2 independent components that fetch async JSON
2. Both need to use an excerpt of the data that the other component fetched
3. Rather than pulling the data when available they should be able to notify each other with the new payload
4. Both update themselves independently based on the broadcasted data
5. No centralized requests
6. Ability to operate independently without even knowing about each other
7. Can send any type of data, detect the type and deserialize in that same type intended
8. Publish/Subscribe and react to state changes
9. Basically solving this: https://github.com/maxence-charriere/go-app/issues/436#issuecomment-815628948

**Comment by maxence-charriere** [comment]
I'll make a documentation article about it.
