### ISSUE TITLE
how to use web components?

### ISSUE THREAD

**Issue by ystyle** [maxence-charriere/go-app#581]
like [wired-elements](https://github.com/rough-stuff/wired-elements), it a web components ui.

can add hellper method, like this:  
```go
app.RawElement("wired-input").attr("placeholder", "Enter name")
app.RawElement("wired-button").attr("title", "Click Me').text("Click Me")
```

**Comment by maxence-charriere** [comment]
Hi, Web components are currently not supported. The hack is to use App.Raw and put raw html in.

Whether its full implementation or syntax hack, I have to do some experiences to see what is possible in this area.
