### ISSUE TITLE
Is it possible to instantiate `Vue` ?

### ISSUE THREAD

**Issue by electricbubble** [maxence-charriere/go-app#583]
> https://vuetifyjs.com/en/components/tabs/#usage

I can't get this `js` to work

```js
new Vue({
  el: '#app',
  vuetify: new Vuetify(),
  
})
```

---

That doesn't make `Vue` work

```golang
app.Window().
	Get("Vue").
	New("Vue", map[string]interface{}{
		"el":      "#app",
		"vuetify": app.Window().Get("Vuetify").New("Vuetify"),
	})
```

What should I do?

**Comment by maxence-charriere** [comment]
Where do you call thils ?

**Comment by electricbubble** [comment]
I'm not so sure it's the right thing to do

```golang
type home struct {
	app.Compo
}

func (h *home) Render() app.UI {
	if app.IsClient && h.Mounted() {
		value := app.Window().
			Get("Vue").
			New("Vue", map[string]interface{}{
				"el":      "#app",
				"vuetify": app.Window().Get("Vuetify").New("Vuetify"),
			})
		_ = value

		app.Window().Get("console").Call("log", app.Window().Get("Object").Call("keys", value))

		app.Window().Get("console").Call("log", h.JSValue())
		app.Window().Get("console").Call("log", value)
	}
	return tabsWithVuetify()
}
```

**Comment by maxence-charriere** [comment]
you should implement the [Mounter](https://go-app.dev/components#mount) interface for this. There are chances that what is `if h.Mounted()` is never called.

something like
```go
func (h *home) OnMount(ctx app.Context) {
     // You js interop code
}
```

**Comment by electricbubble** [comment]
> 
> ```golang
> type home struct {
> 	app.Compo
> }
> 
> func (h *home) Render() app.UI {
> 	return tabsWithVuetify()
> }
> 
> func (h *home) OnMount(ctx app.Context) {
> 	value := app.Window().
> 		Get("Vue").
> 		New("Vue", map[string]interface{}{
> 			"el":      "#app",
> 			"vuetify": app.Window().Get("Vuetify").New("Vuetify"),
> 		})
> 	_ = value
> 
> 	app.Window().Get("console").Call("log", app.Window().Get("Object").Call("keys", value))
> 
> 	app.Window().Get("console").Call("log", h.JSValue())
> 	app.Window().Get("console").Call("log", value)
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/42672996/133376937-f49ae28f-46bf-4f21-a4d4-be7281259c2b.png)
> 


Still not as expected

---

When I type this code directly into `DevTools`

```js
 new Vue({
      el: '#app',
      vuetify: new Vuetify(),
    })
```

It works

![image](https://user-images.githubusercontent.com/42672996/133377035-218723f4-138d-4311-a50b-485762f82731.png)

**Comment by maxence-charriere** [comment]
You js interop code seems to not be correct:
```go
app.Window().
	Get("Vue").
	New("Vue", map[string]interface{}{
		"el":      "#app",
		"vuetify": app.Window().Get("Vuetify").New("Vuetify"),
	})
```

Try
```go
app.Window().
	Get("Vue").
	New(map[string]interface{}{
		"el":      "#app",
		"vuetify": app.Window().Get("Vuetify").New("Vuetify"),
	})
```

**Comment by electricbubble** [comment]
Awesome!

Thanks a lot!
