### ISSUE TITLE
Making PWA installable

### ISSUE THREAD

**Issue by stool79** [maxence-charriere/go-app#584]
Hi there. Thanks again for the great work.

I've used you framework to successfully put together a little internal management UI. 

I'm using (from go.mod)
github.com/maxence-charriere/go-app/v8 v8.0.2

Compiling with go 1.16.6 on mac 10.15.5

I'm struggling to understand why my application manifest file does not create the expected "install" prompt on chrome. Looking into the dev tools I see two issues highlighted on the "Application" tab.

1. App manifest. "No matching service worker detected...."
2. A console log error

``` console
app-worker.js:4 installing app worker 25e96bdb4b5bce69fe2a9079e6071c6bb6fff68e
app.js:10 registering app service worker
app-worker.js:1 Uncaught (in promise) DOMException: Cache.addAll() encountered a network error
```

the app-worker.js file
``` js
const cacheName = "app-" + "25e96bdb4b5bce69fe2a9079e6071c6bb6fff68e";

self.addEventListener("install", event => {
  console.log("installing app worker 25e96bdb4b5bce69fe2a9079e6071c6bb6fff68e");
  self.skipWaiting();

  event.waitUntil(
    caches.open(cacheName).then(cache => {
      return cache.addAll([
        "/",
        "/app.css",
        "/app.js",
        "/manifest.webmanifest",
        "/wasm_exec.js",
        "/web/app.wasm",
        "/web/css/app.css",
        "/web/css/bulma.min.css",
        "/web/images/180.png",
        "/web/images/192.png",
        "/web/images/512.png",
        
      ]);
    })
  );
});
```

I'm not suspecting the files in the web directory since the app renders as expected. The root files I've never seen unless you use a function like app.GenerateStaticWebsite() to write them to disc. This is not currently how I host it.

My app is running the "vanilla" way as described in your go-app "Getting Started" documentation.

Does this feature only work if you export a site? Any idea otherwise what is wrong with the app_worker trying to cache?
Is that last "," for the last file in the cache file array causing issues?

**Comment by stool79** [comment]
It seems that my file is pretty much identical to the one server by the "go-app documentation" site hosted on github. 

Incidentally murlok.io and lofimusic.app present with the same unexpected outcome I describe above. Not installable.

I'm using Chrome Version 93.0.4577.82 (Official Build) (x86_64)

**Comment by maxence-charriere** [comment]
On what are you hosting your app?

**Comment by stool79** [comment]
hosted within a docker container.
I'll try 8.0.4

**Comment by maxence-charriere** [comment]
Try upgrade, i may have fix something because i got that issue with Murlok.io

**Comment by stool79** [comment]
have the following error with latest pull 8.1.0

``` console
GOARCH=wasm GOOS=js go build -o build/web/app.wasm ./cmd/mgr_gui
# github.com/maxence-charriere/go-app/v8/pkg/app
vendor/github.com/maxence-charriere/go-app/v8/pkg/app/engine.go:254:14: updates.Reset undefined (type *time.Ticker has no field or method Reset)
vendor/github.com/maxence-charriere/go-app/v8/pkg/app/engine.go:271:13: updates.Reset undefined (type *time.Ticker has no field or method Reset)
```

**Comment by stool79** [comment]
I don't understand why go mod pulled 8.1.0

Going to force it onto your last github tag 8.0.4

**Comment by stool79** [comment]
no joy on 8.0.4. It compiled but executed with the same outcomes.

**Comment by maxence-charriere** [comment]
Mmmm, you are saying that you can’t install murlok.io and lofimusic.app ?

**Comment by stool79** [comment]
> Mmmm, you are saying that you can’t install murlok.io and lofimusic.app ?

Yes and No

I have no idea why this is an issue on my dev laptop. I can't get the install option on my laptop. However when I browsed to murlok.io and lofimusic.app, on another iMac running the same version chrome browser, it was Installable.

My app however from that same iMac was still not installable. The app is hosted within a docker container on the local network. For now I just access it via a raw url like http://ip:port. Not sure if I need to host in a special way.

**Comment by stool79** [comment]
https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs

according to this article you need to serve the pwa from a secure https domain. This might be why chrome is getting in the way.

I don't think there is an issue with your code or my understanding any longer. Happy to close this.

**Comment by stool79** [comment]
Btw thanks for your prompt responses again.

**Comment by maxence-charriere** [comment]
Seems weird, i can install my localhost dev versions.

**Comment by stool79** [comment]
> Seems weird, i can install my localhost dev versions.

I'll try with an empty "hello world" app tomorrow

**Comment by stool79** [comment]
Man what a headache.

Developing with docker can be tricky on a laptop. It was quietly eating up all my disk space and for some reason chrome chose to deal with it in its own unique ways by not caching.

I saw an alert that my hdd was full and pruned all unused content in docker. App is now installable/cacheable

**Comment by maxence-charriere** [comment]
I glad you where able to figure out. Started to freak out that this thing was broken 😅.
