### ISSUE TITLE
Question about some method signatures

### ISSUE THREAD

**Issue by mvpmvh** [maxence-charriere/go-app#585]
Instead of `Style(k, v string)`, could the signature be `Style(map[string]string)`? Similarly, could `Class(string)` become `Class(...string)`? I think it would make it easier to apply multiple styles and classes in a declarative syntax. The current api seems to require a combo of declarative and imperative code styles that's less elegant. For example:

```
func (r *RowComponent) Render() app.UI {
    c := app.Div().
        Class("row")
    for _ class := range r.Classes {
       c = c.Class(class)
    }    
    for k, v := range r.Styles {
        c = c.Style(k, v)
    }
    return c.Body(...)
}
```

vs

```
func (r *RowComponent) Render() app.UI {
    return app.Div().
        Class(append(r.Classes, "row")...).
        Style(r.Styles).   
        Body(...)
}
```

**Comment by maxence-charriere** [comment]
I'll take a look for something.
