### ISSUE TITLE
How to set a html page with assigned css file

### ISSUE THREAD

**Issue by Virgil-N** [maxence-charriere/go-app#589]
I have a html page and I want include only one css file. How can I do it?

**Comment by electricbubble** [comment]
```go
http.Handle("/", &app.Handler{
		Name:   "go-app",
		Styles: []string{
			"/web/your.css",
		},
	})
```

**Comment by maxence-charriere** [comment]
see https://go-app.dev/static-resources

**Comment by Virgil-N** [comment]
> ```go
> http.Handle("/", &app.Handler{
> 		Name:   "go-app",
> 		Styles: []string{
> 			"/web/your.css",
> 		},
> 	})
> ```

Got it. Thanks.

**Comment by Virgil-N** [comment]
> see https://go-app.dev/static-resources

But how to include a css file in a component ?

**Comment by Virgil-N** [comment]
Or how can I edit head tag in component ?
I mean I just want to include one css file in a component direct.
I don't want to write many handles.

**Comment by Virgil-N** [comment]
There is  a lot files repeated.
```
http.Handle("/", &app.Handler{
		Name:        "Go-App",
		Description: "Go-App!",
		Styles: []string{
			"/web/styles/index.css",
		},
		Scripts: []string{
			"/web/assets/jquery-3.6.0.min.js",
			"/web/assets/Semantic-UI-CSS-master/semantic.min.js",
		},
	})

	http.Handle("/login", &app.Handler{
		Name:        "Login",
		Description: "Login Page",
		Styles: []string{
			"/web/styles/index.css", // repeated
			"/web/styles/login.css", 
		},
		Scripts: []string{
			"/web/assets/jquery-3.6.0.min.js", // repeated
			"/web/assets/Semantic-UI-CSS-master/semantic.min.js", // repeated
		},
	})
```

**Comment by Virgil-N** [comment]
I suggest provide a function named Head.Add() to add meta and css files in page.
```
app.Html().Body(
    app.Head().Add("link").Type("text/css").Ref("stylesheet").Href("/web/styles/login.css"),
    app.Dvi().Body(
        app.Text("hello world"),
    ),
)
```

**Comment by Virgil-N** [comment]
Or like this:
```
func (login *Login) OnNav(ctx app.Context) {
	ctx.Page().SetTitle("Login Page")
	ctx.Page().Head().Add("link").Type("text/css").Ref("stylesheet").Href("/web/styles/login.css")
}
```

**Comment by maxence-charriere** [comment]
I wonder if it is that worth it?

It is true that includes are repeated but css and script file are cached into the web browser until a new version of the app is deployed.

They are not re downloaded again. Also since the app work as a SPA, things like jquery onload will happen once too.

**Comment by maxence-charriere** [comment]
Also the risk you get by loading a css at a page change is style glitch. Since the new page would be loaded instant (its a SPA) while your css would not. There will a blink where the new content will appear without css.

**Comment by Virgil-N** [comment]
I just want to write less code. All right, I'll use handle to load css file.
