### ISSUE TITLE
How To Share Predefined (Customizable) Widgets?

### ISSUE THREAD

**Issue by mvpmvh** [maxence-charriere/go-app#590]
This project is pretty sweet. I like it a bunch and would like to prepackage some components (i.e. build a UI library based off material, bootstrap, etc.) that can be reused by other developers. I'm wondering how would you approach building a UI library? One issue I'm trying to solve is how to allow other developers to customize the behavior of any widget. For example, if I create `CustomWidget` how would I allow other developers to provide custom event handlers? I know I could manually add every method for `HTMLDiv` to `CustomWidget` , but is there a _better_ way? If every component embeds `app.Compo`, can those methods be set on `app.Compo` so that every widget already has those methods?

**Comment by mvpmvh** [comment]
closing because after thinking about things further, it seems the way to do this is to just add all the methods an end-user could customize to the widget's method set.

**Comment by maxence-charriere** [comment]
I did one that i use for the docs app and other project. Take a look on the ui package from this repo.
