### ISSUE TITLE
Documentation: Declarative Syntax example correction

### ISSUE THREAD

**Issue by andyedison** [maxence-charriere/go-app#598]
I am new to this project, so please forgive me if I misunderstood and it isn't a bug.

On the documentation page https://go-app.dev/declarative-syntax#standard-elements the Standard Elements example, it looks like the second component should have a period instead of a comma between the P() and the Text("Content") methods

```go
func (c *myCompo) Render() app.UI {
	return app.Div().Body(        // Div Container
		app.H1().Text("Title"),   // First child
		app.P(), Text("Content"), // Second child <=== this line
	)
}
```

This is a very interesting project, lots of good work.

**Comment by maxence-charriere** [comment]
Good catch, i ll correct it. Thank you
