### ISSUE TITLE
Wondering about some behaviour I don't unterstand.

### ISSUE THREAD

**Issue by oderwat** [maxence-charriere/go-app#602]
With the example from the README here on the main page ("Hello World" with the Input field and two routes). When I change the code for adding the route to `app.Route("/", &hello{name: "Test"})`. Why will it not show "Hello, Test"?

**Comment by electricbubble** [comment]
**REASON**:

`app.Route` is just to get `type`

https://github.com/maxence-charriere/go-app/blob/e7508c6bba3e99aec6ba0347fa0366c910b582f6/pkg/app/route.go#L44
```golang
func (r *router) route(path string, c Composer) {
	r.mu.Lock()
	defer r.mu.Unlock()

	r.routes[path] = reflect.TypeOf(c)
}
```

---

How to change:

```diff
+ var _ app.Mounter = (*hello)(nil)

type hello struct {
	app.Compo

	name string
}

+  func (h *hello) OnMount(ctx app.Context) {
+ 	h.name = "Test"
+ }

func (h *hello) Render() app.UI {
	return app.Div().Body(
		app.H1().Body(
			app.Text("Hello, "),
			app.If(h.name != "",
				app.Text(h.name),
			).Else(
				app.Text("World!"),
			),
		),
		app.P().Body(
			app.Input().
				Type("text").
				Value(h.name).
				Placeholder("What is your name?").
				AutoFocus(true).
				OnChange(h.ValueTo(&h.name)),
		),
	)
}

```

**Comment by oderwat** [comment]
OK. Makes sense now! Thank you!

**Comment by oderwat** [comment]
Doing it that way, one can see the Text "World" briefly after the page loads. However, that is not what I expect when something happens "onMount" for the component. Is there a way to avoid that?

So when I see this now, I wonder how I can add different defaults (props to a component) for different routes when there is no way to add values?

**Comment by electricbubble** [comment]
pkg/app/component.go

🤔I think **OnNav** should be what you need.

**Comment by oderwat** [comment]
OK. This kinda works, but doesn't the component then needs to know the path / URL to "adapt". This feels strange to me. Is there no way to give "properties" to components, so one can "configure" them for what they are needed? I may ask stupid things though. I am just "stumbling" around the examples currently.

**Comment by oderwat** [comment]
Well, from what I understand, one would implement a component (type) per route and then uses something like the hello component in that component which then can have properties. So adding the component to the route is a special case?

**Comment by electricbubble** [comment]
Let's wait for the author's reply. 

🧐 I'm only interested in this project recently.

发自我的iPhone

**Comment by maxence-charriere** [comment]
Hello there,
So as mentioned before, using `Route` is just to associate a component type with a path. It does not matter if you set a variable or not, a component will be freshly created with its Zero value.
=> https://go-app.dev/routing

> Where should you put your default value?

- In OnMount => [Mounter](https://go-app.dev/reference#Mounter)
- If the default value depends on a path: do it in OnNav => [Navigator](https://go-app.dev/routing)




https://go-app.dev/routing


>

**Comment by maxence-charriere** [comment]
You can also give default values to components from their exported fields when they are nested in other components. 

The scenario above deals with the root component, where this should be done from its lifecycle.

**Comment by oderwat** [comment]
OK. Thank you.

Still, there is the somewhat concerning part, that it renders the "original" value before the "default" when I put the code to set the default into the mount (or the route).

**Comment by maxence-charriere** [comment]
The prerender is just to generate html code for robot, on the client side only wasm take over.

the onmount is not necessarily rendered after the original state. Internally there is a loop that render new state each x time. Creating, mount, onnav can happen in the same time frame and the component would be rendered once rather than 3 times.

**Comment by oderwat** [comment]
Well, I wonder how one would create this "Hello, World!" with say 5 random Names. Where each time the page loads another name is displayed. But I don't want to have it "blinking" so the name should be there before the page is visible to the user.

**Comment by oderwat** [comment]
> the onmount is not necessarily rendered after the original state. Internally there is a loop that render new state each x time. Creating, mount, onnav can happen in the same time frame and the component would be rendered once rather than 3 times.

But does "onMount" not usually means that it is guaranteed to be executed before it is "shown"?
