### ISSUE TITLE
AutoFocus(true) does not work.

### ISSUE THREAD

**Issue by oderwat** [maxence-charriere/go-app#604]
I continued testing go-app and had some nice success coding my "guess the number" game, which I usually implement in the beginning when testing a new library (maybe I make it available on my GitHub later today.).

I figured out how to run a "select" and "focus" inside of the event handler. But I also found that "autofocus" is not working. I actually usually don't use it anyway but as the examples have it included I wonder if that is just broken now for some reason?

**Comment by omani** [comment]
I can confirm, autofocus does not work.

**Comment by mlctrez** [comment]
https://stackoverflow.com/questions/27313872/auto-focus-is-not-working-for-input-field/27314017#27314017

> autofocus is defined to work reliably only on page load. It is not really suited for situations where you are swapping, or opening, or unhiding DOM elements such as in a single-page application framework. You are likely to have to resort to handling the autofocusing yourself.

There probably needs to be an example showing `JSValue().Call("focus")`:
```go
func (c *component) Focus() {
	if c.Mounted() {
		c.JSValue().Call("focus")
	}
}
```
