### ISSUE TITLE
Can we move or just have aliases to template elemens?

### ISSUE THREAD

**Issue by ignishub** [maxence-charriere/go-app#608]
This will make it a lot easier to read templates for rendering.

Because the Render function already can be complicated, we can move all html template functions to separate package or just have aliases in separate packages.

With this we can just dot import template package:

```go
func (c *ChatBox) Render() UI {
	return Div().Class("panel").Body(
		Div().Class("panel-header").Body(
			Div().Class("panel-title", "h6").Text("Chat"),
		),
		Div().Class("panel-body").Body(
			Range(c.messages).Slice(func(i int) UI {
				return &c.messages[i]
			}),
		),
	)
}
```

**Comment by maxence-charriere** [comment]
I don’t understand what you ask.

**Comment by ignishub** [comment]
Sorry for my bad english i guess.

I am talking about creating new package where we will have only aliases for all structs and functions  that used in Render function of component.

With this we can just import this package like this:

```go
import . "github.com/maxence-charriere/go-app/v9/pkg/app/template"
```

Because of this we will have clean templates

**Comment by maxence-charriere** [comment]
You mean a library that contains components that implement things like a chatbox?

**Comment by ignishub** [comment]
Hm. This was just an example of how it will look :)

Just look on Render function. All tags without "app."

In complex templates it will be easer to read

**Comment by maxence-charriere** [comment]
But you cannot drop the app tag. This is how go is working.

**Comment by ignishub** [comment]
But  you can.  If you do just:

```go
import . "github.com/maxence-charriere/go-app/v9/pkg/app"
```

But there is a problem. With this we include in global namespace ALL content of app. Thats why we can move template functions to new package or create aliases in this package. Now we can import that way only this package  to global namespace

```go
import . "github.com/maxence-charriere/go-app/v9/pkg/app/template"
```

**Comment by maxence-charriere** [comment]
Oh, I see. That is cool. Still for the template stuff. I still don't get it. I don't provide ready-to-use components in the `app` package. What do you mean by clean template?

**Comment by ignishub** [comment]
By clean templates I mean less code and easier to read templates. Sometimes layouts can be very big and messy(it is html after all). So in my opinion having possibility of removing noise in form of package name in big templates we will increase readability of template code.

**Comment by maxence-charriere** [comment]
I agree. I'm wondering if promoting that way is the right thing. By default, this is not the way you use a package with Go and go app would add a lot in the global scope. Should it be the decision of the user to use it that way?

**Comment by maxence-charriere** [comment]
I m glad I learned about it though, gonna try it a bit.

**Comment by ignishub** [comment]
Yeah it is decision of user. He can use it as he want. And i agree that this questionable. But it will be good to have this option

**Comment by maxence-charriere** [comment]
I though that if you import goapp with `"."` it going to do the job. There is not a lot of call besides the HTML functions.

**Comment by ignishub** [comment]
But there is a problem, if we import all goapp we will import ALL go app. 

More you import in global scope - more chance to name collision

In templates (HTML tags and template functions like If and Range) we have only them.

**Comment by maxence-charriere** [comment]
I see. I will experience with it.

**Comment by ignishub** [comment]
Thank you :) 

Also thank for your project it is inspiration for me :)

**Comment by oderwat** [comment]
You may check out https://github.com/maragudk/gomponents which is something similar and makes use of the global scope.

I actually do not like dot imports a lot and it bytes itself with using other libraries where dot imports may make more sense (like https://github.com/go-jet/jet).
