### ISSUE TITLE
http.Client with basic auth ends up with a 401 response

### ISSUE THREAD

**Issue by omani** [maxence-charriere/go-app#614]
hi there,
when I use the http.Client with Transport digest basic authentication, the fetch method in my wasm app ends with a 401 Unauthorized and does not continue to use the basic auth provided in the **first** response of the the server (realm information, nonce, etc.).

any hints to why that is? if I do the same with curl from the cli (with flag -v for verbose) I see (in the headers) that the first response by the server is a 401, then the curl client makes another (second) request with the basic auth provided, which succeeds.

but in the wasm (in the browser) this behavor is completely different. it stops after the first response.

**Comment by omani** [comment]
update: I was talking about basic auth here. but to be correct, I am dealing with a digest authentication and not a basic authentication. this fact wont change anything regarding my problem. the problem is still the roundtrip that gets cut off after the very first response from the server. that response is needed for the client to figure out the nonce for the digest auth to be (then) able to make the second request with the correct authentication header. but the wasm client never reaches that state.

just wanted to make that clear.

**Comment by flyn-org** [comment]
Is this related to the caching of the application?

I have a similar problem, but with basic authentication. When my application performs an http.Get of a protected URL, the request immediately produces a 401. If I force the browser to reload the application and try again, the browser gets a 401, prompts me for a username and password, tries to load the URL again, and gets a 200.

I have experimented with the `Cache-Control` response header, thinking its presence in the protected resource might help, but this has not improved things.

**Comment by flyn-org** [comment]
I have continued to investigate this.

I thought perhaps replacing /api/login with /api/login/UUID, where UUID is a nonce would avoid caching the result and fix the authentication. Surprisingly this kludge did not solve the problem.

After that, I started investigating go-app's use of JavaScript service workers. What I found is that removing the definition of:
```
self.addEventListener("fetch", (event) => {
  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request);
    })
  );
});
```
from `pkg/app/gen/app-worker.js` and `pkg/app/scripts.go` solved the problem, albeit in a very kludgy way. I would not recommend doing this in practice, but it does start to show the source of the issue. Would it be worth checking `response` to see if it represents a 401 and firing off the fetch if it does? I suspect this would allow the authentication to proceed as the browser would be forced to interact with the server. On the other hand, I guess this would make the authenticated portion of the application unusable in disconnected mode.

**Comment by oderwat** [comment]
Removing the cache from the fetch will completely degrade the app. A maybe better way to do it is described here: https://thatemil.com/blog/2018/02/21/pwa-basic-auth/

In a W3C discussion I saw that handling the return codes could actually be a solution.

**Comment by flyn-org** [comment]
@maxence-charriere, this one might be worth keeping open.
