### ISSUE TITLE
can i use with database?

### ISSUE THREAD

**Issue by YankeeTube** [maxence-charriere/go-app#624]
can i use with database?
i want to use go-app server with together mysql. is it possible?

**Comment by maxence-charriere** [comment]
wasm runs on a web browser. I think you can only run WebSocket on this.
To use a DB, you'll have to do it on the server part and provide an API endpoint that you hit from wasm.

**Comment by YankeeTube** [comment]
Thanks

**Comment by oderwat** [comment]
a) One could create a bridge using a websocket from frontend to backend and connect the backend to the Database. I guess one also could create a transport extending the standard database package and plug MySQL behind it. This way it may be possible to use Gorm in the frontend. But it sounds like a lot of work and adds a lot of code in the frontend (wasm) which has some size (as part of the memory) limitations (after which everything breaks apart very badly).

b) I currently consider using https://github.com/rqlite/rqlite which has an HTTP API backend and is easily distributed and makes no use of the standard DB package(s). This can be a plus if you need to drop onto an HTTP endpoint anyways as you don't need another layer of abstraction. But only if the front end really needs such a close relationship to the database.

If Gorm is a "must" for the front end, I guess go-bro will simply not be feasible (nor anything else)

I am currently experimenting with using TinyGo in parallel to the normal Go Compiler to get smaller WASM files for more complex tasks. But even if one would have Gorm in there and such transparent Websocket to DB bridge, I fear this is not feasible.

You should think of go-app (Frontend) as "Frontend", kinda like VueJS or Vite or React, and so on. The only difference is that you don't write javascript and you commit to using the Go-App Engine and Framework to help you not to do everything by yourself.

**Comment by YankeeTube** [comment]
@oderwat wow so great answer!  It really helped me a lot! Thank you!
