### ISSUE TITLE
How to explain this behaviour (bug?)

### ISSUE THREAD

**Issue by oderwat** [maxence-charriere/go-app#628]
I ran into a problem which I didn't understand. However, I have two code examples to illustrate it (see below).

Both examples switch the visible component by using fragment navigation. When I use "Code1" and click through it, everything works when going 0,1,2, but when I go back 1,0, it will not render 0 again. It still will navigate (fragment updates), but the first component does not redraw. 2 and 1 still work when I navigate to them, but 0 will never render again. When I restart the app on `localhost:8000/#2` I get the same behavior but now with 2 being only rendered once.

Strangely this does not happen with "Code2". There I use different components for each "tab" (doing the same) and this works as I expect it.

When I put the `c.Tabs` initialisation from `OnMount` into `Render` in "Code1", this one also works. But then it would initialize them every render.

So what am I am doing wrong here or is this a bug?

#### Code1
```go
package main

import (
	"log"
	"net/http"
	"strconv"

	"github.com/maxence-charriere/go-app/v9/pkg/app"
)

type tab struct {
	app.Compo
	Text string
}

func (c *tab) Render() app.UI {
	return app.Div().Body(
		app.Div().Text(c.Text),
	)
}

type isolate struct {
	app.Compo
	Tabs    []app.UI
	Active  int
}

var _ app.Mounter = (*isolate)(nil)

func (c *isolate) OnMount(ctx app.Context) {
	c.Tabs = []app.UI{&tab{Text: "Content A"}, &tab{Text: "Content B"}, &tab{Text: "Content C"}}
}

func (c *isolate) OnNav(ctx app.Context) {
	url := ctx.Page().URL()
	idx, err := strconv.Atoi(url.Fragment)
	if err != nil {
		idx = 0
	}
	c.Active = idx
}

func (c *isolate) Render() app.UI {
	if c.Tabs == nil {
		return app.Div().Text("Unmounted")
	}
	return app.Div().Body(
		app.A().Style("padding", "5px").Href("#0").Text("Tab 0"),
		app.A().Style("padding", "5px").Href("#1").Text("Tab 1"),
		app.A().Style("padding", "5px").Href("#2").Text("Tab 2"),
		app.Div().Style("padding", "5px").Body(c.Tabs[c.Active]),
	)
}

func main() {
	app.Route("/", &isolate{})
	app.RunWhenOnBrowser()
	http.Handle("/", &app.Handler{
		Name:        "Isolate",
		Description: "Isolated functionality test",
	})
	if err := http.ListenAndServe(":8000", nil); err != nil {
		log.Fatal(err)
	}
}
```

#### Code 2
```go
package main

import (
	"log"
	"net/http"
	"strconv"

	"github.com/maxence-charriere/go-app/v9/pkg/app"
)

type tab0 struct {
	app.Compo
	Text string
}

func (c *tab0) Render() app.UI {
	return app.Div().Body(
		app.Div().Text(c.Text),
	)
}

type tab1 struct {
	app.Compo
	Text string
}

func (c *tab1) Render() app.UI {
	return app.Div().Body(
		app.Div().Text(c.Text),
	)
}

type tab2 struct {
	app.Compo
	Text string
}

func (c *tab2) Render() app.UI {
	return app.Div().Body(
		app.Div().Text(c.Text),
	)
}

type isolate struct {
	app.Compo
	Tabs    []app.UI
	Active  int
}

var _ app.Mounter = (*isolate)(nil)

func (c *isolate) OnMount(ctx app.Context) {
	c.Tabs = []app.UI{&tab0{Text: "Content A"}, &tab1{Text: "Content B"}, &tab2{Text: "Content C"}}
}

func (c *isolate) OnNav(ctx app.Context) {
	url := ctx.Page().URL()
	idx, err := strconv.Atoi(url.Fragment)
	if err != nil {
		idx = 0
	}
	c.Active = idx
}

func (c *isolate) Render() app.UI {
	if c.Tabs == nil {
		return app.Div().Text("uninitialised")
	}
	return app.Main().Body(
		app.A().Style("padding", "5px").Href("#0").Text("Tab 0"),
		app.A().Style("padding", "5px").Href("#1").Text("Tab 1"),
		app.A().Style("padding", "5px").Href("#2").Text("Tab 2"),
		app.Div().Style("padding", "5px").Body(c.Tabs[c.Active]),
	)
}

func main() {
	app.Route("/", &isolate{})
	app.RunWhenOnBrowser()
	http.Handle("/", &app.Handler{
		Name:        "Isolate",
		Description: "Isolated functionality test",
	})
	if err := http.ListenAndServe(":8000", nil); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by oderwat** [comment]
I think this original behavior is limiting. One can not replace a component with another one of the same types. One could create an additional "placeholder" component use this on the very first render so that the others update into this one. But that is complicated and not very elegant. In addition, it will not "mount" and "dismount" the copied components.

To me, it seems reasonable that the same instance of a component gets checked for updates by comparing the fields, but not two different ones. Still, I feel that I do not understand why it is implemented like this in the first place. Or is it really a bug or wrong behavior?

**Comment by maxence-charriere** [comment]
Since `tabs` are of the same type, every time you switch a `tab`, you actually update the first `tab` mounted. so when you navigate to the first one mounted back, it gets the latest updated value.

This is not a bug. When rendering, a new tree that represents a component and its children is generated. This tree is compared to the current one, and if a node has the same type, it gets updated rather than recreating a whole thing.

In your example, it does not play well because you are switching between the same type of elements.

Since your tab is one type with the same data in, some working solution would be to change the content from the tab component events, or just keep all your tab and display only one with a `Style("display", "none|block")`

**Comment by oderwat** [comment]
@maxence-charriere I actually did the latter one (keep em all visible) but I am not satisfied with that. I made a change to go-app which lets me modify the name of the component with an optional qualifier ("tab#1", "tab#2", "tab3"). Currently, I add this as a public field to the component and simply add it to the name in the name method. This way the component gets replaced and I get the mount and unmount events too. What do you think about this solution?

**Comment by oderwat** [comment]
What I actually want is a "mount point" where I can switch to another component without ever thinking about what type they are. I ran into this behavior while creating a tab component and it all worked well until I had two of the same components inside of it.

**Comment by oderwat** [comment]
So I solved my problem by creating a package I can use in our projects. It basically uses an alternating "in-between" component to force the embedded component to get replaced and also trigger dis-/mount events.

If you are curious you can check out: https://github.com/metatexx/go-app-pkgs/tree/master/mountpoint
