### ISSUE TITLE
TypeError: WebAssembly: Response has unsupported MIME type 'text/plain; charset=utf-8' expected 'application/wasm'

### ISSUE THREAD

**Issue by idc77** [maxence-charriere/go-app#641]
Getting this error
```
TypeError: WebAssembly: Response has unsupported MIME type 'text/plain; charset=utf-8' expected 'application/wasm'
```

```
package ui

import "github.com/maxence-charriere/go-app/v9/pkg/app"

type Home struct {
	app.Compo
}

func (h *Home) Render() app.UI {
	return app.Html().Body(
		app.Head().Body(
			app.Meta().Name("charset").Content("utf-8"),
		),
		app.Body().Body(
			app.H1().Text("Hello World"),
		),
	)

}
```

```
package cmd

import (
	"net/http"

	"mypackagepath/ui"
	"github.com/maxence-charriere/go-app/v9/pkg/app"
	"github.com/spf13/cobra"
)

// uiCmd represents the ui command
var uiCmd = &cobra.Command{
	Use:   "ui",
	Short: "",
	RunE: func(cmd *cobra.Command, args []string) error {
		app.Route("/", new(ui.Home))
		app.RunWhenOnBrowser()
		http.Handle("/", &app.Handler{
			Author:       "A name",
			Description:  "domain.tld is an URL shortener service",
			LoadingLabel: "Yo! Wait up, it's loading...",
			Name:         "Some Name",
			Title:        "domain.tld - shorturl service",
			Version:      "1",
		})

		return http.ListenAndServe(":7890", nil)
	},
}

func init() {
	rootCmd.AddCommand(uiCmd)
}
```

**Comment by idc77** [comment]
never mind, I didn't read to the end of the getting started

**Comment by ocdtrekkie** [comment]
Sadly, I don't see what you found at the end of the getting started which solved this for you! :(

**Comment by ocdtrekkie** [comment]
Oh. I did do that part.

**Comment by oderwat** [comment]
Do you still get the same error as he got? Or why did you end up here?

**Comment by ocdtrekkie** [comment]
So my browser appears to be getting a 404 not found. (And hence is returning MIME type text/html.)

I am *very very new* to writing Go, but I'm pondering... what in the getting started is actually serving the /web directory?

**Comment by oderwat** [comment]
There is also https://github.com/mlctrez/goappcreate by @mlctrez which uses another approach (the usual make instead of mage and gin framework instead of the chi router). I do not have our "watcher" included in my first example (the reloading because that's a lot of proprietary code now). In the go-nats-app there is also the back- and front end communication solved. But it is using NATS for that, which is a very cool and powerful but unusual approach. Before that, we were using "Twirp" and a bit web sockets and standard REST. The NATS combines this and makes stuff effortless to write and understand.

**Comment by ocdtrekkie** [comment]
Hmm... Okay, so I am trying to serve this in an abnormal environment (a Sandstorm.io dev sandbox, as the case is), and I may have to go back and ask someone else to explain this oddity for me, but I'll explain here unless this provides some context that's useful.

My app is built at /opt/app/app and my WASM is at /opt/app/web/app.wasm, so everything *should* work out of the box, I think, but as I said, I'm getting a 404 on the app.wasm, which is weird. However, I was reading about some of the other stuff in Docs, and was pondering the ability to config where static resources are, and added `Resources:   app.LocalDir("/opt/app/web"),` even though, of course, that's the default relative location anyways?

![image](https://user-images.githubusercontent.com/4399499/206180753-57a9c9ca-0a5b-4c74-8e8e-a725555d9bb7.png)

That loaded me a Hello World! But also did some weird stuff with the loading screen:

![image](https://user-images.githubusercontent.com/4399499/206180462-41fd3767-8107-48bc-805d-7f41b82e5487.png)

**Comment by oderwat** [comment]
I had some strange things happen to me too when using `app.LocalDir()`. In fact, I did not really understand how that works at all. It may help to check what paths are used from the browser and fiddling with the static resources option. If you do not need a backend, you may get happy by just creating a [static version of the site](https://go-app.dev/github-deploy).

**Comment by ocdtrekkie** [comment]
Where is "prefix" coming from in this context?

So the reason local storage doesn't work in Sandstorm is because we spawn apps on a randomized subdomain every time you open them. Local storage isn't necessarily blocked, but the chances the app will ever be at that origin again is statistically impossible, so it effectively doesn't persist for us. This is good anyways: We want apps to store on the server so that everything is cross-device.

**Comment by oderwat** [comment]
But... having this kind of subdomain actually prevents one of Go-App's main functionality: Installation as an App on the user's phone or desktop. Which is the only reason for us to use it. Loading such a large Wasm code every time I open the app again does not make sense :). So, I wonder why you want to use Go-App for that use case?

**Comment by ocdtrekkie** [comment]
Yeah, the app is served at the root of the subdomain, and the web folder is in the same directory on the server as the server binary.

So server is listening at http://subdomain/ and 404ing trying to load the wasm at http://subdomain/web/app.wasm, which seems like where it should be.

**Comment by ocdtrekkie** [comment]
It's entirely possible it does not make sense to use go-app here!

**Comment by oderwat** [comment]
Can you do a `log.Println(os.Getwd())` (and watch the output somewhere) in `func main()` to verify the current working directory is where the "web" folder is?

**Comment by ocdtrekkie** [comment]
It'll be a bit until I can check, but you might be on to something. I think we launch /opt/app/app, but don't cd to /opt/app first.

**Comment by oderwat** [comment]
You can use `https://pkg.go.dev/os#Executable` in that case in your app.

**Comment by ocdtrekkie** [comment]
I just did a `cd` in the script that launches it. All good, that was it. Thanks for talking me through it!
