### ISSUE TITLE
Scroll bar size on Documentation pages

### ISSUE THREAD

**Issue by simulot** [maxence-charriere/go-app#642]
Hi,

Using go-app.dev reference page on chromium based desktop browser is not practical because of the width of scroll bar.It's too small to be dragged with a mouse.  

![image](https://user-images.githubusercontent.com/5980377/141647211-e2a29733-ed52-49f5-956a-fc91e488a80a.png)

Left: Firefox
Right: Chromium

I'm using Linux, but this is same on Windows.
Thanks for this wonderful tool!

**Comment by simulot** [comment]
The scroll bar is too thin to scroll the reference list. Could you enlarge it?

**Comment by maxence-charriere** [comment]
Documentation will take another form in a near future.
