### ISSUE TITLE
Prerender doesn't work

### ISSUE THREAD

**Issue by YankeeTube** [maxence-charriere/go-app#645]
![image](https://user-images.githubusercontent.com/34546950/142231902-e44699a7-fc63-4b8d-b324-6a3c7202e26b.png)
![image](https://user-images.githubusercontent.com/34546950/142231942-e1e62a37-b733-4ceb-9a63-f713e4eadd00.png)

To be exact, it works, but it does not maintain data when rendering is completed.  

this is my OnPreRender Code
```go
func (p *IndexPage) OnPreRender(ctx app.Context) {
	var game Game
	resp, err := http.Get("http://127.0.0.1:3333/api")
	if err != nil {
		log.Fatalln("connect failed to API Server")
	}
	defer resp.Body.Close()
	json.NewDecoder(resp.Body).Decode(&game)
	p.game = game.Name
	app.Log("game is ", game.Name)  // print Success!
}
```

and this is my Render code
```go
func (p *IndexPage) Render() app.UI {
	app.Log("after test is ", p.game) // print Success!
	return app.Div().Class("g-app").Body(
		&organisms.AppHeader{},
		app.H1().Class("test").Text(p.game),
	)
}
```

**Comment by maxence-charriere** [comment]
It does not maintain data because the pretender is only to generate html that is readable by robots for seo purpose. 

The pretendering is replaced as soon as the wasm is loaded.

**Comment by YankeeTube** [comment]
If then, 

1. Is there any way to keep the data of the onPreRender?

2. In order to maintain the results requested by the onPreRender, do we have to make a total of two requests, the Render and the onPreRender?

3. Can I use fasthttp or fiber instead of net/http?

**Comment by maxence-charriere** [comment]
1 no, this happen server side et only generate raw html that is deleted a soon a wasm loads.

2 pre render have nothin to do with normal rendering. Se it like its thing on server side to generate html readable by robots.

3 you can use any go library or js library

**Comment by maxence-charriere** [comment]
For 3 you have to try if it is a go library. Http wrap javascript calls i think
