### ISSUE TITLE
Can I use "HMR" in "go-app"?

### ISSUE THREAD

**Issue by YankeeTube** [maxence-charriere/go-app#646]
The process of re-executing every time I work on the UI is more cumbersome than I thought, so is there a way to use a method such as Hot Moudle Reload?

**Comment by ItsVoltz** [comment]
I use https://github.com/pojntfx/html2goapp and work on my components / pages in HTML and then I will convert them to go that way I can play around with a live html server and then convert them when I'm ready to integrate into the app

**Comment by oderwat** [comment]
I wrote a `magefile` ([Mage](https://magefile.org/)) which checks dependencies, recompiles, and restarts the server when we change code. As we need an "update app" mechanism for the app anyway (using head polling or a websocket) it then can auto-reload the application to refresh the page. I also wrote (our own) html2goapp tool but that is only used rarely when creating a new skeleton for a component/page and is especially useful for complex SVG elements (hence my PR for custom elements).
