### ISSUE TITLE
Is there a way to access the current page url in the render function?

### ISSUE THREAD

**Issue by YankeeTube** [maxence-charriere/go-app#647]
Is there a way to access the current page url in the render function?

I want to access the URL() from the render function.

**Comment by oderwat** [comment]
You could set up an `OnNav()` Handler in the component and store the URL or parts of it into the component which you are rendering. So it will be updated and available for `Render()`.

**Comment by YankeeTube** [comment]
@oderwat  Thank you for answering first.


I also set OnNav, but before the update occurs, I want to process it.

If you check the component's lifecycle, Nav operates after mount, and then Nav operates after Render, right?

**Comment by oderwat** [comment]
You will always get a `Render()` before everything else. You need to set up the component that this is possible, for example checking if the path in the component still is nil.

**Comment by oderwat** [comment]
This shows the order of actions (using dbg from our [dbg](https://github.com/metatexx/go-app-pkgs/tree/master/dbg) package. Ignore the audio context warning.

![image](https://user-images.githubusercontent.com/719156/142765258-aa2986c0-2a9c-41ea-9e97-012525259553.png)

**Comment by YankeeTube** [comment]
@oderwat 
Thank you. It wasn't the result I wanted, but it helped me a lot!
