### ISSUE TITLE
Styles is not loaded when moving to tag a.

### ISSUE THREAD

**Issue by YankeeTube** [maxence-charriere/go-app#648]
Each page needs to be loaded with a different css file.
However, if you approach it directly, do the normal operation, and if you approach it with the anchor tag, it will not be called.

**Comment by oderwat** [comment]
You lost me :)

**Comment by oderwat** [comment]
I guess you want to use different stylesheets when the navigation changes. 

I think you can add a component that will have an `OnNav()` and changes the stylesheet to what you want. Probably by changing a linked source in the head area of the page. I did not try it myself and have no time right now. But it's an interesting problem I look into for myself soon.
