### ISSUE TITLE
can i use custom app-worker.js?

### ISSUE THREAD

**Issue by YankeeTube** [maxence-charriere/go-app#650]
I want to attach a service worker separately and intercept the fetch, but it keeps being ignored because of app-worker.js.

Also... app-worker.js keeps erasing my separate cache. This can be added to appHandler, but I hope you can get an array that can handle exceptions.

**Comment by maxence-charriere** [comment]
You can override the endpoint and provide your own. Though a lot of what make goapp work belong to this file. You will have to copy paste what is already here, add your stuff and handle version generation by yourself, otherwise your app will never get updated by the browser.

**Comment by YankeeTube** [comment]
Well, I don't think it's a good solution, but when I re-write and register app-worker.js, they both run. Thank you!
