### ISSUE TITLE
Question about security

### ISSUE THREAD

**Issue by ItsVoltz** [maxence-charriere/go-app#651]
Is it safe for me to write my backend with the go-app frontend as long as I dont expose anything sensitive to the client or should I write an API and have my go-app query that?

**Comment by maxence-charriere** [comment]
What happend in the backend stays in the backend. The goapp handler is like any handler. It runs on server side. The app you see in the browser runs on the browser, the handler have no idea about what is happening. 

You can safely have your api next to the goapp handler. It will be as safe as you design it.

**Comment by ItsVoltz** [comment]
> What happend in the backend stays in the backend. The goapp handler is like any handler. It runs on server side. The app you see in the browser runs on the browser, the handler have no idea about what is happening.
> 
> You can safely have your api next to the goapp handler. It will be as safe as you design it.

Awesome so as long as no sensitive data is in the go-app handlers its never exposed to the client? I've been looking for a library in pure go for this exact purpose and am excited to work with it, thank you for the near instant response!
