### ISSUE TITLE
Cookie is not included when requesting http on go-app.

### ISSUE THREAD

**Issue by YankeeTube** [maxence-charriere/go-app#653]
this is my code
```go
client := &http.Client{}
baseURL := fmt.Sprintf("http://localhost:3333%s", url)

req, err := http.NewRequest("GET", baseURL, nil)
if err != nil {
  fmt.Println(err)
  return
}

req.Header.Set("Cookie", "test=11; test2=zz")
resp, err := client.Do(req)
```

but request header not set cookie

There is no problem when requesting api directly from postman or new tab.

**Comment by maxence-charriere** [comment]
I think this is a problem related to `net/http` and not go-app.

I don't think this compiles:
```go
req.Header.Set("Cookie", "test=11; test2=zz")
```
=> https://pkg.go.dev/net/http#Header.Set

Did you try with something like this:
```go
req.Header.Add("Cookie", &http.Cookie{Name: "test", Value: "11"}).String())
req.Header.Add("Cookie", &http.Cookie{Name: "test2", Value: "zz"}).String())
```

**Comment by YankeeTube** [comment]
i still issue.
and I did it using js fetch, but I think the same problem is coming out.

Do you have the same phenomenon? @maxence-charriere

**Comment by mlctrez** [comment]
The http client in wasm is backed by the javascript fetch api.  The js fetch api restricts which headers can be manipulated.  See https://developer.mozilla.org/en-US/docs/Web/API/Headers and the paragraph mentioning forbidden header names.

Go appears to hard code the fetch api options to credentials=include
https://github.com/golang/go/blob/master/src/net/http/roundtrip_js.go#L71

You may want to check out https://github.com/marwan-at-work/wasm-fetch  which provides for a bit more flexability

**Comment by YankeeTube** [comment]
Thanks Everyone...!
I found a problem.
I was operating the api server using fiber framework.

However, although it is normal in net/http, we found a problem that cookie is not transmitted in fiber.

**Comment by YankeeTube** [comment]
I thought this was a problem with fiber, but the reality was not.  

In order for net/http to communicate with cors in WASM, the following option was required for the request header.
```go
req, err := http.NewRequest("GET", baseURL, nil)
req.Header.Add("js.fetch:credentials", "include")
```  


After that, if you check the request again on the browser's network tab, you can see the request including cookie normally!
I hope it helped someone!
