### ISSUE TITLE
navigation issue

### ISSUE THREAD

**Issue by YankeeTube** [maxence-charriere/go-app#656]
Although the external link is target `_self`,
Both the `anchor tag(app.A())` or `navigate(ctx.Navigate)` and `navigatTo(ctx.NavigateTo)` open as new tabs.

Is there a way to solve this? @maxence-charriere  @oderwat

**Comment by oderwat** [comment]
I think all of the external URLs will be opened with `window.open()`. But you can just use `app.Window().Get("location").Set("href", "https://www.google.de/")` instead.

**Comment by maxence-charriere** [comment]
All url that does not belong to your current host are opened on a new tab/window.

you can override this by setting a specific url in Handler.InternalURLs
