### ISSUE TITLE
How can I set class on the html or body element?

### ISSUE THREAD

**Issue by ItsVoltz** [maxence-charriere/go-app#657]
I have a page that I would like to set a class on the html and body how would I go upon doing so, I have written into the component an html and body element which causes it to set the classes on the auto-generated body and html elements but it also generates its own html and body elements.

**Comment by oderwat** [comment]
This is why I made this: https://github.com/maxence-charriere/go-app/pull/629 which is (as the other PRs in our version of go-app for some time now)

**Comment by ItsVoltz** [comment]
> 

Another question is there a way to use other components in my main component, for example say I want a bunch of smaller components and I would like to then bring them into the main page to make the actual page component smaller can I do this?

**Comment by oderwat** [comment]
Yes, or declare it as part of the parent component so you can initialize them and not recreate them with every call to render. You have to realize that "Render()" of a component is called for every update which may be very often.

**Comment by maxence-charriere** [comment]
You currently can’t custom the body or the HTML tag. 

Sorry @oderwat for your PR, I wanted to take a look more on this but got very busy between work and health.

I ll take another look soon.

**Comment by oderwat** [comment]
@maxence-charriere That is fine and health is most important anyway!

**Comment by maxence-charriere** [comment]
Thanks for being so helpful in all the issues @oderwat.

**Comment by maxence-charriere** [comment]
What is the scenario where we want to put a class on the `html` element?

**Comment by maxence-charriere** [comment]
Hey folks, just pushed a new version that fix this.
see the release => https://github.com/maxence-charriere/go-app/releases/tag/v9.3.0
