### ISSUE TITLE
Passing data between all components / Middleware

### ISSUE THREAD

**Issue by ItsVoltz** [maxence-charriere/go-app#659]
I was curious about some sort of middleware with the app, sorry for all the issue posts I have created recently, really love the package and its fun to work with so trying to learn as much as I can with it. For example say I want authenticated end points say like `/dashboard` you are required to be login how would make it so if you go to any of these authenticated endpoints check for a session token if it exists populate a user field and then if they aren't logged in redirect to the login page. Would I just use pre-render, and if so do I have to grab the session in every PreRender for every authenticated page, obviously some sort of helper func to make some sort of middleware in pre-render might work but wanted to hear someone else's opinion that has worked with the library longer and see if i'm over thinking it.

**Comment by maxence-charriere** [comment]
That is a good question since prerender does not give access to the http request.

Right now you have to do auth stuff like an app, dealing with http client.

This actually something that could be useful to have. I ll think about a solution to access the http request.

**Comment by ItsVoltz** [comment]
> That is a good question since prerender does not give access to the http request.
> 
> Right now you have to do auth stuff like an app, dealing with http client.
> 
> This actually something that could be useful to have. I ll think about a solution to access the http request.

What would be the best way for me to check a user authentication and pass it around my different pages?

**Comment by ItsVoltz** [comment]
Also what would a good way be to parse a form? I for example I have an OnSubmit but my callback never works as it refreshes the page to do a request.

**Comment by oderwat** [comment]
You should use `event.PreventDefault()` on the event parameter of the event handler you define. I do not need parsing of forms in my apps, because the data is already in the component. But if you don't have that you need to access the form data like with any javascript program using the javascript bridge methods (Call/Get/Set) to read the data from the DOM.

**Comment by ItsVoltz** [comment]
> You should use `event.PreventDefault()` on the event parameter of the event handler you define. I do not need parsing of forms in my apps, because the data is already in the component. But if you don't have that you need to access the form data like with any javascript program using the javascript bridge methods (Call/Get/Set) to read the data from the DOM.

Awesome thank you! Do you happen to have discord or anything I can message you on instead of github issues, you've been a great help

**Comment by mar1n3r0** [comment]
@ItsVoltz Use a httpsOnly cookie created on the backend and stored on the frontend. You can check if it's stored in the browser at any given time without making a request for every page.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

**Comment by ItsVoltz** [comment]
> @ItsVoltz Use a httpsOnly cookie created on the backend and stored on the frontend. You can check if it's stored in the browser at any given time without making a request for every page.
> 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

Already got this working, any idea how to get captchas to properly work https://github.com/maxence-charriere/go-app/issues/671 seems my issues get abandoned fast
