### ISSUE TITLE
HTML templating and nesting components in v9

### ISSUE THREAD

**Issue by diamondburned** [maxence-charriere/go-app#660]
I've been reading the documentation back and forth, and while I have found
`app.Raw` for rendering raw HTML from a component, I still haven't seen a way to
do so by templating.

I've been considering using `html/template` in combination with this, but
`html/template` won't handle rendering `app.Compo` for me. I expected that to
mean I won't get the nice reactivity that using `app.Compo` would.

It seems like in previous versions of `go-app`, it was able to just do

```go
type Compo struct {
	app.Compo
	Main *other.Compo
}

func (c *Compo) Render() string {
	return `
		<div>
			{{ .Main }}
		</div>
	`
}
```

But I don't think this would work at all in v9 with either `html/template` or
only `app.Raw` by itself. Reading `app.Raw`'s code, it seems to treat the given
HTML string literally and doesn't do any prior templating. `html/template` would
of course not understand what an `app.Compo` is in v9.

How should I get something like this working if neither `html/template` nor
`app.Raw` can do it? Is it even possible at all to do something like this, or am
I forced to use the HTML element constructors?

**Comment by maxence-charriere** [comment]
Templating is not supported. I was using it in former go-app versions and it was too hard to maintain.
It also add a considerable size to the go assembly binary.
