### ISSUE TITLE
style image update

### ISSUE THREAD

**Issue by YankeeTube** [maxence-charriere/go-app#662]
Style image The image keeps blinking due to the problem of continuing to request due to the operation of the update.

In the case of dynamic images, it is neat to apply it as a style tag, but is there a way to solve this problem? 
@maxence-charriere  @oderwat 

I tried making it into a child component, but the problem continued.

**Comment by YankeeTube** [comment]
The biggest reason why it moves like this is...
Whenever items set as Style are updated, the order is not guaranteed.

Because of this, the browser performs a reflow operation and mistakenly requests it for a new image.

**Comment by maxence-charriere** [comment]
Not sure if this is still around with current version. Feel free to reopen if it is the case.
