### ISSUE TITLE
Can anyone give me a proper example for client server communication

### ISSUE THREAD

**Issue by ItsVoltz** [maxence-charriere/go-app#666]
Can anyone give me a proper example for communicating with the server on the client and transferring data, setting cookies etc. And an easy way to share data across components. I think I'm just overthinking it and want to see how other people may do it.

**Comment by maxence-charriere** [comment]
Hello there.

There is an example in the docs here: https://go-app.dev/concurrency#async

for the server part I redirect you to the Golang net/http package.

hope it helps.

**Comment by ItsVoltz** [comment]
Thank you max, it does a lot!
