### ISSUE TITLE
Documentation issue in Architecture page

### ISSUE THREAD

**Issue by stephanwesten** [maxence-charriere/go-app#667]
There is an example line like this:

app.Div().Body

I find this confusing as I expect there to be one Body element containing all the html elements. From w3schools for example:

 The <body> element contains all the contents of an HTML document, such as headings, paragraphs, images, hyperlinks, tables, lists, etc.

Note: There can only be **one** <body> element in an HTML document.

A div containing a body should not be possible. 

Btw i like what you have done. 

A suggestion; include an example how to deploy to a Cloudflare worker, alleviates the need for a server. You can serve with a few Javascript lines a PWA. 
They also support wasm. There is also back-end storage, so you could perhaps write an entire application serverless with a PWA in Go…

**Comment by maxence-charriere** [comment]
Hey, thanks for the feedback.

The body notation was inspired by swift UI. I have been here for a while now and changing it will likely mess with people's codebase. I don't feel it is worth changing.

I never used Cloudfare worker. Totally up to add one but I have to try it. Would also be open to adding an article by someone who already used it.
