### ISSUE TITLE
can i use child component onclick?

### ISSUE THREAD

**Issue by YankeeTube** [maxence-charriere/go-app#668]
First of all, happy new year! @oderwat @maxence-charriere 

I have button components classified as atoms according to the ATOMIC design.
But when you use this for the top components, 
&atoms.Button{} Is there a way for parents to use onClick?

example
```go
Body(
  &atoms.Button{}.OnClick(handler)
)
```

Right now, I have no choice but to deliver the action name and call the action.

**Comment by oderwat** [comment]
Our components just use callbacks and add "onClick" in the render function if needed. You may want to use events and implement them in the atoms. I just think this is adding unwanted complexity. But maybe @maxence-charriere has an idea how to do it.

**Comment by maxence-charriere** [comment]
Happy new year.

See your parent component as a reusable interface. If you want to expose let say a OnClick on this, you ll have to declare a func with the wanted signature in the component fields and plug it to the underlying HTML element onclick.

**Comment by YankeeTube** [comment]
@maxence-charriere 
Um... I don't understand what you mean. Can you show me the example code?

**Comment by YankeeTube** [comment]
oh i got it Thank u!
it was so fantastic...! @maxence-charriere 

I'll write an example for someone like me and close the issue.



```go
// child Component

type Button struct {
  app.Compo
  ClickHandler app.Event
}

func (h *Button) Render() app.UI {
  return app.Button().OnClick(h.ClickHandler)
}
```


```go
// parent Component
type Container {
  app.Compo
}

func (h *Container) Render() app.UI {
  return app.Div().Body(
    &Button{
      ClickHandler: h.buttonClickHandler,
    }
  )
}

func (h *Container) buttonClickHandler(ctx app.Context, e app.Event) {
  fmt.Println("Click!")
}
```
