### ISSUE TITLE
Recaptcha

### ISSUE THREAD

**Issue by ItsVoltz** [maxence-charriere/go-app#671]
Hello. anyone know about getting recaptcha to properly work?

I have it setup to prompt user with a captcha after they click register like so:
https://streamable.com/4if31l

However whenever the captcha submits the form it completely ignores my form submission handler:
```go
func (c *register) OnCaptchaComplete(ctx app.Context, e app.Event) {
	e.PreventDefault()
	print("Captcha complete")
}
```

here is the snippet for the element
```go
app.Div().Class("flex justify-center").Body(
	app.Form().
	ID("register-captcha-form").
	OnSubmit(c.OnCaptchaComplete, nil).
	Body(
	&components.Captcha{Callback: "registerCaptchaCB"}),
	),
),
```

Is there a way to easily prevent the captcha from submitting normally and passing in the response and properly send to my handler with the recaptcha response so I can use the data to build a request to the api?

I know I can just read the query value for the g-recaptcha-response but is there anyway I can prevent recaptcha from submitting a post / get request to the form action?

**Comment by maxence-charriere** [comment]
Look like it also require to return false => https://stackoverflow.com/questions/3350247/how-to-prevent-form-from-being-submitted

but that is currently not possible with go-app. I ll have to think of how to do this. 

In the meantime you could register a func manually to an event handler with the js interopt.

**Comment by ItsVoltz** [comment]
> In the meantime you could register a func manually to an event handler with the js interopt.

How do you mean?

**Comment by ItsVoltz** [comment]
> Look like it also require to return false => https://stackoverflow.com/questions/3350247/how-to-prevent-form-from-being-submitted
> 
> but that is currently not possible with go-app. I ll have to think of how to do this.
> 
> In the meantime you could register a func manually to an event handler with the js interopt.

So I have callback for the function like so, return false doesnt actually do anything to prevent the recaptcha resubmitting the form, so I had to call e.preventDeafault() to get what I want to work however then it prevents my go-app callback from being called. Anyway to work around this?

Also have you thought about making easy way to create middleware for all of the routes, for example say I have an authenticated list of routes and wanted to pass an authenticated middleware to run on all of them to set a user object in all those routes.
```js
window.registerCaptchaCB = function(token) {
    $("#register-captcha-form").submit(function (e) {
        e.preventDefault()
    });
    console.log("CAPTCHA GO BRR")
    console.log("Captcha token: " + token);
    return false
};
```

**Comment by ItsVoltz** [comment]
Any ideas?

**Comment by ItsVoltz** [comment]
Still nothing??

**Comment by maxence-charriere** [comment]
Something like this:

```go
type register struct {
	app.Compo

	closePreventSubmit func()
}

func (c *register) OnMount(ctx app.Context) {
	preventSubmit := app.FuncOf(func(this app.Value, args []app.Value) interface{} {
		event := app.Event{Value: args[0]}
		event.PreventDefault()
		return false
	})

	form := app.Window().GetElementByID("register-captcha-form")
	if !form.Truthy() {
		panic("form element not found")
	}
	form.Call("addEventListener", preventSubmit)

	c.closePreventSubmit = func() {
		form.Call("removeEventListener", preventSubmit)
		preventSubmit.Release()
	}
}

func (c *register) OnDismount() {
	c.closePreventSubmit()
}

func (c *register) Render() app.UI {
	return app.Div().
		Class("flex").
		Class("justify-center").
		Body(
			app.Form().
				ID("register-captcha-form").
				Body(
					&components.Captcha{Callback: "registerCaptchaCB"},
				),
		)
}

```

**Comment by ItsVoltz** [comment]
> Try something like this:
> 
> ```go
> type register struct {
> 	app.Compo
> 
> 	closePreventSubmit func()
> }
> 
> func (c *register) OnMount(ctx app.Context) {
> 	preventSubmit := app.FuncOf(func(this app.Value, args []app.Value) interface{} {
> 		event := app.Event{Value: args[0]}
> 		event.PreventDefault()
> 		return false
> 	})
> 
> 	form := app.Window().GetElementByID("register-captcha-form")
> 	if !form.Truthy() {
> 		panic("form element not found")
> 	}
> 	form.Call("addEventListener", preventSubmit)
> 
> 	c.closePreventSubmit = func() {
> 		form.Call("removeEventListener", preventSubmit)
> 		preventSubmit.Release()
> 	}
> }
> 
> func (c *register) OnDismount() {
> 	c.closePreventSubmit()
> }
> 
> func (c *register) Render() app.UI {
> 	return app.Div().
> 		Class("flex").
> 		Class("justify-center").
> 		Body(
> 			app.Form().
> 				ID("register-captcha-form").
> 				Body(
> 					&components.Captcha{Callback: "registerCaptchaCB"},
> 				),
> 		)
> }
> ```

![image](https://user-images.githubusercontent.com/29076540/148694266-b9da9e95-436f-4403-a916-e63e6cc1d549.png)

Fixed this by doing 
```go 
form.Call("addEventListener", "submit",  preventSubmit)
```

And after changing my form up a bit I got it to work. Thank you so much!

**Comment by maxence-charriere** [comment]
Oops, ^^ yep i forgot de event :D.
Glad it worked.

**Comment by ItsVoltz** [comment]
> Oops, ^^ yep i forgot the event :D.
> Glad it worked.

What would be the proper way to populate component data on an event I have a form submission handler but whenever I get an error and set the error string in the component, it can’t be set after. I’ve tried creating async tasks and dispatch but it will only update the first time and no others change and update the component.

**Comment by maxence-charriere** [comment]
does your components data are exported or non exported?

**Comment by ItsVoltz** [comment]
> does your components data are exported or non exported?

Non exported but the handler is a receiver to the component

**Comment by maxence-charriere** [comment]
Do you have so code to share about what you are trying to do? Would help me understand your problem.

**Comment by ItsVoltz** [comment]
> Do you have some code to share about what you are trying to do? It would help me understand your problem.

```go
func (c *register) OnRequestRegister(ctx app.Context, e app.Event) {
	e.PreventDefault()
	ctx.Async(func() {
		errStr := ""

		if len(c.username) < 3 || len(c.username) > 26 {
			errStr = "Username must be 3-26 characters in length."
		}

		if strings.Contains(c.username, " ") {
			errStr = "Username may not contain spaces."
		}

		if len(c.password) > 128 {
			errStr = "Password may not be greater than 128 characters."
		}

		if len(c.password) < 6 {
			errStr = "Password must be at least 6 characters in length."
		}

		if c.password != c.confPassword {
			errStr = "Passwords do not match."
		}

		ctx.Dispatch(func(ctx app.Context) {
			c.error = errStr
		})

		if errStr == "" {
			token := app.Window().Get("token").String()
			app.Log("CAPTCHA RESPONSE:", token)
		}
	})
}
```

Here is my latest code from me just testing I have tried a bunch of stuff tho.

Here is my component structure:
```go
type register struct {
	app.Compo

	closePreventSubmit func()

	username, password, confPassword, error string
	user    responses.User // populates if they are logged in and redirects to dashboard
}
```

**Comment by maxence-charriere** [comment]
To what `OnRequestRegister` is subscribed to?

**Comment by ItsVoltz** [comment]
> To what `OnRequestRegister` is subscribed to?

OnSubmit for the registration form

**Comment by maxence-charriere** [comment]
Your code seems correct to me (note that don't need to async or dispatch here).

Are you sure the submit event is launched each time you click on submit?

> Is there a better way for me to do form validation?

I would call the checker function each time a form input changes.
For the captcha, I would try to find a way to manually trigger it and check on the result.

**Comment by ItsVoltz** [comment]
> Your code seems correct to me (note that don't need to async or dispatch here).
> 
> Are you sure the submit event is launched each time you click on submit?
> 
> > Is there a better way for me to do form validation?
> 
> I would call the checker function each time a form input changes. For the captcha, I would try to find a way to manually trigger it and check on the result.

Hmm any suggestions, and I have but its weird whenever I change the error message even when I tried to have each inout have its only error label, it would only allow me to change the value once and then it gets stuck at whatever the previous value was set to the variable. Even printing it thinking the UI isnt getting updated was still the same.

**Comment by maxence-charriere** [comment]
Do you update username and password each time you change the input?

**Comment by ItsVoltz** [comment]
> Do you update `username` and` password` each time you change the input?

Yes

**Comment by maxence-charriere** [comment]
can i see your render?

**Comment by ItsVoltz** [comment]
> can i see your render?

```go
func (c *register) Render() app.UI {
	return app.Div().
		Class("min-h-full flex flex-col justify-center py-12 sm:px-6 lg:px-8").
		Body(
			app.Div().
				Class("sm:mx-auto sm:w-full sm:max-w-md").
				Body(
					app.H2().
						Class("mt-6 text-center text-3xl font-extrabold text-gray-300").
						Body(
							app.Text("Sign up"),
						),
					app.P().
						Class("mt-2 text-center text-sm text-white").
						Body(
								app.Text("Already have an account? "),
								app.A().
									Href("login").
									Class("font-medium text-red-900 hover:text-red-800").
									Body(
										app.Text("Click here to sign in"),
									),
						),
				),
		app.Div().
			Class("mt-8 sm:mx-auto sm:w-full sm:max-w-md").
			Body(
				app.Div().
					Class("bg-gray-800 py-8 px-4 shadow sm:rounded-lg sm:px-10").
					Body(
						app.Form().
							ID("register-form").
							Class("space-y-6").
							OnSubmit(c.OnRequestRegister, nil).
							Body(
								app.If(c.error != "", &components.Alert{
									Message: c.error,
									Type:    components.AlertError,
								}),
								app.Div().
									Body(
										app.Label().
											For("username").
											Class("block text-sm font-medium text-gray-500").
											Body(
												app.Text("Username"),
											),
										app.Div().
											Class("mt-1").
											Body(
												app.Input().
													ID("username").
													Value(c.username).
													Name("username").
													Type("text").
													AutoComplete(true).
													AutoFocus(true).
													Required(true).
													Class("appearance-none block w-full px-3 py-2 border border-gray-600 rounded-md shadow-sm placeholder-gray-400 text-gray-300 bg-gray-700 focus:outline-none focus:ring-red-900 focus:border-red-900 sm:text-sm").
													OnChange(c.ValueTo(&c.username)),
											),
									),
								app.Div().
									Body(
										app.Label().
											For("password").
											Class("block text-sm font-medium text-gray-500").
											Body(
												app.Text("Password"),
											),
										app.Div().
											Class("mt-1").
											Body(
												app.Input().
													ID("password").
													Value(c.password).
													Name("password").
													Type("password").
													Required(true).
													Class("appearance-none block w-full px-3 py-2 border border-gray-600 rounded-md shadow-sm placeholder-gray-400 text-gray-300 bg-gray-700 focus:outline-none focus:ring-red-900 focus:border-red-900 sm:text-sm").
													OnChange(c.ValueTo(&c.password)),
											),
									),
								app.Div().
									Body(
										app.Label().
											For("confpassword").
											Class("block text-sm font-medium text-gray-500").
											Body(
												app.Text("Confirm Password"),
											),
										app.Div().
											Class("mt-1").
											Body(
												app.Input().
													ID("confpassword").
													Value(c.confPassword).
													Name("confpassword").
													Type("password").
													Required(true).
													Class("appearance-none block w-full px-3 py-2 border border-gray-600 rounded-md shadow-sm placeholder-gray-400 text-gray-300 bg-gray-700 focus:outline-none focus:ring-red-900 focus:border-red-900 sm:text-sm").
													OnChange(c.ValueTo(&c.confPassword)),
											),
									),
								app.Div().Class("flex justify-center py-2").Body(
									&components.Captcha{Callback: "registerCaptchaCB"},
								),
								app.Div().
									Body(
										app.Div().
											Body(
												app.Button().
													Type("submit").
													Class("w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-red-900 hover:bg-red-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-800").
													Body(
														app.Text("Sign up"),
													),
											),
									)),
					), 
					),
		)
}
```

**Comment by maxence-charriere** [comment]
I'm not sure about what is wrong, I try to reproduce this but seems to work for me:
```go
type register struct {
	app.Compo

	closePreventSubmit func()
	name               string
	err                string
}

func (c *register) OnMount(ctx app.Context) {
	preventSubmit := app.FuncOf(func(this app.Value, args []app.Value) interface{} {
		event := app.Event{Value: args[0]}
		event.PreventDefault()
		fmt.Println("preventSubmit")
		return false
	})

	form := app.Window().GetElementByID("register-captcha-form")
	if !form.Truthy() {
		panic("form element not found")
	}
	form.Call("addEventListener", "submit", preventSubmit)

	c.closePreventSubmit = func() {
		form.Call("removeEventListener", preventSubmit)
		preventSubmit.Release()
	}
}

func (c *register) OnDismount() {
	fmt.Println("dismount")
	if c.closePreventSubmit != nil {
		c.closePreventSubmit()
	}
}

func (c *register) Render() app.UI {
	return app.Div().
		Class("flex").
		Class("justify-center").
		Body(
			app.Form().
				ID("register-captcha-form").
				OnSubmit(c.onSubmit).
				Body(
					app.If(c.err != "",
						app.Div().Text(c.err),
					),
					app.Input().
						Placeholder("name").
						Value(c.name).
						OnChange(c.ValueTo(&c.name)),
					app.Button().
						Type("submit").
						Text("submit"),
				),
		)
}

func (c *register) onSubmit(ctx app.Context, e app.Event) {
	fmt.Println("onSubmit =>", c.name)
	c.err = ""
	if c.name == "" {
		c.err = "no name"
	}
}
```

**Comment by ItsVoltz** [comment]
> I'm not sure about what is wrong, I try to reproduce this but seems to work for me:
> 
> ```go
> type register struct {
> 	app.Compo
> 
> 	closePreventSubmit func()
> 	name               string
> 	err                string
> }
> 
> func (c *register) OnMount(ctx app.Context) {
> 	preventSubmit := app.FuncOf(func(this app.Value, args []app.Value) interface{} {
> 		event := app.Event{Value: args[0]}
> 		event.PreventDefault()
> 		fmt.Println("preventSubmit")
> 		return false
> 	})
> 
> 	form := app.Window().GetElementByID("register-captcha-form")
> 	if !form.Truthy() {
> 		panic("form element not found")
> 	}
> 	form.Call("addEventListener", "submit", preventSubmit)
> 
> 	c.closePreventSubmit = func() {
> 		form.Call("removeEventListener", preventSubmit)
> 		preventSubmit.Release()
> 	}
> }
> 
> func (c *register) OnDismount() {
> 	fmt.Println("dismount")
> 	if c.closePreventSubmit != nil {
> 		c.closePreventSubmit()
> 	}
> }
> 
> func (c *register) Render() app.UI {
> 	return app.Div().
> 		Class("flex").
> 		Class("justify-center").
> 		Body(
> 			app.Form().
> 				ID("register-captcha-form").
> 				OnSubmit(c.onSubmit).
> 				Body(
> 					app.If(c.err != "",
> 						app.Div().Text(c.err),
> 					),
> 					app.Input().
> 						Placeholder("name").
> 						Value(c.name).
> 						OnChange(c.ValueTo(&c.name)),
> 					app.Button().
> 						Type("submit").
> 						Text("submit"),
> 				),
> 		)
> }
> 
> func (c *register) onSubmit(ctx app.Context, e app.Event) {
> 	fmt.Println("onSubmit =>", c.name)
> 	c.err = ""
> 	if c.name == "" {
> 		c.err = "no name"
> 	}
> }
> ```

See my issue is I can get it to update at least once, its after I try to set the variable after. So for example say I get a username with whitespace error and then I run it again trying to get another error it just doesnt update. the max ith as updated is 2 times for me. Which is quite infuriating.

**Comment by oderwat** [comment]
I did not follow this really but are you sure that `&components.Captcha{Callback: "registerCaptchaCB"}` is safe to be rendered multiple times?

There is also `OnDismount()` but if the same(!) component gets mounted again the `closePreventSubmit` will not be nil as it was not reset to nil on dismount.

As I said, it is just wild guessing :)

**Comment by ItsVoltz** [comment]
> 

registerCaptchaCB is just a JS callback to set the token so from the recaptcha handler so I can pull it into the OnRegister. However, It still runs the event handler for the form submission but changing the var doesnt change it in the component

**Comment by oderwat** [comment]
I often "thought" to know what happens but it did not do what I was thinking. That is why I made https://github.com/metatexx/go-app-pkgs/tree/master/dbg and added `dbg.Log()` and `dbg.Logf("something: %s",something)` to every single function in my code. So I could easily see what runs when and what parameters or state it has.

**Comment by oderwat** [comment]
Looks like this in the console:
![image](https://user-images.githubusercontent.com/719156/148793442-5612c1cf-7aa6-49b2-9e8a-7ff4383bddea.png)

**Comment by maxence-charriere** [comment]
@ItsVoltz any chance i can clone your repo and try to figure out directly?

**Comment by ItsVoltz** [comment]
> @ItsVoltz any chance i can clone your repo and try to figure out directly?

Unfortunately my buddy wont let me as it contains API and other backend stuff under the same repo.

**Comment by ItsVoltz** [comment]
Okay I fixed it by not using value to and pulling and assigning the value myself, i plan on rewriting inputs and what not to components and allow for me to make custom validators and stuff inline, so I can reduce my renders a lot so this is what I was gonna do anyways. Thanks everyone!
