### ISSUE TITLE
Setting page titles OnPreRender doesn't reflect when clicking link

### ISSUE THREAD

**Issue by ItsVoltz** [maxence-charriere/go-app#674]
When setting page data like title author etc and clicking on a ref to navigate to a different route it doesn't change the title unless you force reload the page. Should I be setting title `OnNav()` aswell?

**Comment by oderwat** [comment]
I would not like that. Nothing says that navigation moves to a "page" with another title. It just changes the URL. My apps actually do not necessarily even have something "pages". I don't want to replicate a "server" in the front end of my SPA.

**Comment by maxence-charriere** [comment]
You can modify title and some other things with ctx.Page

**Comment by oderwat** [comment]
I redacted my comment because I misread that you want to set it implicitly when navigation occurs. Setting it from OnNav when one wants it is how we do it when we want it.
