### ISSUE TITLE
how can i render root to body?

### ISSUE THREAD

**Issue by YankeeTube** [maxence-charriere/go-app#677]
It was confirmed that using app.body().body() in this way was removed from 9.3.0.  

So how can I start with the body, not the `div`, in order to start with the `body`?

**Comment by maxence-charriere** [comment]
The body is attr are customizable but the content is handled by go-app routing and components.

**Comment by YankeeTube** [comment]
@maxence-charriere Then, do you happen to
Is it possible to js `append` `app.UI` with `app.Window().Get("document")` ?

**Comment by maxence-charriere** [comment]
You can do whatever is possible to do with js.
