### ISSUE TITLE
handler does not take effect

### ISSUE THREAD

**Issue by InasaXia** [maxence-charriere/go-app#683]
title,html,body... 
These properties use default values.
```
func main() {
	app.Route("/", &hello{})
	app.RunWhenOnBrowser()
	http.Handle("/", &app.Handler{
		Name:  "Hello",
		Title: "test",
		HTML: func() app.HTMLHtml {
			return app.Html().Styles(map[string]string{
				"height": "100%",
			})
		},
		Body: func() app.HTMLBody {
			return app.Body().Styles(map[string]string{
				"height": "100%",
			})
		},
	})

	if err := http.ListenAndServe(":8000", nil); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by simulot** [comment]
Does hello component has a Render method?

**Comment by InasaXia** [comment]
Yes. It has a Render method.
![image](https://user-images.githubusercontent.com/30060632/149695923-b7e4eff5-57ec-4df5-8b93-3238f177932e.png)

**Comment by maxence-charriere** [comment]
Can you show the page source code? (The one from the browser View Page Source button)

**Comment by InasaXia** [comment]
I tried it again and this time it worked.

**Comment by InasaXia** [comment]
Maybe browser cache？

**Comment by maxence-charriere** [comment]
You may have to reload  after an update. Check the console log.

**Comment by InasaXia** [comment]
Yes. Thanks.
