### ISSUE TITLE
ObserveState doesn't work with ExpiredIn

### ISSUE THREAD

**Issue by maxim0r** [maxence-charriere/go-app#684]
Hi, Maxence,
Thank you for the great work.
I wanted to do a temporary alert via state with the ExpiredIn parameter. I was hoping that the observation would work. Unfortunately, it doesn't work. What is the best way to implement such a pattern?
```go
type Alert struct {
	app.Compo
	alert model.Alert
}

func (c *Alert) Render() app.UI {

	if c.alert.Text == "" {
		return app.Div()
	}

	return app.Div().
		Class("alert alert-" + string(c.alert.Style)).
		Text(c.alert.Text)
}

func (c *Alert) OnMount(ctx app.Context) {
	ctx.ObserveState("alert").Value(&c.alert)
}
```

Setting the state value
```go
ctx.SetState("alert",
	model.Alert{Text: "Success", Style: model.Success},
	app.ExpiresIn(alertDisplayInterval),
)
```

**Comment by maxence-charriere** [comment]
The state is expired but does not provide a notification for it. I did not think of dispatching that a state was expired. Right now it is just removed from the store. Maybe I should change that behavior. Have to take a look at how to implement it.

**Comment by maxence-charriere** [comment]
I'm not sure finally. Here what you want to do is change the state to say it has another value.
Maybe you should do something like this:

```go
ctx.SetState("alert", model.Alert{Text: "Success", Style: model.Success}

ctx.After(alertDisplayInterval, func (ctx app.Context) {
    ctx.SetState("alert", model.Alert{Text: "Error", Style: model.Error}
})
```

**Comment by maxim0r** [comment]
Thank you for your help. 
ctx.After almost works. Only after Navigate does not work.
I am probably doing something wrong.
I am trying to do the following
```go
func (c *Logon) logon(ctx app.Context, e app.Event) {

	ctx.Async(func() {

		token, err := api.Logon(ctx, c.username, c.password)
		if err != nil {
			ctx.SetState("alert",
				model.Alert{Text: "Auth error: " + err.Error(), Style: model.Danger},
			)

			// it works
			ctx.After(alertDisplayInterval, func(ctx app.Context) {
				ctx.SetState("alert", model.Alert{})
			})

			c.Update()
	
			return
		}

		ctx.SetState("alert",
			model.Alert{Text: "Auth success", Style: model.Success},
		)

		ctx.SetState("token", token, app.Persist)

		// it does not work
		ctx.After(alertDisplayInterval, func(ctx app.Context) {
			ctx.SetState("alert", model.Alert{})
		})

		ctx.Navigate("/")
	})
}
```

Please tell me what's wrong. I couldn't figure it out myself.

**Comment by maxence-charriere** [comment]
```go
c.Update()
```
No need this.

Should you put `ctx.Navigate("/")` in the after block?
