### ISSUE TITLE
How to use go app to compile HTML？

### ISSUE THREAD

**Issue by toolvcn** [maxence-charriere/go-app#685]
Compile into wasm is
GOARCH=wasm GOOS=js go build -o web/app.wasm

Convert to html？

**Comment by simulot** [comment]
Have you tried to run the app? 

If you are using a makefile, run `make run`
https://go-app.dev/getting-started#use-a-makefile

**Comment by toolvcn** [comment]
> 您是否尝试过运行该应用程序？
> 
> 如果您使用的是生成文件，请运行 https://go-app.dev/getting-started#use-a-makefile`make run`

The App run successful，What I want to generate is an HTML page. 
For example, an HTML file under a URL，How can I generate such a page？
[https://github.com/maxence-charriere/go-app/tree/master/docs](url)

**Comment by mlctrez** [comment]
@toolvcn -

Look into https://github.com/maxence-charriere/go-app/blob/master/pkg/app/static.go
and https://go-app.dev/github-deploy

**Comment by toolvcn** [comment]
> @toolvcn -
> 
> 查看https://github.com/maxence-charriere/go-app/blob/master/pkg/app/static.go和https://go-app.dev/github-deploy

Thank you. That worked out for me
