### ISSUE TITLE
Self-contained app running on IPFS

### ISSUE THREAD

**Issue by mar1n3r0** [maxence-charriere/go-app#691]
I am researching as of late the idea to run the wasm app on a distributed network such as IPFS.

Resources:

https://docs.ipfs.io/how-to/websites-on-ipfs/multipage-website/

https://github.com/ipfs/go-ipfs/issues/5520

https://github.com/ipfs/go-ipfs/issues/4025

https://docs.ipfs.io/concepts/ipns/#example-ipns-setup-with-cli

In fact it does work! Completely distributed and without the server part running anywhere.

You will need a running node of ipfs-desktop to access it:
https://docs.ipfs.io/install/ipfs-desktop/#install-using-appimage

Example with functioning navigation:
https://github.com/mar1n3r0/hello-ipfs

**Comment by oderwat** [comment]
Very interesting (and it works). I did not look into IPFS lately but may experiment a bit with it again.

**Comment by mar1n3r0** [comment]
Yeah with pubsub out of the box and distributed database such as https://github.com/berty/go-orbit-db we might not even need backend and devops anymore for some use cases. Although in practice a distributed network will always be slower than a centralized one when it comes to time-sensitive tasks.
