### ISSUE TITLE
Why does HTMLBody not accept more than one child?

### ISSUE THREAD

**Issue by PauloMelo** [maxence-charriere/go-app#692]
There are situations where you may not want to have a div inside the body and all children elements being inside that div.
There are situations where you want to have several children inside the body, either by being different sections or articles.

Since a app.Composer in argument to app.Route must be Render() app.UI, there is no way to create more than one children entry to the body.

How can I do it without passing a app.Div().Body(....)?

**Comment by oderwat** [comment]
Good question! I once also needed multiple divs and could work around it by using `app.Section()` and putting the divs inside that. But I would like to have a better solution too.

**Comment by maxence-charriere** [comment]
Is that really a problem to wrap sections/articles inside a div?

Div is not a semantic element and does not have any effect on seo.

**Comment by PauloMelo** [comment]
No it is not a problem, it is ugly and is not compliant with the HTML standard. It is not nice to state that "you cannot have more than one child inside the body, and, by the way the best solution is to use a div..."

but in the end you are the owner...

**Comment by oderwat** [comment]
It should be possible to have `body(nav,article,section)` which is currently not possible. I should also be possible to just have a `body(h1,p,p,h2,p,h2,p)`. I also run into the problem that a component can't return more than a root node. For example, a "left navigation" which just outputs a list of divs, would be nice.

All of this can be worked around (of course). I also had a problem with CSS which I could work around using an `app.Section().Style("display", "contents")` construct. I don't really remember what it was and if that can be solved now with the possibility to define the body element myself.

**Comment by maxence-charriere** [comment]
I had been considering this but the implementation made things too complicated. For now I want to keep thing working, simple, and maintainable.
