### ISSUE TITLE
The Event after Render()

### ISSUE THREAD

**Issue by dingdinglz** [maxence-charriere/go-app#696]
I have some js codes want to run after the Render Method.
Is there an event after the Render ?
I try Mounted, but sometime appear the error:syscall/js: call of value.call on undefined
I think that  is because Render not finish.

**Comment by maxence-charriere** [comment]
You can use ctx.Dispatch or ctx.Defer

**Comment by oderwat** [comment]
> You can use ctx.Dispatch or ctx.Defer

To react to something being rendered? There is no `ctx` in Render, where should it be called?

I guess what he could do is render a script tag as part of the Render function which executes the javascript code he wants to run.

```
func (c *Markdown) Render() app.UI {
	return app.Div().ID("testid").Class("prose prose-red prose-sm sm:prose").Body(app.Raw(`<div class="container">`+c.converted+"</div>"),
		app.Script().Text(`window.alert(document.getElementById("testid").innerHTML);`))
}
```

**Comment by dingdinglz** [comment]
> > You can use ctx.Dispatch or ctx.Defer
> 
> To react to something being rendered? There is no `ctx` in Render, where should it be called?
> 
> I guess what he could do is render a script tag as part of the Render function which executes the javascript code he wants to run.
> 
> ```
> func (c *Markdown) Render() app.UI {
> 	return app.Div().ID("testid").Class("prose prose-red prose-sm sm:prose").Body(app.Raw(`<div class="container">`+c.converted+"</div>"),
> 		app.Script().Text(`window.alert(document.getElementById("testid").innerHTML);`))
> }
> ```

right , i try to add ctx.defer or ctx.dispatch , but it not work.
then i use your method , i find ,this way,can't use scripts'method imported in app.Handler Scripts
error of undefind

**Comment by oderwat** [comment]
Prerender happens only on the server before your page gets delivered to the browser. So this will never work for JS Code.

I can't imagine your code. Could you maybe share some of it?

**Comment by dingdinglz** [comment]
> I can't imagine your code. Could you maybe share some of it?

I want to render some markdown after Render().
use markdown.js
markdown.toHtml()

**Comment by maxence-charriere** [comment]
Have a look on the doc source of this repo. I m doing it too.

**Comment by maxence-charriere** [comment]
You can use `ctx.Defer` for that now.
