### ISSUE TITLE
typeerror: failed to execute 'compile' on 'webassembly': http status code is not ok

### ISSUE THREAD

**Issue by javlonrahimov** [maxence-charriere/go-app#697]
It is giving me this error when I try to run the example from the documentation.

`typeerror: failed to execute 'compile' on 'webassembly': http status code is not ok
`

![Screenshot from 2022-03-04 21-36-38](https://user-images.githubusercontent.com/56770292/156803030-a9f7fbbd-4e75-4958-aac3-4d02b40e43c9.png)

**Comment by jwmach1** [comment]
double check, are you using go 1.17 as mentioned in [getting started](https://go-app.dev/getting-started)?

**Comment by maxence-charriere** [comment]
Did you compile the webassembly part?

**Comment by javlonrahimov** [comment]
> double check, are you using go 1.17 as mentioned in [getting started](https://go-app.dev/getting-started)?

Yes I am using 1.17.7

**Comment by javlonrahimov** [comment]
> Did you compile the webassembly part?

Oh, I forgot it :(.
It is working now!!!

Thanks.
