### ISSUE TITLE
CompileError: wasm validation error: at offset 4: failed to match magic number

### ISSUE THREAD

**Issue by roborobs1023** [maxence-charriere/go-app#703]
Compile error when using make file for hello test. 

below is a copy of my main.go file. 

I'm working on Windows 10 for programing this and have both make and GCC installed. When I run the command (make run) all compiles correctly but when I go to launch in a browser I get the following error message. 

CompileError: wasm validation error: at offset 4: failed to match magic number

`package main
import (
  "log"
	"net/http"

	"github.com/maxence-charriere/go-app/v9/pkg/app"
)

// hello is a component that displays a simple "Hello World!". A component is a
// customizable, independent, and reusable UI element. It is created by
// embedding app.Compo into a struct.
type hello struct {
	app.Compo
}

// The Render method is where the component appearance is defined. Here, a
// "Hello World!" is displayed as a heading.
func (h *hello) Render() app.UI {
	return app.H1().Text("Hello World!")
}

// The main function is the entry point where the app is configured and started.
// It is executed in 2 different environments: A client (the web browser) and a
// server.
func main() {
	// The first thing to do is to associate the hello component with a path.
	//
	// This is done by calling the Route() function,  which tells go-app what
	// component to display for a given path, on both client and server-side.
	app.Route("/", &hello{})

	// Once the routes set up, the next thing to do is to either launch the app
	// or the server that serves the app.
	//
	// When executed on the client-side, the RunWhenOnBrowser() function
	// launches the app,  starting a loop that listens for app events and
	// executes client instructions. Since it is a blocking call, the code below
	// it will never be executed.
	//
	// When executed on the server-side, RunWhenOnBrowser() does nothing, which
	// lets room for server implementation without the need for precompiling
	// instructions.
	app.RunWhenOnBrowser()

	// Finally, launching the server that serves the app is done by using the Go
	// standard HTTP package.
	//
	// The Handler is an HTTP handler that serves the client and all its
	// required resources to make it work into a web browser. Here it is
	// configured to handle requests with a path that starts with "/".
	http.Handle("/", &app.Handler{
		Name:        "Hello",
		Description: "An Hello World! example",
	})

	if err := http.ListenAndServe(":8000", nil); err != nil {
		log.Fatal(err)
	}
}
`

below is a copy of my makefile 

`build:
	set GOARCH=wasm 
	set GOOS=js 
	go build -o web/app.wasm
	go build

run: build
	.\Go-App-Test
`

**Comment by nbarbey** [comment]
I have the same issue on a linux install. Just followed the tutorial and got this error.

**Comment by maxence-charriere** [comment]
Not sure how it work on window but setting the env variable in a different line will likely result on not having them set. I think each makefile command run in its own terminal session.

**Comment by oderwat** [comment]
I am using [Mage](https://magefile.org/) instead of Make for quite some time now and would not want to go back.

Here is a short snippet of how I use it (I quickly copy & paste it together from a much larger one so it may need some tweaks to make it work):

```go
package main

import (
    "errors"
    "fmt"
    "os"
    "os/exec"
    "runtime"
    "time"

    "github.com/magefile/mage/mg"
    "github.com/magefile/mage/sh"
    "github.com/magefile/mage/target"
)

var goCompiler = "go"

var appName = "./bin/theapp"
var appGlobs = []string{
    "./magefiles/*.go",
    "./go.mod",
    "./cmd/app/*.go",
    "./pkg/*/*.go",
}

func init() {
    if runtime.GOOS == "windows" {
        appName += ".exe"
    }
}

func buildApp() error {
    changes, err := target.Glob(appName, appGlobs...)
    if err != nil {
        return err
    }
    if !changes {
        return nil
    }
    fmt.Println("> Building App...")
    if desktop {
        return sh.RunV(goCompiler, "build", "-tags", "desktop", "-o", appName, "./cmd/app")
    } else {
        return sh.RunV(goCompiler, "build", "-o", appName, "./cmd/app")
    }
}

func BuildWasm() error {
    changes, err := target.Glob("web/app.wasm", appGlobs...)
    if err != nil {
        return err
    }
    if !changes {
        return nil
    }
    fmt.Println("> Building WASM...")
    return sh.RunWithV(map[string]string{"GOOS": "js", "GOARCH": "wasm"}, goCompiler, "build", "-o", "web/app.wasm", "./cmd/app")
    //return sh.RunWithV(map[string]string{"GOOS": "js", "GOARCH": "wasm"}, goCompiler, "build", "-ldflags", "-s -w", "-o", "web/app.wasm", "./cmd/app")
}


func Build() error {
    mg.Deps(BuildWasm)
    return buildApp()
}
```
