### ISSUE TITLE
Complete frontend development using go-app

### ISSUE THREAD

**Issue by wraza2k9** [maxence-charriere/go-app#715]
I love the go-app projects.

I have a short question, I do not have web frontend development experience with vanilla javascript or other frameworks.
Can I develop complex web applications completely in go-app? 

Thanks .

**Comment by maxence-charriere** [comment]
Https://murlok.io 

make your own opinion.

**Comment by oderwat** [comment]
@wraza2k9 I think your question is not if one can make a complex front-end with go-app but if you can do it when you have no experience with "normal" javascript frontends.

To be honest I very much think it makes it harder to use go-app if you do not already know much about the DOM, Javascript, event handling, HTML(-Forms), and CSS. I fear go-app will not help you with that. I may be wrong but without having somebody "translating" all the knowledge into the go-app domain, it will be much harder than just starting out with VUE.js or Vite (to name two of my personal favorites). There is a lot (LOT) of material for these (and even more for REACT or AngularJS).

So if you really have no frontend development experience, I fear you need to learn a whole bunch more than just how to use go-app and write Go code:

* HTML5
* CSS
* Javascript Events (at least, but more likely all of Javascript)
* The DOM and how it works (even if go-app handles a lot of that)
* REST or other APIs

So I guess as long there is not a "building block" package that hides this complexity, you will need to learn all of this to create a complex web application.

This is in contrast to using Flutter (Web), which may be the only feasible option (from what I know). With this, you learn "Flutter UI" (and the Dart language). There is no need to know HTML or CSS in fact it can even render to canvas and skip HTML. Flutter (or better Dart) for Web does compile to Javascript and the system also uses WASM. They may move more to WASM in the future. We made some Flutter App and it works. It is not my favorite though.

As I do not like coding in Javascript I was looking for alternatives and looked into Nim (a great general-purpose language that can compile to JS but is very unknown) and Elm (which compiles to JS and is made for Frontend development) and has some abstraction which reminds me on go-app at times.

So if you have the time and enthusiasm I also think it is a strength of go-app that it is a bit META to all of this. You could very well mix go-app with other Javascript frameworks or libraries. You do depend on WASM and its future development though. This alone makes go-app a "questionable" target and may be very well a reason to not use it for anything "real" if you can't take a risk.
