### ISSUE TITLE
What is the offline mode?

### ISSUE THREAD

**Issue by dht-hedaihua** [maxence-charriere/go-app#721]
Hi，I saw that the feature supports offline mode, but I didn't see what the offline mode is after I read the documents and related issues. Is there a relevant demo? thanks.

**Comment by mlctrez** [comment]
@HDHChris 

This basically means that you don't have to have internet connectivity once the go-app application has been loaded once and the service worker is installed. All resources used by the application will be cached and the app can run without an internet connection. 

More details on service workers and offline mode
https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers
