### ISSUE TITLE
How to get the dom after the iframe is loaded

### ISSUE THREAD

**Issue by carmel** [maxence-charriere/go-app#724]
First of all, thank you for this wonderful project. 

As a newbie, I would like to know if there is some kind of lifecycle hook (like the Compo OnMound function) that is called after the iframe is loaded and some way to get the dom content when the iframe is embedded in the UI.

For example, I have embedded an iframe in the UI to load a certain product detail page of Amazon, and I want to resolve the SKU information of the product by dom after the page is loaded, so how can I get such a dom?

![image](https://user-images.githubusercontent.com/36031579/166159132-f63c7843-a277-4a3c-abe4-63d73808c913.png)

Although iframes have a load event, it seems that it cannot trigger the load event in a target page which entered by clicking multiple links. For example, iframe src is Amazon home page, here you need to click a series of links to enter the product details page.

**Comment by oderwat** [comment]
I wonder how you get around 'X-Frame-Options: sameorigin' for this page? It should not be possible to load Amazon into an iFrame.

If you actually can load the page into the iframe, you should also get access to the document and contentWindow of the iframe and can access this.

But I don't think this has much to do with Go-App after all.

**Comment by oderwat** [comment]
@carmel I don't think that there is a way to get the cookies from the iframe.

To make it actually work I would suggest that you use [ChromeDP](https://github.com/chromedp/chromedp) in the backend and show the results in the frontend with a "same-site" iframe (maybe only the needed parts). There you can grab all events you are interested in and replicate them in ChromeDP. 

You also could create/use a complete transparent proxy and filter that data. This may even be the **easiest** way and I did something like that in the past to add SSO to a site that did not support it and even used a shared account for the different users and filtered stuff in that proxy by the user.

Yet another method would be to just inject javascript into the actual page using [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo) or another way.

The last method which comes to my mind would be to create a browser extension for what you want to do and let it talk to a backend.

The two last things could still be in an iframe inside your App and communicate with it using the shared backend API.

**Comment by carmel** [comment]
That's so cool, thanks for the advice.
