### ISSUE TITLE
building up content with loops over collections...

### ISSUE THREAD

**Issue by alphastrata** [maxence-charriere/go-app#728]
Hello, I'm looking to something like the following (wanting to build a gallery).

```go
ImageGallery := ioutil.ReadDir("web/images")

for _, img; range ImageGallery{
   app.Append(app.Img(...))
}
```
haven't been able to work out how to do it with the provided range.
would be useful to know whether or not calls to `tr` can work too?

**Comment by oderwat** [comment]
Besides that `ImageGallery, _ := ioutil.ReadDir("web/images")` will only work in the backend / PreRender step you would use it like this (attention, just some kind of pseudo code):

```go
func (c *Component) PreRender() app.UI {
   ImageGallery, _ := ioutil.ReadDir("web/images")
   return app.Range(ImageGallery).Slice(func(idx int) app.UI {
      return app.Img().Src("/web/imaged"+ImageGallery[idx].Name())
   })
}
```

**Comment by oderwat** [comment]
> would be useful to know whether or not calls to `tr` can work too?

What is `tr`?

**Comment by alphastrata** [comment]
> 
`tr` tablerow
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr
