### ISSUE TITLE
github.com/maxence-charriere/go-app/v9/pkg/app Not found

### ISSUE THREAD

**Issue by bridoux** [maxence-charriere/go-app#732]
VS code not finding github.com/maxence-charriere/go-app/v9/pkg/app in $
![go-app package not find](https://user-images.githubusercontent.com/6211647/171801186-b53bb3df-f64c-481c-be5b-439f884ae7e6.png)
![added package](https://user-images.githubusercontent.com/6211647/171801218-3cdf8105-cabb-4ee4-a57d-8e5bc260ff52.png)
GOPATH even though it installed successfully via command prompt. I ave tried different ways do not seem to figure out what the problem is.
NB: I am new to go and thought it might be interesting to work with go-app
TIA

**Comment by maxence-charriere** [comment]
you might import a go-app without v9 somewhere
