### ISSUE TITLE
How do i make this work on windows

### ISSUE THREAD

**Issue by ObiajuluM** [maxence-charriere/go-app#737]
I have done everything in the tutorial so far, I have successfully generated the 6 files, how do I run the server
the tutorial says to run this `./hello` in the terminal, but it doesn't work. it seems like a Linux command

thanks

**Comment by oderwat** [comment]
The filename after building the project on windows will end in `.exe`. It depends on the folder your code resides in when running the `go mod init` or on the name you have chosen when using `go mod init withsome.com/yourname/hello`.

You can also force the name using the following two lines to build the app:

```
GOARCH=wasm GOOS=js go build -o web/app.wasm
go build -o hello.exe
```

P.S.: Actually, it sounds as if you are a Go beginner and you could look up some info about building programs with Go using Windows.

**Comment by ObiajuluM** [comment]
hello @oderwat, sorry to disturb you.

<img width="164" alt="image" src="https://user-images.githubusercontent.com/47371105/176884067-d689412c-04a5-485e-8d06-e51522babfa4.png">
I have done the necessary but I get this error when I run the main.go file.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/47371105/176884231-1b2ed12b-dcfe-4c02-9608-eb9ca3a76f2c.png">

**Comment by oderwat** [comment]
The `main` dies not end in `.exe` which happens if the Go environment thinks it is on Linux. Check with `go env` what `GOOS` says. I guess it will be "linux" or "darwin" but it must be "windows". 

Check this: https://github.com/golang/go/issues/40237 (not the first answer, which is about virus checkers but the later one)

**Comment by ObiajuluM** [comment]
done, it works thanks

**Comment by ObiajuluM** [comment]
Can you recommend any tutorials for Go-app other than the website-provided one? Videos, blogposts, anything

**Comment by oderwat** [comment]
> Can you recommend any tutorials for Go-app other than the website-provided one? Videos, blogposts, anything

I am not aware of anything like that. I also think that people have different approaches to using it. The only resources I know of are the few public projects that use go-app. We work on a pretty big (and very opinionated) framework that sits on top of (a fork) of Go-App. But that will probably never be (fully) released to the public. We may create some examples in the future. I plan to let some developers create demos with the raw Go-App that can be published when starting to work with our framework.

**Comment by ObiajuluM** [comment]
Sorry to disturb, Do you know any other frameworks similar to this, for building PWAs and in full go code?

**Comment by oderwat** [comment]
There are [vugu](https://github.com/vugu/vugu), [vecty](https://github.com/hexops/vecty) and maybe [dashborg-go-sdk](https://github.com/sawka/dashborg-go-sdk) are what I know of.  I don't comment them :)

**Comment by ObiajuluM** [comment]
Thanks

**Comment by ObiajuluM** [comment]
> We work on a pretty big (and very opinionated) framework that sits on top of (a fork) of Go-App. But that will probably never be (fully) released to the public. 

what framework is that?

**Comment by oderwat** [comment]
> what framework is that?

Our own of course.

**Comment by ObiajuluM** [comment]
It's private?

**Comment by oderwat** [comment]
Yes

**Comment by ObiajuluM** [comment]
Ok, enjoy
