### ISSUE TITLE
Disable Offline Mode

### ISSUE THREAD

**Issue by Naatan** [maxence-charriere/go-app#742]
Hi, I'm using go-app for a webview application, which is using a local http server. As such offline mode is of no use to me and further - it seems to make live reload functionality unreliable.

Is there any way I can disable offline mode?

Thanks.

**Comment by oderwat** [comment]
Afaik, that is not possible right now. But I think you can easily make a fork and remove the (ServiceWorker part)[https://github.com/maxence-charriere/go-app/blob/2c1f1d9faccea9f0f61441699839316577cb5047/pkg/app/gen/app.js#L13-L15] to give it a try. I think that could work.
