### ISSUE TITLE
LocalDir ResourceProvider does not find /web relative to executable

### ISSUE THREAD

**Issue by justinfx** [maxence-charriere/go-app#753]
Hi there. Just getting started with my first go-app project, and I am finding that even though the docs state this:

(https://go-app.dev/static-resources)

> static resources are to be put into a directory called web, by default located next to the [server](https://go-app.dev/architecture#server) executable

... I am finding that the implementation of `LocalDir()` (default) actually expects the "web" directory to be relative to the current working directory as opposed to the location of the executable. If I run the executable from a different location, regardless of the web directory being right next to it, the resources are not found. In my own code I have had to implement a modified version that does the following:

```go
func LocalResourceDir() app.ResourceProvider { 
	path, _ := os.Executable() 
	path = filepath.Dir(path) 
	return resourcesFS{ 
		Handler: http.FileServer(http.Dir(path)), 
	} 
} 

type resourcesFS struct { 
	http.Handler 
} 

func (resourcesFS) Package() string { return "" } 
func (resourcesFS) Static() string  { return "" } 
func (resourcesFS) AppWASM() string { return "/web/app.wasm" } 
```

Is this something the `LocalDir()` should support? Or should the documentation be updated to reflect the current behaviour?

Thanks!

**Comment by oderwat** [comment]
I think the documentation should be updated.

**Comment by justinfx** [comment]
If the fix is to update the user docs, it might be nice to further update `LocalDir` docstring to note that it only supports a root path located under the current working directory of the process.  Because it strips away the leading slash, preventing you from applying an absolute path, the behavior can be a bit surprising.

**Comment by maxence-charriere** [comment]
I will update the documentation.

Modifying the LocalDir godoc part is not necessary.

> LocalDir returns a resource provider that serves static resources from a local directory located at the given path.

Dealing with absolute or relative path behavior is not a problem related to go-app.

**Comment by justinfx** [comment]
> Dealing with absolute or relative path behavior is not a problem related to go-app.

Are you sure? `LocalDir` specifically formats the path parameter to make it only work if it's relative to the cwd. So that seems go-app specific since it is imposing the behavior with an assumption about the meaning of the path.

**Comment by maxence-charriere** [comment]
if you specify an absolute path, it will take it no matter what is the working dir

**Comment by justinfx** [comment]
Well, yes it will take the path and do something with it. But the results are unexpected. If you pass it an absolute path, it will not be treated absolute. And the docstring doesn't say that it roots it to the process cwd.
But ok, I will back off. Your call obviously!
