### ISSUE TITLE
Documentation suggestion in go-app page

### ISSUE THREAD

**Issue by drognisep** [maxence-charriere/go-app#758]
Something I've noticed is that Go => WASM makes some pretty big files in general, and app.wasm size can contribute to slower page loads. I don't see a performance section in the docs, but if one were to be added it might be worth mentioning that making a cleaner separation between wasm code and server code can really reduce the wasm bundle size.

How I did this is instead of putting the server startup code in main.go, I moved it to its own server.go file in the main package. Then I created another file called server_js.go where the same function is defined, but empty. Using the Hello World example (plus a little bit extra stuff) this single change shrank the app.wasm file from 13MB to 5MB. That can make a pretty big difference on resource constrained devices for that first impression page load.

### Original main.go
```go
package main

import (
	"context"
	"github.com/maxence-charriere/go-app/v9/pkg/app"
	"log"
	"net/http"
	"time"
)

type Frame struct {
	app.Compo
}

func (f *Frame) Render() app.UI {
	return app.Div().Class("frame").Body(
		app.H1().Text("Hello World!"),
	)
}

func main() {
	app.Route("/", &components.Frame{})
	app.RunWhenOnBrowser()

	mux := http.NewServeMux()
	mux.Handle("/", &app.Handler{
		Name:        "Hello",
		Description: "A Hello World! example",
		Styles: []string{
			"/web/main.css",
		},
	})

	ctx := handleSignals()
	srv := http.Server{
		Addr:    ":8080",
		Handler: mux,
	}

	done := make(chan struct{})
	go func() {
		<-ctx.Done()
		timeout, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		if err := srv.Shutdown(timeout); err != nil {
			log.Printf("Error shutting down the server: %v\n", err)
		}
		close(done)
	}()

	log.Println("Starting todo app server")
	if err := srv.ListenAndServe(); err != nil {
		if err != http.ErrServerClosed {
			log.Fatalf("Error starting server: %v\n", err)
		}
	}
	<-done
	log.Println("Server shut down")
}
```

### Modified main.go to call the server function
Note the reduction in imports. This means that there's a lot less needless stuff going into the app.wasm bundle.
```go
package main

import (
	"github.com/maxence-charriere/go-app/v9/pkg/app"
)

type Frame struct {
	app.Compo
}

func (f *Frame) Render() app.UI {
	return app.Div().Class("frame").Body(
		app.H1().Text("Hello World!"),
	)
}

func main() {
	app.Route("/", &components.Frame{})
	app.RunWhenOnBrowser()

	server()
}
```

### server_js.go
Just an empty function. :)
```go
package main

func server() {}
```

### server.go
Moved all the server boilerplate to here with the `!js` build tag to make *sure* it isn't going into the wasm.
```go
//go:build !js

package main

import (
	"context"
	"github.com/maxence-charriere/go-app/v9/pkg/app"
	"log"
	"net/http"
	"time"
)

func server() {
	mux := http.NewServeMux()
	mux.Handle("/", &app.Handler{
		Name:        "Hello",
		Description: "A Hello World! example",
		Styles: []string{
			"/web/main.css",
		},
	})

	ctx := handleSignals()
	srv := http.Server{
		Addr:    ":8080",
		Handler: mux,
	}

	done := make(chan struct{})
	go func() {
		<-ctx.Done()
		timeout, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		if err := srv.Shutdown(timeout); err != nil {
			log.Printf("Error shutting down the server: %v\n", err)
		}
		close(done)
	}()

	log.Println("Starting todo app server")
	if err := srv.ListenAndServe(); err != nil {
		if err != http.ErrServerClosed {
			log.Fatalf("Error starting server: %v\n", err)
		}
	}
	<-done
	log.Println("Server shut down")
}
```

**Comment by oderwat** [comment]
Hi. Yes, that is similar to how we do it too. We use a `WASM` and a `!WASM` build target to separate the front-end from the back-end and vice versa. But beware, that will destroy server-side rendering (SEO) and remove all the front-end code from the back-end. I do not like all that extra code in the executable and our apps don't have "normal" routes, as they are mostly real apps and not "websites" that are supposed to be called through those URLs.

So we have not only one "dependent" function but two: `AppServer()` (which is the back end) and `UX()`, which is the front end, and locks like this for the easiest case. Both are called by `main.go` and depend on the build flag.

```go
func main() {
	// This is behind a WASM build tag, so the business logic of the UI does not increase
	// the size of our server executable.
	// It also has an empty component with its own Render in "server.go"
	UX()

	// this concludes the part which goes into the front-end
	app.RunWhenOnBrowser()

	// this will depend on the target (wasm or not wasm) and
	// it starts the servers if it is not the wasm target.
	AppServer()
}
```

The front-end code in the back-end (`!WASM target`) looks like that for the simplest case.

```go
// Our empty version of the httpServer for usage with the wasm target
// this way, we will not include any of the related code
//go:build !wasm

package main

import (
	"github.com/maxence-charriere/go-app/v9/pkg/app"
)

type empty struct{ app.Compo }

// Render implements the "source" code our App is showing before WASM is loaded and runs.
// Actually, the WASM loader takes over if javascript is available. So this is mainly
// what robots and scrappers get to see.
func (c *empty) Render() app.UI {
	return app.Div().Text("The application is loading...")
}

func UX() {
	// This will skip most of the frontend code in the server binary
	// but keeps the routing intact. It is important that all possible
	// routes that are reachable in the front ende are here. Any route that
	// is not covered results in a (raw) 404 error from the server.

	// For the Skelly demo app, we handle all routes in the front end itself
	app.RouteWithRegexp("/.*", &empty{})
}

func AppServer() {
 // all the server stuff. This also uses a package `services` for the needed API services
// create the go-app handler, set up routes and middleware, and serve them...
}
```

We also put all the frontend code into a package `ux`.

So that looks like that:

```go
// Our empty version of the httpServer for usage with the wasm target
// this way we will not include any of the related code
//go:build wasm

package main

import "...../ux"

// This is a dummy for the AppServer (back end) code, so it does
// not get included in the WASM code
func AppServer() {
}

// This is the actual front-end.
func UX() {
	ux.Create()
}
```

We also use a compression middleware for the WASM and CSS (not for the JS as there is some strange behavior with the service handler updates).

The problem with putting something like that into the documentation is that this can be highly individual. For example, using SSL, connection limiters, redirectors (HTTP->HTTPS), middleware of all kinds (logging/auth), database setups, WebSockets, and so on. So if you are creating a larger application, all of this is very implementation dependant. I guess telling about the negative impact of having the same code for WASM and the executable and having a working example would go a long way, though.

**Comment by maxence-charriere** [comment]
The intent here is to keep the documentation as simple as possible. Cluttering it with compilation directive tends to scare people. 

As @oderwat said too, this is highly individual. Go-app is not supposed to tell you how to organize your code. 

I personally separated server package and wasm package in some project. In some others it just makes thing complicated where there is no need for.

I think WASM size is not a go-app problem but a WASM one.
Organizing code or what compression to use should not be driven by go-app. Go-app should just be able to go along with many scenarios.

**Comment by drognisep** [comment]
> But beware, that will destroy server-side rendering (SEO)

Could you expand on this, @oderwat? With the setup described above, curl is still pulling pre-rendered content with meta tags and everything. As far as I know curl doesn't run any JS associated with a response, so I'm not sure what's missing on the SEO front.

> ...our apps don't have "normal" routes, as they are mostly real apps and not "websites" that are supposed to be called through those URLs.

I hear you there. The only time I've felt the need to break from that is when I needed some sort of deep linking feature. It seems like this separation would allow for tidy front-end logic that can delegate to the back-end for integration concerns.

> The problem with putting something like that into the documentation is that this can be highly individual.

Yeah I agree with that. I think just showing the difference in separation with a pro/con list can let people know a difference exists, and then they can make informed decisions from there in terms of their implementation details.

> Go-app is not supposed to tell you how to organize your code.

> I think WASM size is not a go-app problem but a WASM one.

100% agree on all points. I'm not advocating for a particular project structure or implementation detail per se, I think the core of what I would like to see is something letting people know there are known ways to optimize if necessary (to your points, with as simple code as possible). I think adding a completely different section (performance? optimization?) using the hello world example as is shown in the docs, but separating wasm from server, would be a small change and give people that are looking for it food for thought.

I think it's likely the more I get into this project, the more optimizations and patterns I'll discover that may apply to more people than just me. If so, I think it makes sense to share them. These could always be blog posts or something, but I think this particular idea of separation may be more widely applicable.

**Comment by drognisep** [comment]
>> But beware, that will destroy server-side rendering (SEO)

> Could you expand on this, @oderwat? With the setup described above, curl is still pulling pre-rendered content with meta tags and everything. As far as I know curl doesn't run any JS associated with a response, so I'm not sure what's missing on the SEO front.

@oderwat I think I see what you mean now. It seems like you're talking about the `empty` element introduced in your example. Since the front-end components are not visible within the compilation scope of the server side, it sees nothing to pre-render.

**Comment by maxence-charriere** [comment]
This will be revamped and move away from that repo.
