### ISSUE TITLE
Server side content generation

### ISSUE THREAD

**Issue by ph1048** [maxence-charriere/go-app#763]
Hello!

Could you please point out, how to effectively generate part of content at server side?
I am trying to write a simple application that generates a html table based on data from mongodb request. Obviously, this logic meant to be running at server side. The closest result I got by implementing OnPreRender method, where I call the mongodb, but it is obviously not meant to be solved that way.
So what I am trying to understand is, what is typical approach of interop between client side and server side in a single app.

Here is the code to illustrate the idea:

```
func (h *table) OnPreRender(ctx app.Context) {
	h.Words = ch.GetWordsTableFromDB()
}

func (h *table) Render() app.UI {
	return app.Div().Body(
		app.Table().Body(
			app.Range(h.Words).Slice(func(i int) app.UI {
				return app.Tr().Body(
					app.Td().Body(app.Text(h.Words[i].Get())),
					app.Td().Body(app.Text(h.Words[i].Form1())),
					app.Td().Body(app.Text(h.Words[i].Translate())),
					app.Td().Body(app.Text(h.Words[i].Example())),
				)
			}),
		),
	)
}
```

Apologies if my question is too basic, but I browsed through all docs and examples, and failed to get the idea.

**Comment by oderwat** [comment]
The same as with all other front-end/back-end applications: You create an API in the backend that gets queried from the frontend. So, in addition to the `app.Handler` route, you set another route to a backend service that the frontend can talk to.

The frontend will then query that API (usually after entering some data for a query) and renders the result when it arrives. 

This is not part of Go-App itself, and there are many ways to make that work. I suggest you first implement some API calls to an existing API in the front end. For example, https://www.my-ip.io/api

After that, you could look up one of the many tutorials on creating a REST API service. For example, https://golang.cafe/blog/golang-rest-api-example.html (just a random one I just found). 

I would start with the one that is not using any particular router. Later you may want to switch to something like Gorilla Mux or the Chi Router (which I like).

When you need a lot of different queries, complex data, and versioning, you may want to look at something like I like to use [twirp](https://github.com/twitchtv/twirp) which I like a lot. For even more complex programs you may want to look up something like GraphQL.

**Comment by ph1048** [comment]
Big thanks for this detailed explaination! Now I correctly got the concept, that this is not meant to be done by go-app.
