### ISSUE TITLE
How to use data attributes

### ISSUE THREAD

**Issue by zeljkosh** [maxence-charriere/go-app#771]
I was playing around last night tring to add bootstrap in appGo, and i had somewhat of a success, at least at felt i was progressing and getting a hang of it. 

my code is like this 

```
app.Div().Body(
		app.Nav().Body(
			app.Div().Body(
				app.Button().Body(

					app.Span().Class("navbar-toggler-icon"),
				).Type("button").Class("navbar-toggler rounded-pill"),
				app.Div().Body(
					app.Div().Body(
						app.A().Text("Home").Class("nav-item nav-link "),
						app.A().Text("About").Class("nav-item nav-link "),
					).Class("navbar-nav"),
				).Class("collapse navbar-collapse").ID("navbarCollapse"),
			).Class("container-fluid"),
		).Class("rounded-pill  navbar navbar-expand-lg navbar-dark bg-dark shadow-5-strong"),
	).Class("p-3 container")
```

but now i would like to add `data-bs-toggle="collapse" data-bs-target="#navbarCollapse"` is this possible ? 
or would i have to do the wrapping logic differently?

Thanks.

**Comment by maxence-charriere** [comment]
Cute the data- prefix in the key.

**Comment by oderwat** [comment]
Like this: `app.Div().DataSet("bs-toggle","collapse")...`

**Comment by maxence-charriere** [comment]
Yes

**Comment by zeljkosh** [comment]
Yes that made it work, thanks a lot and very fast reply.
Cheers!

**Comment by dxps** [comment]
For others - as myself - that get into this, a quick summary of working with data attributes:
1. Set them using element's `.DataSet(_)` or `.DataSets(_)` methods.
  Example: `DataSets(map[string]any{ "div1-1": "div-1-1 data", "div1-2": "div-1-2 data" })`

2. Get them using `ctx.JSSrc().Get("dataset").Get(_)`.
  Example: `ctx.JSSrc().Get("dataset").Get("div1-1").String()`

See a small example [here](https://github.com/dxps/go_playground/blob/master/go-app_samples/go-app_html_attrs/internal/components/html_attrs.go).
