### ISSUE TITLE
Getting Started flow skips most docs, sends to Reference early

### ISSUE THREAD

**Issue by stevegt** [maxence-charriere/go-app#774]
When going through /getting-started, I found that the "Next" link in /architecture sends folks directly to /reference.  That gave me a first impression that there was no more documentation other than the API reference.  A better "next" path from /architecture would be /components.  Components is already set up to send people to declarative, routing, etc. after that.  

Fixing this would provide a much smoother learning curve and likely higher adoption.  In my own case, hitting /reference so quickly caused me to spend an afternoon looking for alternatives to go-app before I realized what the problem was.

**Comment by stevegt** [comment]
Same problem in /states -- should send to /notifications.  Will add to PR.

**Comment by maxence-charriere** [comment]
Documentation will be revamped and moved away from this repo.
