### ISSUE TITLE
Is there any way to update/trigger UI from server side?

### ISSUE THREAD

**Issue by garfeng** [maxence-charriere/go-app#779]
Thanks very much for this excellent job.

Now, I am trying to write a desktop app that controls some cameras.

The server side snap images from camera, and then push the images to frontend, then the web app should draw images one by one in canvas, like showing videos.

How to trigger frontend to redraw new images ?

**Comment by alvarolm** [comment]
I would use component updates https://go-app.dev/components#updates
the documentation its pretty helpful

**Comment by garfeng** [comment]
> I would use component updates https://go-app.dev/components#updates the documentation its pretty helpful

@alvarolm Thank you for your reply. I need to refresh UI from backend, not from the frontend wasm program

**Comment by alvarolm** [comment]
> > I would use component updates https://go-app.dev/components#updates the documentation its pretty helpful
> 
> @alvarolm Thank you for your reply. I need to refresh UI from backend, not from the frontend wasm program

In that case I think it depends of the server, can you pull the images via http ?, if that is the case it should be easy.
any way form the front end you have a bunch of options, even using js library:
https://github.com/cemacrr/imageplayer

I believe you may be using the wrong approach to your question, you haven't even explained how you will access the server (protocols and so on)

**Comment by garfeng** [comment]
> 

@alvarolm Thank you very much. I will use websocket to push messages to the frontend, and then, the wasm program will analyze the message and decide how to refresh the UI, such as render the new url of images.
