### ISSUE TITLE
Adding components `onClick` functions in a loop always seems to be the last function written

### ISSUE THREAD

**Issue by amlwwalker** [maxence-charriere/go-app#780]
Hard to describe in the title...

I have a loop, where for each one of my aggregates, I want to add a checkbox and for each checkbox I want to add a unique onClick function.

```go
var switches []app.UI
for _, v := range aggregates {
	switches = append(switches, pComponents.Checkbox(v, v, true, func(ctx app.Context, e app.Event) {	
		fmt.Printf("result.JSValue() %s - %s\r\n", v, err)
	}))
}
   // add switches to DOM
```

I would have died to this hill that this would work, but for some reason `v` is _always_ equal to the last value of aggregates in the list when I click the button

so if aggregates is an array of strings `[]string{"hello", "world", "are", "you", "out", "there}` then whichever of the radio buttons I click on, `v` always prints as `there`. 

I have also got my `Checkbox` function to set the `id` of the element to the value of `v` as I thought perhaps the way to do this is to grab the ID of the current element however I realised I couldn't find an example of how to get the DOM element from the ctx here - please could you show me an example of getting fields/children/children's fields from the `onClick`

I thought it might be something like `el := ctx.JSSrc().JSValue().Get("id")` however that always comes up blank.

I am slightly confused by this as i was sure that this would generate the function per checkBox in the array and each would have their own function, however it seems that they are all somehow receiving the last onClick function.

**Comment by mlctrez** [comment]
@amlwwalker 
https://levelup.gitconnected.com/4-pitfalls-in-go-i-still-occasionally-fall-into-7099eae3ecd1
You should at least be able to fix the "always equal to the last value" part of this question with 1. from the link above.

Not sure about the middle part of your question for getting the id.

**Comment by oderwat** [comment]
Maybe the problem is not in this part of the code, but where you add the handler. You probably need to add a scope to it or change how you set the scope (see #749).

**Comment by mlctrez** [comment]
@amlwwalker 

Here's a better explanation for why.  See 3/4 the way down in the section on Closures:

https://eli.thegreenplace.net/2019/go-internals-capturing-loop-variables-in-closures/#closures

Basically go is re-writing the anonymous function to use a pointer to the variable v.  So it has the same issue as the iteration loop issue when pointers are used.

The fix is just make v a new variable on each loop.  
Also, how to get the id of the element in the onClick() is included in this example.

```go
func (b *Body) Render() app.UI {

	aggregates := []string{"hello", "world", "are", "you", "out", "there"}

	var elements []app.UI
	for _, vLoop := range aggregates {

		// give v a new address on each iteration
		v := vLoop
		el := app.Div().Body(
			app.Input().ID(v).Type("checkbox").OnClick(
				func(ctx app.Context, e app.Event) {
					// how to get id of clicked checkbox
					app.Log("checkbox.ID = ", ctx.JSSrc().Get("id").String())
					app.Log("you clicked", v)
				},
			),
			app.Text(v),
			app.Br(),
		)

		elements = append(elements, el)

	}

	return app.Div().Body(elements...)
}
```

**Comment by amlwwalker** [comment]
awesome thanks you

**Comment by amlwwalker** [comment]
awesome thanks you
