### ISSUE TITLE
Uncaught (in promise) DOMException: Cache.addAll() encountered a network error

### ISSUE THREAD

**Issue by caner-cetin** [maxence-charriere/go-app#786]
![image](https://user-images.githubusercontent.com/92731060/202674955-e3835730-fb04-4211-aff3-3a1a9935fc78.png)
Very strange problem that I couldn't find on google or neither here. Problem started when I added static .css file.

`gh repo clone canercetin-randomguy/amnesia`

`make run`

`http://localhost:3169`

should be enough to replicate.

or just look from here

[code itself](https://github.com/canercetin-randomguy/amnesia/blob/master/main.go)

Help?

**Comment by maxence-charriere** [comment]
Can't reproduce this. Feel free to reopen if it is still an issue.

**Comment by caner-cetin** [comment]
Alrighty. sorry that original code is gone :/
