### ISSUE TITLE
Feature request - cross origin setting for manifest link

### ISSUE THREAD

**Issue by mlctrez** [maxence-charriere/go-app#791]
I have a use case where I would like to include credentials ( in my case cookies ) in the manifest request.

See the gotchas section on this link
https://web.dev/add-manifest/#link-manifest

I've tested this small change locally and it resolves the issue.    

![image](https://user-images.githubusercontent.com/885489/205518981-f25c40aa-02a0-4ef5-b5e2-54020b63af5f.png)

I can submit a PR with the changes but would like some advice:
* How to configure the setting on and off?  Environment variable, app.Handler field, or other?
* Are there other links  ( icon, apple-touch-icon ) that would also need to be considered?
* Have I missed an obvious way to achieve this without code changes?

**Comment by oderwat** [comment]
I am not sure about it, but you may be able to add a second link containing the cross-origin by adding it as `h.RawHeaders`. Not sure about the placement, though.

P.S.: I am curious about the use case. Is it about https://cloud.google.com/iap or another guard?

**Comment by mlctrez** [comment]
I'll check if raw headers works. I'm guessing other manifest link will still be there and cause 401 error that I'm trying to get rid of.

The use case is a reverse proxy I run on my edge to allow access to development instances. 
If you look at the top of my github  [repositories](https://github.com/mlctrez?tab=repositories) it should be there since I just touched up the readme.

**Comment by mlctrez** [comment]
RawHeaders appear last in the `<head>` 
https://github.com/maxence-charriere/go-app/blob/b5c5d9aea1bb47f783d4488ae292a96a1580b3f0/pkg/app/http.go#L783

As suspected, both link hrefs are requested, so the 401 error at my proxy still shows up.

**Comment by oderwat** [comment]
> Not sure about the placement, though.

What I meant that I am uncertain if it will work correctly on the mobile device if one of the links gets blocked. The placement was clear.

I think that the "crossorigin" should be a setting in app. Handler (with a default of empty string) and be used in all the meta link files. That would be compatible to the current state, and it will be most likely that all the links go to the same server anyway.

**Comment by oderwat** [comment]
> If you look at the top of my github [repositories](https://github.com/mlctrez?tab=repositories) it should be there since I just touched up the readme.

Do you talk about the "gossl"? I created a universal server with a lot of different options for SSL / ACME / Connection Limits / Remote IP forwarding and so on for out go-app framework. Just to end up using traefik in production, because of the need of SNI. For development we use Sish for some time now, which suits us perfectly.

**Comment by suntong** [comment]
I guess my reported case is a reverse proxy as well that allows access to internal instances.

> but you may be able to add a second link containing the cross-origin by adding it as h.RawHeaders

So the fix has to be done internally within [go-app](https://github.com/maxence-charriere/go-app) right @oderwat? Are we able to circumvent the issue ourselves meanwhile? thx.

**Comment by oderwat** [comment]
@suntong I do not really understand what you mean. You can always add 'rawHeaders' already.
