### ISSUE TITLE
Automatically reload app and resources in dev mode

### ISSUE THREAD

**Issue by jorgefuertes** [maxence-charriere/go-app#797]
Hi everyone,

I've configured `air` and my `Makefile` to perform an automatic recompiling when I do changes to my code or to my assets (css, sass, images...). But after the successful recompiling then I need to manually reload the PWA to get the update notification and then click on update to really reload the PWA or the assets.

I've set a `DEV_MODE` env var and when its `on` then I do the ctx.Reload, but it happens after a _by hand_ page reload only.

The question is how can I simulate the `livereload` behavior, this is _reload the assets when I'm chaning the sass files or reload the PWA when the code changes_, **with no human interaction**.

Any ideas? Thank you very much.

**Comment by oderwat** [comment]
That is the way it is with the service-worker and the fetch cache. To get an update, it needs to get the information, that there is a new version of the service-worker first. You can force the service-worker to check for updates regularly by setting `AutoUpdateInterval` in `app.Handler`. I set this to 5 seconds with my life reload.

```
    // The interval between each app auto-update while running in a web browser.
    // Zero or negative values deactivates the auto-update mechanism.
    //
    // Default is 0.
    AutoUpdateInterval time.Duration
```

You also need to make sure that you have no static version number, if you set one:

```
    // The version number. This is used in order to update the PWA application
    // in the browser. It must be set when deployed on a live system in order to
    // prevent recurring updates.
    //
    // Default: Auto-generated in order to trigger pwa update on a local
    // development system.
    Version [string](https://go-app.dev/pkg/builtin/#string)
```

BTW: There are other ways to live reload parts of the application, like new CSS. Besides the really full server/clients-based variants, you can also use https://livejs.com/ to make it reload CSS or other assets. But that goes a bit against the PWA idea of having all resources cached and loaded just once, when the version changes.

**Comment by jorgefuertes** [comment]
Thanks for the response, @oderwat, this is very helpfull.

I know its aganist the PWA principles, but I want it just for development mode, because I want to see inmediate CSS changes in my browser, I'm used to that while I'm developing front applications.

Thanks again, I'm giving a try to the ideas you've pointed to me.
