### ISSUE TITLE
GET https://storage.googleapis.com/murlok-github/icon-192.png 404

### ISSUE THREAD

**Issue by lolorenzo777** [maxence-charriere/go-app#798]
Hi,
I'm testing this great framework and following the simple example in the "getting started" section in the doc, I receive this following error in the browser console : `GET https://storage.googleapis.com/murlok-github/icon-192.png 404`

![image](https://user-images.githubusercontent.com/13906379/211047159-720839e0-de1f-4d57-943f-742893047866.png)

What am I doing wrong ? Where this `https://storage.googleapis.com/murlok-github/icon-192.png` comes from ?
Is there some other external connection the framework is doing ?

Thank for your help/answers.

**Comment by mlctrez** [comment]
@lolorenzo777   You're doing nothing wrong.. If you don't set icon(s) in your handler, go-app uses the defaults:

https://github.com/maxence-charriere/go-app/blob/master/pkg/app/http.go#L255

Why the default is now a 404 is another issue that @maxence-charriere will need to resolve.

**Comment by lolorenzo777** [comment]
OK I understand this is required by the PWA manifest. 
![image](https://user-images.githubusercontent.com/13906379/211051610-93700a42-7f7c-4a48-ab37-40e7b0631ed0.png)

Could be interesting to find a way to use such a local ressource for this *default* icon rather than a remote one.

**Comment by oderwat** [comment]
> Could be interesting to find a way to use such a local ressource for this default icon rather than a remote one.

Just add one to the web folder and use that in the `app.Handler`:

```
		Icon: app.Icon{
			Default:    "/web/logo-192.png",
			Large:      "/web/logo-512.png",
			AppleTouch: "/web/logo-192.png",
		},
```

**Comment by maxence-charriere** [comment]
Yes i had to clean up some stuff and deleted the cloud storage that was storing de default icons. Need to define your own one.

**Comment by astrolemonade** [comment]
> Yes i had to clean up some stuff and deleted the cloud storage that was storing de default icons. Need to define your own one.

Can you bundle the go-app logo with the lib or is it too much work for too less?
