### ISSUE TITLE
How to get `aria` or `dataset` from the event handler

### ISSUE THREAD

**Issue by jorgefuertes** [maxence-charriere/go-app#808]
Hi,

I'm sorry to disturb but I can't figure it how to do this. Maybe I'm lacking on syscall/js or just on javascript knowledge, so I apologize in advance.

I have an app.A (anchor) with an OnClick handler to a function, and I'm trying to recover some information need to do the action, for example the action name. I've tried to set that info into the Dataset (no idea how to access it later) or in an `aria` as `Aria("action", "remove")` and I've tried a lot of combinations like this one:

```go
func (p *List) actionClick(ctx app.Context, e app.Event) {
	e.PreventDefault()
	// action := ctx.Src().JSValue().Get("aria-action")
	action := e.Get("target").Get("aria-action")
	app.Log("action:", action)
}
```

Anyone can point me into the right direction? Thanks.

**Comment by oderwat** [comment]
Well. First of I usually don't use values from the Javascript world, when I could use a closure or reference to the Go structure of the context or reference.

But when I want to get something from the DOM and do not find the right way to access it I use `app.Window().Get("console").Call("log", <my go js variable reference>)` which will print the JS object inside of the browser console, so you can use it to debug the value (object). 

Most of the time I just spelled something wrong or find out that the value I thought should be there, is not there in the first place.

I think you should play around with it and dump `ctx.JSSrc()` and `e.Value` to get a better understanding of what happens.

**Comment by jorgefuertes** [comment]
Thanks for the comment, @oderwat, I'd tied to dump it with app.Log but I can only get "object" in console. I'll try this.

How do you pass data from an anchor (for example a dabatase ID) to a handler to execute a removal calling your API? Which is the best practice? Making a function with the IS as argument and return a handler function from here?

Thanks!

**Comment by jorgefuertes** [comment]
Thanks to yours debugging tips I'm allow to know how to get the dataset attributes, just like this:

```go
action := e.Get("target").Call("getAttribute", "data-action")
```

Is this the better way? Thanks a lot!

**Comment by oderwat** [comment]
Yes, I usually create a factory function for the handlers and use the closure to capture the value I want to evaluate in the handler. I dislike using IDs in the DOM when not absolutely needed, but you can use that too.

**Comment by oderwat** [comment]
Well, I guess you need to do it that way. That said, I would not have a 'data-action' in any of my code usually. Why is it there in your code?

BTW: I just published a ToDo-Application example we have lying around for some months to our companies GitHub account. Maybe you get some inspirations there: https://github.com/metatexx/go-app-todo

**Comment by jorgefuertes** [comment]
Thanks, you are very helpful.

**Comment by oderwat** [comment]
I just like go-app, and we try to support it a bit using some of our resources.
