### ISSUE TITLE
Component is loosing its data

### ISSUE THREAD

**Issue by rtrzebinski** [maxence-charriere/go-app#820]
Hi, thank you for developing this wonderful library, I need help with the following issue.

In main I set:

```
app.Route("/", components.NewHome("bar"))
```

Home component code:

```
type Home struct {
	app.Compo
	foo string
}

func NewHome(foo string) *Home {
	return &Home{
		foo: foo,
	}
}

func (h *Home) OnMount(ctx app.Context) {
        // THIS IS AWAYS EMPTY - why?
	log.Println("foo: " + h.foo)
}

func (h *Home) Render() app.UI {
	return app.Div().Body()
}
```

Inside the component, once it is mounted, I'm trying to use some data passed to it via constructor - a `foo` variable which should have a value `"bar"`.

However **it is always empty**, like the component was recreated? I use the WEB browser console to check it.

What might be the reason? Is there any way to pass some data from main to the component?

**Comment by rtrzebinski** [comment]
I create a pull request with steps to reproduce:

https://github.com/rtrzebinski/simple-memorizer-go/pull/2

Steps to reproduce:

```
make dev
make run
```

Open http://localhost:8000 

Check console output - foo value will be empty

**Comment by oderwat** [comment]
> app.Route("/", components.NewHome("bar"))

The second parameter to `app.Route()` is evaluating the **type** of the variable you give.

From the docs:

> Route associates the **type** of the given component to the given path.
> When a page is requested and matches the route, a **new instance** of the given component is created before being displayed.

This means that your Instance with the "bar" parameter just gets thrown away and go-app will create a fresh empty structure for the component when the page is getting requested.

In the next release, there will be `app.RouteFunc()` that will allow you to give a function that creates a new component. This way, you will be able to add data to it earlier.

Until then, you need to initialize your component in another way. This means you need to initialize the fields of the component you need at `OnInit()`, `OnMount()` or `OnNav()`.

**Comment by rtrzebinski** [comment]
Thank you @oderwat for a quick answer!

I understand the reason and I have my sanity back.

```
Until then, you need to initialize your component in another way. This means you need to initialize the fields of the component you need at OnInit(), OnMount() or OnNav().
```

How would I use it to obtain some data from config (main), could you please point me to some example?

**Comment by maxence-charriere** [comment]
You can define env variable in the handler.

**Comment by oderwat** [comment]
@rtrzebinski as maxence says. If you want to send variable data from the backend (starting program) you can either:

1. Add it to [app.Handler](https://go-app.dev/reference#Handler).Env and simply access it from the frontend.
2. Use a backend endpoint and get it through a **request** to the URL
3. Make it a cache able resource and get it through a **request** to the URL

The request can be a real request using httpclient (http.fetch). We mostly use NATS now. I demonstrated that in my [go-nats-app](https://github.com/oderwat/go-nats-app) example. While this example is mainly targeting external NATS servers, there is an example by @mlctrez on how to [proxy the ws endpoint](https://github.com/mlctrez/goapp-natsws), so it is in the same domain. You may want to read through the issues in our repos too if you are interested in that kind of backend.

But you can also use something simple like an added script or extra headers (in app.Handler) which you then can query from the DOM using [JavaScript](https://go-app.dev/js#include-js-files).

If it is some static information that is known at compile time, you can just add it globally or locally into your component code.

**Comment by rtrzebinski** [comment]
@oderwat @maxence-charriere That solved my issue, than you so much!
