### ISSUE TITLE
How to perform an action on keyboard key press

### ISSUE THREAD

**Issue by rtrzebinski** [maxence-charriere/go-app#821]
More of a question that the issue really: how to catch the event when user is pressing a keyboard key - space bar for instance - and perform an action upon it?

I am trying with:

```
	ha := func(ctx app.Context, e app.Event) {
		app.Log("key pressed")
	}
	app.Window().AddEventListener("keyPress", ha)
```

But it seem to catch mouse buttons only, not keyboard keys.

**Comment by oderwat** [comment]
Did you try "keydown", "keyup", "keypress". Should work as usual. That said, I usually only use the "OnKeyPress()", "OnKeyDown()", "OnKeyUp()" and especially "OnInput()" inside a component.

**Comment by rtrzebinski** [comment]
@oderwat `keyup` worked, thank you!

> That said, I usually only use the "OnKeyPress()", "OnKeyDown()", "OnKeyUp()" and especially "OnInput()" inside a component.

Would you be so kind and share an example code of how to do it?

Currently I have:

```
func (h *Home) OnMount(ctx app.Context) {
	ha := func(ctx app.Context, e app.Event) {
		app.Log("key pressed")
	}
	app.Window().AddEventListener("keyup", ha)
}
```

I wonder if there is a better way.

**Comment by rtrzebinski** [comment]
I figured out how to get a key pressed:

```go
	ha := func(ctx app.Context, e app.Event) {
		app.Log("key pressed")
		app.Log(e.Get("code"))
	}
```

**Comment by oderwat** [comment]
I am not at my computer, but the difference is that I usually only need the event handler on a text box or similar. So, I added that event handler in the Render() method of the component. Adding it when you mount should probably remove it "OnDismount()" if that happens, so you do not run into dead data of that component.

**Comment by rtrzebinski** [comment]
Thank you so much @oderwat !

Here is my commit for reference -> https://github.com/rtrzebinski/simple-memorizer-4/commit/aa5d08ca1ff2d0959145c5ba06911cfc1f816c57

Have a good evening :)
