### ISSUE TITLE
Question: how to add rows to existing table

### ISSUE THREAD

**Issue by rtrzebinski** [maxence-charriere/go-app#824]
Hi, I can not find this in the documentation, so asking here:

I have a component, that displays a html table.

How do I add / edit / delete elements dynamically? For instance when loaded from the API.

```go
// The Render method is where the component appearance is defined.
func (h *Exercises) Render() app.UI {
	h.ui = app.Div().Body(
		&Navigation{},
		app.Table().Style("border", "1px solid black").Body(
			app.Tr().Style("border", "1px solid black").Body(
				app.Th().Style("border", "1px solid black").Body(
					app.Text("Question"),
				),
				app.Th().Style("border", "1px solid black").Body(
					app.Text("Answer"),
				),
			),
			&ExerciseRow{},
			&ExerciseRow{},
		),
	)

	return h.ui
}

// The OnMount method is run once component is mounted
func (h *Exercises) OnMount(ctx app.Context) {
	// what do I do here in order to add more ExerciseRow ?
}
```

**Comment by oderwat** [comment]
You need to model your data inside the component, and then you just change that data. When this happens over the "normal" ways (events, calling defer), it will automatically render the new view of that component automatically. If you do stuff outside what go-app is watching, you may need to trigger an update calling `c.Update()` where c is your component.

So, for your example, you will not add the `ExerciseRow{}` in your render that way. But you will use something like this:

```
app.Range(c.answers).Slice(func(i int) app.UI {
			return app.Tr().Body(
				app.Td().Class("border border-slate-300 p-2").
					Body(app.Text(c.answers[i].StreamID)).
					OnClick(onStreamIdClick),
				app.Td().Class("border border-slate-300 p-2 text-right").
					Body(app.Text(c.answers[i].Stream)),
				app.Td().Class("border border-slate-300 p-2").
					Body(app.Text(c.answers[i].Subject)),
				app.Td().Class("border border-slate-300 p-2").
					Body(app.Text(c.answers[i].Params)),
				app.Td().Class("border border-slate-300 p-2").
					Body(app.Text(c.answers[i].CreatedAt.Format("02.01.2006 15:04"))),
			)
		}),
```

**Comment by rtrzebinski** [comment]
@oderwat Thank you for answering so quickly!

So `c.answers` in you example is a slice (of `app.UI`?) and if I update that slice, UI will be changed accordingly?

**Comment by oderwat** [comment]
Yes, `answers` in that example is just a slice of a struct type. Not a component. I usually do not add components inside the "model", but one can do that too.

We have an example [here](https://github.com/metatexx/go-app-todo) that may be helpful.

**Comment by rtrzebinski** [comment]
@oderwat Amazing, the above code did the trick, thank you!

```go
package components

import (
	"github.com/maxence-charriere/go-app/v9/pkg/app"
)

type Exercises struct {
	app.Compo
	rows []*ExerciseRow
}

// The Render method is where the component appearance is defined.
func (h *Exercises) Render() app.UI {
	return app.Div().Body(
		&Navigation{},
		app.Table().Style("border", "1px solid black").Body(
			&ExerciseHeader{},
			app.Range(h.rows).Slice(func(i int) app.UI {
				return h.rows[i]
			}),
		),
	)
}

// The OnMount method is run once component is mounted
func (h *Exercises) OnMount(ctx app.Context) {
	h.rows = append(h.rows, &ExerciseRow{})
	h.rows = append(h.rows, &ExerciseRow{})
	h.rows = append(h.rows, &ExerciseRow{})
	h.rows = append(h.rows, &ExerciseRow{})
}
```

**Comment by rtrzebinski** [comment]
Commit for the reference -> https://github.com/rtrzebinski/simple-memorizer-4/commit/a9cad6f6d14a4909cd148f7a10827e0310e837bd
