### ISSUE TITLE
How to remove window event listener?

### ISSUE THREAD

**Issue by rtrzebinski** [maxence-charriere/go-app#832]
I use this function:

```
func (w *browserWindow) AddEventListener(event string, h EventHandler) func() {
	return func() {}
}
```

To bind events on keyup, like:

```
app.Window().AddEventListener("keyup", func(ctx app.Context, e app.Event) {
  // sent some HTTP request on key press
}
```

It works fine, however every time component is re-loaded, a new event of the same type is added to the stack.

So if I loaded the component 10 times, and I press the button, an event (HTTP call) will be run 10 times - not good.

I found a way to run this code only once with `sync.once.Do(onceBody)` but the event handler still works everywhere in the app, not just on one page (component) that I need it.

Question - how do I de-register these events? Can't see a method for that in the interface, perhaps there is some other, manual way to achieve this?

**Comment by oderwat** [comment]
From the docs:

`AddEventListener` subscribes a given handler to the specified event. **It returns a function that must be called to unsubscribe the handler and release allocated resources.**
```

**Comment by rtrzebinski** [comment]
I must have missed that, thank you @oderwat will give it a try!

**Comment by rtrzebinski** [comment]
Worked very well, commit for the reference -> https://github.com/rtrzebinski/simple-memorizer-4/commit/23d39489332908c052fc0ddddf1363f7205151d6
