### ISSUE TITLE
Form value binding messed up when using app.if

### ISSUE THREAD

**Issue by ystyle** [maxence-charriere/go-app#842]
```go
type hello struct {
	app.Compo
	Switch bool
	name   string
	path   string
}

func (h *hello) OnClick(ctx app.Context, e app.Event) {
	fmt.Printf("switch: %v, name: %s, path: %s\n", h.Switch, h.name, h.path)
	h.Switch = !h.Switch
}

func (h *hello) Render() app.UI {
	return app.Div().Body(
		app.Button().Text("switch").OnClick(h.OnClick),
		app.If(h.Switch,
			app.Input().Type("text").Name("name").Placeholder("name").Value(h.name).OnChange(h.ValueTo(&h.name)),
		).Else(
			app.Input().Type("text").Name("path").Placeholder("path").Value(h.path).OnChange(h.ValueTo(&h.path)),
		),
	)
}
```
As in the above code, the actual binding values are all on the path
![Peek 2023-07-10 11-53](https://github.com/maxence-charriere/go-app/assets/4478635/1ee28aef-5564-4435-9ca8-387ab29923e0)

**Comment by maxence-charriere** [comment]
Try unexport your `Switch`, here the variable is reset by the default value at each update.

**Comment by ystyle** [comment]
still the same problem
![Peek 2023-07-10 14-06](https://github.com/maxence-charriere/go-app/assets/4478635/d3d001af-b7a4-4dba-a078-215aed0c8101)

**Comment by oderwat** [comment]
See #632 ...I believe that because both conditional code paths are always executed, you always `h.ValueTo(&h.path)`. I still think that app.If() should be deprecated.

**Comment by ystyle** [comment]
So how can we switch between different form areas? Similar to pressing tabs to divide forms and form items to display and hide

**Comment by maxence-charriere** [comment]
Seem @oderwat is right. You could create 2 event handlers for each of your usecase without using `ValueTo`.
