### ISSUE TITLE
Makefile for Windows

### ISSUE THREAD

**Issue by BElluu** [maxence-charriere/go-app#843]
Hello,
In documentation I see 
```
build:
	GOARCH=wasm GOOS=js go build -o web/app.wasm
	go build

run: build
	./hello
```

but when I run this makefile I got error
![image](https://github.com/maxence-charriere/go-app/assets/11333925/a39f6427-0444-45f0-86f6-b0e7ce78599a)

I think this problem is because I develop on windows. Someone can tell me, how should I build app?

**Comment by oderwat** [comment]
This is using Unix shell syntax (bash / zsh), I wonder what 'make' is running it. You could try using "set" on an extra line

```bat
set GOARCH=wasm
set GOOS=js
go build -o web/app.wasm
```

Disclaimer: I am not a Windows guy (anymore). We usually don't compile for Windows on Windows. Instead, we cross compile using an [Earthly](https://earthly.dev/) builder on Linux from a Mac, which our standard developer system. I think it would work with a Makefile, if you use something like CygWin (what I used in the past). When on Windows, I usually have WSL2 (and Docker) running for development. But, I am certain, that the "Windows" people here can tell you their best practices.

**Comment by suntong** [comment]
_Easiest_ way is to run `make` under Git Bash, as you need Git Bash to use git under Window anyway.

**Comment by oderwat** [comment]
I think that using [Mage](https://magefile.org/) is actually a nicer option than using make in general. This will work on Windows too and even without a local mage installation (which is trivial when running Go). That way, it is fully independent of the shell. I used this for the [go-nats-app](https://github.com/oderwat/go-nats-app) example. The example shows the two stage compilation and can easily be extended and reused for other projects. We have some large ones which can create docker images, handle deployment and auto-recompile on code changes and such stuff. Besides that, I would recommend using [Earthly](https://earthly.dev/) when projects get larger. This is our solution for "everything" (CI/CD) with occasional extra scripts (as the build environment is containerized, it will allow all the nifty Linux tools) or `magefiles`. This should also work on Windows (we are on Mac/Linux/WSL2).

**Comment by tg21** [comment]
I have been using powershell on windows and it seems to be working fine.
If someone is still trying to find something simple then just create a build.ps1 with following code in your project folder
```
$Env:GOOS = "js"; 
$Env:GOARCH = "wasm"; 
go build -o web/app.wasm;
Remove-Item Env:GOOS
Remove-Item Env:GOARCH
go build;
```
