### ISSUE TITLE
More examples please

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#848]
> I have no good example app in a public repo, but you could check out https://github.com/oderwat/go-guess-the-number-app/ which I wrote quite some time ago, as I started exploring go-app. I think we should make some of our internal, training repos available. Maybe in the new year, the team is mostly on vaccation already :)

_Originally posted by @oderwat in https://github.com/maxence-charriere/go-app/issues/794#issuecomment-1359996713_

So I've read through the doc, from https://go-app.dev/getting-started to https://go-app.dev/reference, where it gets into the deep water suddenly...

Wow, I haven't even finished composing my question and you've already gave me the answer, @oderwat! Amazing!! Thanks!!!

**Comment by oderwat** [comment]
From us/me there are some more:

https://github.com/metatexx/go-app-todo
https://github.com/metatexx/go-app-pkgs
https://github.com/metatexx/mxx/tree/main/natswasm
https://github.com/oderwat/go-nats-app
https://github.com/oderwat/rodgoapp
https://github.com/oderwat/go-guess-the-number-app/
