### ISSUE TITLE
HTML Rendering

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#849]
Say I have `app.Text(p)`, and I want to use HTML markups in my string `p`, like `<b>`, `<i>` etc.

How can I do it please?

**Comment by suntong** [comment]
Ah, use app.Raw() instead -- https://go-app.dev/reference#Raw.

**Comment by oderwat** [comment]
Well, you usually do now want to use `app.RAW()`. It will not play nice with updating nodes through render. It basically lets the browser parse and apply all of the code each time render is called. So you should not rely on that "a lot".
