### ISSUE TITLE
How to get host IP address from request context

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#850]
Basically the same ask as 
https://stackoverflow.com/questions/62678542/determine-ip-to-which-http-request-was-addressed-in-http-handler, but for go-app --

For a server / host with multiple IP addresses, how can I determine from the request which network interface (or IP address) it was sent to?

I have the following setup:

The request is made to the server using one of its IP addresses - let's say either `192.168.0.1`(on eth0) or `192.168.0.2`(on eth1). The server is listening on all addresses on the local machine (e.g. `http.ListenAndServe(":8080", nil)`).

How can I determine the IP address that the client access to, when both front and back ends are in [go-app](https://github.com/maxence-charriere/go-app)? And I need to get that IP in the `OnMount(Context)` function:

https://github.com/maxence-charriere/go-app/blob/1f671917400880c5dadc7558d28edabcfa2297e3/pkg/app/component.go#L81-L83

I tried to print its `ctx app.Context`, but I don't think I can make use of it, as I only got this:

`{Context:context.Background.WithCancel src:0x87c840 jsSrc:{Value:{_:[] ref:9221120241336057903 gcPtr:0x810848}} appUpdateAvailable:false page:{url:<nil> resolveStaticResource:0x1ff00000} disp:0x86ca20}
`

Thanks

**Comment by oderwat** [comment]
Go-App uses the Go standard library HTTP handler and therefor you get the IP in the same way.

BUT: The context inside your front-end components does not accesses anything through IP. The client is not accessing the server after the initial loading at all if you do not write code that does that. I think you miss how a [PWA setup works](https://go-app.dev/lifecycle#lifecycle-overview). A big part of having a PWA is, that it does work offline too. It usually also does not matter from where your PWA content was served. If you need to give information about backend IPs to the frontend, you can use `app.GetEnv()` and set it in the field `Env` of [app.Handler](https://go-app.dev/reference#Handler).

**Comment by suntong** [comment]
Wow, amazing response speed!

Now I understand what `OnAppUpdate` is actually for.

> The client is not accessing the server after the initial loading at all 

That implies that the `OnMount(Context)` function only happens in app's *first loading* right?

So, in order for *app recurrent loadings* case to work, which occurs when a user is coming back on the app, to get the IP address that the client access to, is the best place in the `Render()` function instead, or anywhere else?

**Comment by suntong** [comment]
To bring the difficulties one level down, instead of getting the IP address that the client access to, say I use `app.GetEnv()` to get the server's working IP, now, besides putting in the field `Env` of `app.Handler`, is it OK to put into app control struct as well?

https://go-app.dev/getting-started

```go
type hello struct {
	app.Compo
	serverIP string
}

. . .

func main() {
	// The first thing to do is to associate the hello component with a path.
	//
	// This is done by calling the Route() function,  which tells go-app what
	// component to display for a given path, on both client and server-side.
	myApp := &hello{serverIP: true_value}
	app.Route("/", myApp)
. . .
```

Would such value be passed to all front ends as well?

**Comment by oderwat** [comment]
> That implies that the `OnMount(Context)` function only happens in app's _first loading_ right?

Not really: It happens every time the component gets mounted. Which is when the page was loaded for your first root component. The one you have in the frontend Route that applies.



> Would such value be passed to all front ends as well?

No, because the value you give to the `app.Route()` will only be used as an example of the type to create for the component. It does not carry over the state. You may use the fairly new [app.RouteFunc()](https://go-app.dev/reference#RouteFunc) that creates the actual component when mounted, together with a global variable (or an anonymous closure) that contains the value. But actually, I did not yet tried that myself.

**Comment by suntong** [comment]
Thanks for the swift reply. I'll try tomorrow, so closing it now FTTB...
