### ISSUE TITLE
OnPaste() to accept image paste and show as such

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#852]
Hi,

This may be slightly OT, but I appreciate if anyone can show me how [go-app](https://github.com/maxence-charriere/go-app) knows that what pasted in is actually an image paste, then show the image as the result.

The following code accepts pasting paragraphs and shows as such. I prepared it for you to easily start with, but feel free of using it or not. If you can make it accepting ether paragraphs or image, then it'll be super. Thanks.

```go
package main

import (
	"log"
	"net/http"

	"github.com/maxence-charriere/go-app/v9/pkg/app"
)

// hello is a component that displays a simple "Hello World!". A component is a
// customizable, independent, and reusable UI element. It is created by
// embedding app.Compo into a struct.
type hello struct {
	app.Compo
	textStr string
}

// The Render method is where the component appearance is defined. Here, a
// "Hello World!" is displayed as a heading.
func (h *hello) Render() app.UI {
	return app.Div().Body(
		app.If(h.textStr != "",
			app.Textarea().Text(h.textStr).Cols(80).ReadOnly(true),
		).Else(
			app.P().Body(
				app.Textarea().
					Text(h.textStr).
					Spellcheck(true).
					Style("border", "solid 1px orange;").
					Placeholder("Paste your text").
					AutoFocus(true).
					OnChange(h.ValueTo(&h.textStr)),
			),
		),
	)
}

// The main function is the entry point where the app is configured and started.
// It is executed in 2 different environments: A client (the web browser) and a
// server.
func main() {
	// The first thing to do is to associate the hello component with a path.
	//
	// This is done by calling the Route() function,  which tells go-app what
	// component to display for a given path, on both client and server-side.
	app.Route("/", &hello{})

	// Once the routes set up, the next thing to do is to either launch the app
	// or the server that serves the app.
	//
	// When executed on the server-side, RunWhenOnBrowser() does nothing, which
	// lets room for server implementation without the need for precompiling
	// instructions.
	app.RunWhenOnBrowser()

	// Finally, launching the server that serves the app is done by using the Go
	// standard HTTP package.
	//
	// The Handler is an HTTP handler that serves the client and all its
	// required resources to make it work into a web browser. Here it is
	// configured to handle requests with a path that starts with "/".
	http.Handle("/", &app.Handler{
		Name:        "Hello",
		Description: "An Hello World! example",
	})

	log.Println("Listening on http://:8000")
	if err := http.ListenAndServe(":8000", nil); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by mlctrez** [comment]
@suntong 

Here's an example of how to you might integrate go-app and clipboard events. This component can handle both image and text data, although the application only uses images.

https://github.com/mlctrez/imgtofactbp/blob/master/components/clipboard/clipboard.go

The parent application also shows how to render the pasted image into an existing element.

Hop this helps.

**Comment by suntong** [comment]
OMG, I was totally shooting into the dark, with no hope that people can answer. 

"Amazing!", I have to say, of the go-app and the golang community in total.

Thanks

**Comment by suntong** [comment]
> The parent application also shows how to render the pasted image into an existing element.

I gave it a try (finally), but when pasting an image, nothing happens.

- [this is what I added](https://github.com/suntong/go-app-demos/commit/d0bb211b25626d3c53d3158f18b95c969222132a) to render the pasted image
- [this is the whole file](https://github.com/suntong/go-app-demos/blob/master/0B3-textarea/main.go

would you see what I'm missing please?

**Comment by mlctrez** [comment]
You missed two items from the original code - the clipboard component needs to be included in the UI and must be initialized with an ID:

Your render method modified with these changes:
```go

func (uc *appControl) Render() app.UI {
	if uc.clipboard == nil {
		uc.clipboard = &clipboard.Clipboard{ID: "clipboard"}
	}
	return app.Div().Body(
		uc.clipboard,
		app.If(uc.textStr != "",
			app.Textarea().Text(uc.textStr).Cols(80).ReadOnly(true),
		).Else(

```

**Comment by suntong** [comment]
> the clipboard component needs to be included in the UI and must be initialized with an ID:

Ah, yes, I've even read about it 😊😊😊 

> Your render method modified with these changes

BINGO!!! Thanks a thousand. I'm on cloud nine now...
