### ISSUE TITLE
go-app on Netlify

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#854]
Parallel to #744, has anyone managed to have go-app PWA serviced by Netlify hosting the go-app binary?

Any pointers to wrapping the Netlify/lambda handler and responses to getting a working PWA?

Reason: seems that Netlify building is much much simpler than lambda (and free too) --  
https://blog.carlmjohnson.net/post/2020/how-to-host-golang-on-netlify-for-free/

**Comment by oderwat** [comment]
Nope, but did you consider Fly.io ([go example](https://fly.io/docs/languages-and-frameworks/golang/))?

**Comment by suntong** [comment]
OK, I took a look, seems that the go source is similar to the Netlify example I gave above, but the building part is much much more complicated. 

Were you able to make go-app work on Fly.io @oderwat? Any working sample code please?

**Comment by oderwat** [comment]
@suntong nope, we have a server farm ourselves. But I think a co-worker did it. I will ask around.

**Comment by suntong** [comment]
I'm closing it, because after four full days trying to find solutions for hosting go-app on public cloud providers like AWS, Netlify etc, I decided to go back to my VPC, despite how busy it is.

If anyone also interested in it, ping me and I'll open it again.
