### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#855]
I'm getting such `No 'Access-Control-Allow-Origin' header is present on the requested resource` error when trying to host it on a tiny cloud. 

For the default README sample, this is all that I get:

> ![image](https://github.com/maxence-charriere/go-app/assets/422244/5073e49f-03e0-4b6b-9bba-77c203a86b28)

My guess is that the front html file and web/app.wasm are somehow hosted on different internal sites, loading the `web/app.wasm` in full was OK, but get blocked by CORS policy afterwards. Anyway, how to fix it please?

**Comment by suntong** [comment]
I found an article on how to fix the issue with the plain golang http, 
https://www.stackhawk.com/blog/golang-cors-guide-what-it-is-and-how-to-enable-it/
but I'm unable to apply it to go-app.

**Comment by suntong** [comment]
Found an old open issue #791 that might be closely related to mine above, as the CORS policy violation of my case is `manifest.webmanifest` as well.

**Comment by oderwat** [comment]
There is not really a difference to a "normal" HTTP Server here. We use the CORS middleware of the Chi router but you can write that in some lines yourself. I have no time, but I asked a friend "Chat GPT4" and he told me this:

To handle CORS with the "go-app" package, which is a Go library for building progressive web applications (PWAs), you need to set up CORS on the server-side just like in a standard Go web application. The difference is that the "go-app" package uses the WebAssembly-based frontend, and it communicates with the backend server through HTTP requests.

Here's how you can enable CORS for the "go-app" package:

1. Import the necessary packages:

```go
package main

import (
    "net/http"

    "github.com/maxence-charriere/go-app/v8/pkg/app"
)
```

2. Create your "go-app" handler:

```go
type MyApp struct {
    app.Compo
}

func (a *MyApp) Render() app.UI {
    // Your frontend rendering logic goes here
}
```

3. Add a middleware to enable CORS:

```go
func enableCORS(handler app.Handler) app.Handler {
    return func(ctx app.Context) error {
        // Allow requests from any origin
        ctx.Response.Header().Set("Access-Control-Allow-Origin", "*")

        // Add other CORS headers as needed
        ctx.Response.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
        ctx.Response.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")

        // Check if the request method is OPTIONS (preflight request)
        if ctx.Request.Method == "OPTIONS" {
            return nil
        }

        // Call the actual "go-app" handler
        return handler(ctx)
    }
}
```

4. Register your "go-app" handler with the "go-app" package, wrapped with the CORS middleware:

```go
func main() {
    myApp := new(MyApp)
    app.Handle("/", enableCORS(myApp))

    // Start the server
    app.Run(":8080")
}
```

In this example, the `enableCORS` middleware is applied to the "go-app" handler, which is implemented as `MyApp`. The middleware adds the necessary CORS headers to the response before passing it to the frontend.

Note: It's important to be cautious about allowing requests from any origin (`Access-Control-Allow-Origin: *`) in a production environment. For production use, you should specify the allowed origins explicitly based on your requirements.

**Comment by suntong** [comment]
Wow, didn't realized Chat GPT4 can be so intelligent. Maybe I should form a habit of asking it each time first, :).

Seems pretty straightforward, but I'm closing it without checking, because after four full days trying to find solutions for hosting go-app on public cloud providers like AWS, Netlify etc, I decided to go back to my VPC, despite how busy it is. 

Thanks again for the code, I may revisit it someday...
