### ISSUE TITLE
[online doc feature req] Visible linking urls

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#856]
Please provide visible linking urls to each section in the online doc. Like in
https://go-app.dev/components

If I want to give a direct url to the "LIFECYCLE EVENTS" section, there is no visible linking that I can make use of. I know some of the function has such visible linking symbols, please make it applicable to all sections, not just function names. thx.

**Comment by mlctrez** [comment]
@suntong  - 

The url not loading *might* be an issue with chrome and AdBlock.   Loading the url in incognito mode works for me.

@maxence-charriere is maintaining all of this for free, so check if blocking ads might be the issue.

- mlctrez

**Comment by suntong** [comment]
> The url not loading _might_ be an issue with chrome and AdBlock.

I think you understand my question incorrectly, as I have no problem loading the url. Please reread my OP.

**Comment by mlctrez** [comment]
https://go-app.dev/components#lifecycle-events works correctly for me.

**Comment by suntong** [comment]
The problem is, where do you get such visible linking url?

**Comment by mlctrez** [comment]
Ahh.  Visible linking as in the link is placed next to the title of the section. That could possibly be added, but the same URL is present by selecting the navigation menu link.

**Comment by suntong** [comment]
> Visible linking as in the link is placed next to the title of the section. That could possibly be added, 

Thanks.

> but the same URL is present by selecting the navigation menu link.

If by "navigation menu" you meant the three line symbol at ULH corner of the doc page, then https://go-app.dev/components is the only level I can see there, no sub menu/links under it.

**Comment by mlctrez** [comment]
This navigation menu is present on desktop views of the go-app documentation. Mobile and narrow screens may not have this.

![select](https://github.com/maxence-charriere/go-app/assets/885489/f33f4e50-d30c-4136-a50e-aef48d83fc4b)

**Comment by maxence-charriere** [comment]
Hey there,
Thanks for all the feedback.

The menu is there depending on the size of the screen.

I know i’m not really active recently but I m preparing some work to overhaul the documentation, and evaluating whether to release a new major version that fix the not so intuitive api feedback.

Sent from my iphone

On Aug 3, 2023, at 1:03 PM, Matt Crawford ***@***.***> wrote:

﻿

This navigation menu is present on desktop views of the go-app documentation. Mobile and narrow screens may not have this.

[select]<https://user-images.githubusercontent.com/885489/258004656-f33f4e50-d30c-4136-a50e-aef48d83fc4b.png>

**Comment by suntong** [comment]
> The menu is there depending on the size of the screen.

Ah, I'm still having a mindset of viewing a static help docs. 

Alright, I'm good now and closing it.
