### ISSUE TITLE
[online doc feature req] Searching

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#857]
Please provide searching capability to the online doc.

Like for trying to solve #855 myself, I want to search for "`CORS`" in the online doc, but that seems impossible for me now.

**Comment by oderwat** [comment]
Yes, the `go-app.dev` page is a thing of its own. I guess that there is too limited time for the developer to create such a search. I never used the static-pages or doc generation, so I have no idea on how hard it would be to add a text indexer and routing for results. That could be an interesting project, but I have no time for that.

For "documentation" I actually use the source code of Go-App itself, inside GoLand ;-)

**Comment by maxence-charriere** [comment]
This will moved out of the repo. closing it.
