### ISSUE TITLE
[online doc feature req] Code copying

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#858]
More and more sites are offering code copying features to allow people to copy the demo code with a single mouse click. Too many sites are do that, like in https://www.cloudskillsboost.google/focuses/3563?parent=catalog:

> ![image](https://github.com/maxence-charriere/go-app/assets/422244/ef3db3cd-883e-4be0-9313-f62fcec6af28)

Can we have that as well in our online doc pls?

**Comment by maxence-charriere** [comment]
Good idea! Doc will be moved out of there but I keep this one in mind!
