### ISSUE TITLE
Javascript Interoperation

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#859]
So I've checked https://go-app.dev/js#intro page, but I'm still not too clear on how to invoke Javascript from go-app.

I've provided an almost working example [here](https://github.com/suntong/go-app-demos/tree/master/0B2-codecopy). In its [test](https://github.com/suntong/go-app-demos/tree/master/0B2-codecopy/test) folder, the Javascript invoked fine _from html page_. 

However, the same content, when _rendered with go-app_, the Javascript was not able to be invoked.

I tried to ask  ChatGPT for an answer, and this is what I got (handling onclick using go-app):

```
func (m *CodeBlockModel) Render() app.UI {
	return app.Div().Body(
		app.Button().
			OnClick(m.OnCopy).
			Body(
				app.Img().Src("copy-icon.svg").Alt("Copy Icon"),
			),
		app.Pre().Body(
			app.Code().Text(m.Code),
		),
	)
}

func (m *CodeBlockModel) OnCopy(ctx app.Context, e app.Event) {
	tempInput := app.Window().Document().CreateElement("textarea")
	tempInput.Set("value", m.Code)
	app.Window().Document().Body().AppendChild(tempInput)

	tempInput.Call("select")
	app.Window().Document().Call("execCommand", "copy")

	app.Window().Document().Body().RemoveChild(tempInput)

	fmt.Println("Code copied!")

	// Trigger a model update to change the button state
	m.Update()
}
```

However, I cannot even get it compiles. 

Sorry this is a bit OT. Anyone can help please?

**Comment by mlctrez** [comment]
@suntong 

See https://github.com/mlctrez/imgtofactbp/blob/master/components/clipboard/clipboard.go#L41 for an alternate method for placing text into the clipboard using the window.navigator.clipboard api.   I think this is what you're trying to do.

**Comment by suntong** [comment]
Wow, amazing response speed!

**Comment by suntong** [comment]
> alternate method for placing text into the clipboard using the window.navigator.clipboard api

I gave it a try (finally), but nothing get copied on click.

- [this is what I added](https://github.com/suntong/go-app-demos/commit/9a5a2c5750ac0e10d7c4a24bc4c28e9c772d9816) to make use of it
- [this is the whole file](https://github.com/suntong/go-app-demos/blob/master/0B2C-codecopy/main.go)

would you see what I'm missing please?

BTW, on UI rendering, I think the code is equivalent to the previous version (before the change), however [the previous version](https://github.com/suntong/go-app-demos/blob/master/0B2-codecopy/main.go) have the "Copy code" button properly located, while my new modification somehow get it misplaced, and I cannot think of any reason, other than translating `app.Raw` into the `app.Button()`. Anybody know how to fix that as well please?

**Comment by mlctrez** [comment]
Your code example works for me.. Clicking the button results in the code text block being present in the clipboard.

There are some broken symbolic links in your repository that result errors loading the service worker:

`web/script.js -> ../test/script.js`
`web/styles.css -> ../test/styles.css`

**Comment by suntong** [comment]
> There are some broken symbolic links in your repository

Ops, yeah, thx, fixed now.

> Your code example works for me.. Clicking the button results in the code text block being present in the clipboard.

Oh, I tried to view different X selections, including "primary" XA_PRIMARY (default), "secondary"  for  XA_SECONDARY  or  "clipboard" for XA_CLIPBOARD, none is replaced with the code text block.

Is any of your env different from mine pls:

```sh
$ uname -rm
6.1.0-9-amd64 x86_64

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

$ apt-cache policy google-chrome-stable
google-chrome-stable:
  Installed: 114.0.5735.133-1
  Candidate: 115.0.5790.170-1
  Version table:
     115.0.5790.170-1 500
        500 https://dl.google.com/linux/chrome/deb stable/main amd64 Packages
 *** 114.0.5735.133-1 100
        100 /var/lib/dpkg/status
```

**Comment by mlctrez** [comment]
I'm not sure about the X selections that you posted.  
For me, pasting into a text editor ( or console ) resulted with the correct result.

**Comment by oderwat** [comment]
@suntong You are running the browser on Debian? A quick search gave me: https://www.reddit.com/r/gnome/comments/11lrn4j/chromes_clipboard_is_getting_broken_under_linux/

Did you try another browser or OS yet?

@mlctrez I guess you are not testing it with Google-Chrome on Linux?

**Comment by suntong** [comment]
> About the clipboard and calling JavaScript. In one of our projects, I do this:

That works like a charm! Thanks for the high-quality production-grade code!!!

For anyone who might be benefit from it, the fully working code is at  
https://github.com/suntong/go-app-demos/tree/master/0B2A-codecopy

**Comment by suntong** [comment]
> Did you try another browser or OS yet?

I don't have any other browsers on three of my Linux machines, but I do have two browsers on my Android, which I tried, but neither is working. One is Google-Chrome.

@oderwat would you give it a try at your end please?
https://github.com/suntong/go-app-demos/tree/master/0B2C-codecopy

```sh
$ make run
GOARCH=wasm GOOS=js go build -o web/app.wasm
go build -o ./boostrap
./boostrap
2023/08/14 10:49:55 Listening on http://:8000
```

Thanks a lot.

@mlctrez what OS and which browser are you using? thx.

**Comment by mlctrez** [comment]
@suntong I'm using Chrome Version 115.0.5790.170 on Ubuntu 22.04
The original codebase is running at https://mlctrez.github.io/imgtofactbp/ if you need another point to test with.

**Comment by suntong** [comment]
Strange, I upgraded my google-chrome-stable from v114.0.5735.133-1 to v115.0.5790.170-1 and still NOK.

> The original codebase is running at https://mlctrez.github.io/imgtofactbp/ if you need another point to test with.

_"Clicking on the copy blueprint button will place the blueprint string into the clipboard"_ Oh, even that doesn't work for me. @oderwat would you give it a try at your end please, as I have _now_ tried on my Debian Desktop, Android Mobile and Win 10 Chrome Version 115.0.5790.170. None of them are working for me. Thanks

**Comment by mlctrez** [comment]
@suntong   
For the https://mlctrez.github.io/imgtofactbp/ site, make sure you paste an image from the clipboard and select some sizes and types in the check boxes, otherwise the copy button does nothing.
You can check in the JS console for logging to confirm.

**Comment by suntong** [comment]
Ah, yes, the https://mlctrez.github.io/imgtofactbp/ site is working for me now. I only pasted an image before.
