### ISSUE TITLE
How to download a file?

### ISSUE THREAD

**Issue by rtrzebinski** [maxence-charriere/go-app#860]
I'm working on a CSV export feature, how can I make the client (browser) to download a file in go-app?

**Comment by oderwat** [comment]
If you have a backend, you need to add a router/handler "in front" of the Go-App router. If you do not want to use the backend (which is what I usually want) you can do that in the same way as all other PWAs do it. See https://stackoverflow.com/questions/3665115/how-to-create-a-file-in-memory-for-user-to-download-but-not-through-server to get an idea on how to implement it.

**Comment by rtrzebinski** [comment]
@oderwat Thank you, I have a backend, I can create a route that will build that file, so I only need to add a proper headers to the HTTP response and the file will be downloaded from the browser?

**Comment by oderwat** [comment]
@rtrzebinski Yes, use the Chi router with some middleware and add the Go-App handler as the last one with a wildcard pattern.

**Comment by rtrzebinski** [comment]
Thank you again @oderwat 

Using your suggestions I've made it like this -> https://github.com/rtrzebinski/simple-memorizer-4/commit/81c3e5ddf802b6d275c1a3d3a8814bfa8b00712f

The key was to call `Download("")` on `A()` however I don't know what the argument is for, so I passed an empty string.

It works fine, however I'm not 100% happy with this solution, because if required a direct call to the REST API from the frontend, and I wanted everything to go through the service, but I'm not sure whether this is possible with a file download.

I could fetch data from the API and then build the CSV on the frontend, but is it possible to initialize a file download from the frontend without making a web call? That I can not figure out.

**Comment by oderwat** [comment]
Hmm. I am uncertain if I understand your wish. If you have data in the backend, write an HTTP handler that serves the file.

Then either use the download attribute (https://www.w3schools.com/tags/att_a_download.asp) and/or use a propper content disposition header. Something like his code: https://stackoverflow.com/questions/63781184/http-downloadable-file-serving

If you want to do it in the front-end, you need the `href="data:application/octet-stream;charset=utf-16le;base64,....` and the "download" attribute (which then also sets the name for the file to download).

I do not understand what you mean with `but is it possible to initialize a file download from the frontend without making a web call?`. This is what will happen if you use the `dara:application...` in the href attribute. But of course, you need to have the data in the front-end for that to work.

**Comment by rtrzebinski** [comment]
I think `href="data:application/octet-stream;charset=utf-16le;base64,....` is what I need, thank you very much for your time :)

**Comment by rtrzebinski** [comment]
@oderwat However, it would mean that the file needs to be ready on page load, right? Or there is a way to generate it on demand? (I mean this base64 part, could it be dynamic, on click?)

**Comment by oderwat** [comment]
Sure, you can change the href content whenever you want.
