### ISSUE TITLE
app.Route and component initiate

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#861]
I have

https://github.com/suntong/go-app-demos/blob/65ba93af774439fcc77917e54dce34a4997c420a/0A2C-hello/main.go#L54C2-L54C11

`app.Route("/hello", &hello{Name: "Sam"})`

and here is my `hello`:

https://github.com/suntong/go-app-demos/blob/65ba93af774439fcc77917e54dce34a4997c420a/0A2C-hello/main.go#L13-L20

```go
type hello struct {
	app.Compo
	Name string
}

func (h *hello) OnMount(ctx app.Context) {
	app.Log("component mounted with:", h.Name)
}
```

My anticipated behaviour is that when I visit `/hello`, I would see the log of `component mounted with: Sam`, however, the `h.Name` is still empty. 

What I'm missing please?

**Comment by oderwat** [comment]
Look at: https://github.com/maxence-charriere/go-app/issues/853#issuecomment-1660016029

**Comment by suntong** [comment]
Ok. Thanks
