### ISSUE TITLE
How to architect this

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#862]
> I ask because I changed my go-app control structure from lowercase to uppercase and it stop working, just as reported in OP. 

_Originally posted by @suntong in https://github.com/maxence-charriere/go-app/issues/799#issuecomment-1668190070_
           
Here is my change, replicated using the simplest example:

https://github.com/suntong/go-app-demos/commit/a4d2142098976119a9197a16079b1a45e4d3a40b

The reason I need to make such change, or the dilemma that I'm facing is, 

- I want to [use a two-level components approach, where the 1st level is universal](https://github.com/suntong/go-app-demos/commit/d48ec66f1ea8688715621b81d0e991aef7795bba)
- Yet at the 2nd level, I need fields to be in upper case, as I need to export & import the working component to/from JSON.

Is there any way that I can achieve my above two goals at the same time please?

**Comment by oderwat** [comment]
You cannot really marshal a working (aka mounted?) component to JSON anyway. Why not embed that data you want to un-/marshal as JSON inside a struct and put that into the component?

**Comment by suntong** [comment]
Perfect!!!
