### ISSUE TITLE
Custom error page

### ISSUE THREAD

**Issue by muffins261** [maxence-charriere/go-app#877]
I wanted to create a custom 404 page, but I didn't find this option in the documentation.  Is it possible to do this? If so, please give me an example.

**Comment by oderwat** [comment]
It depends on what you mean with an 404 page: 

As you define the routes in the backend and any route that is not picked up will throw a normal 404 error as with any other Go standard HTTP Server (see for example: https://stackoverflow.com/questions/9996767/showing-custom-404-error-page-with-standard-http-package).

One thing you easily could do, when using the "normal" way how Go-App, defines the routes: Set up all the real routes and as the last one you set up a wildcard route and make that load a "Page not found" component.

If you only have a wildcard route to the front-end and use some root component for all the logic, you need to deal with navigation there, then you need to evaluate your path and create something that you want to be the error 404 page.

**Comment by mlctrez** [comment]
@oderwat has excellent points on handling 404s and routing them correctly in go-app. 

On a side note, looking at how the code handles routing, I came across the following:

https://github.com/maxence-charriere/go-app/blob/ae6abf8bdf25d2128a1bbf49e254e4cc184f924a/pkg/app/app.go#L353-L356

A possible enhancement would instead call an `app.NotFoundComposer` function:

```go
compo, ok := routes.createComponent(path)
if !ok {
	compo = NotFoundComposer()
}
```

And changing:
https://github.com/maxence-charriere/go-app/blob/91858c694eb42ee3c23a070caefa64b8e1b5be75/pkg/app/notfound.go#L3-L7

To a function:

```go
var (
	// NotFoundComposer returns a default not found component.
	NotFoundComposer = func() Composer { return &notFound{} }
)
```

Then users could provide a default component when routing to an unknown route.

```go 
// while setting up app.Route() calls
app.NotFoundComposer = func() app.Composer { return &notFoundCustom{} }
```
