### ISSUE TITLE
How do I stop the logo from spinning?

### ISSUE THREAD

**Issue by omani** [maxence-charriere/go-app#880]
having a little tux guy spinning around is cute in dev environments, but for more serious production envs I need a non-moving static logo.

it seems there is no option to disable the spinning of the loading icon in the app handler.

is there an option? if not, can we implement this please?

**Comment by mlctrez** [comment]
If you need to change the css on the loading screen, you will have to serve your own `/app.css`.

```go
type customHandler struct {
	app.Handler
}

func (g *customHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path == "/app.css" {
		// serve up your css		
	} else {
		g.Handler.ServeHTTP(w, r)
	}
}
```
Removing line 53 would prevent the spin in the original css:

https://github.com/maxence-charriere/go-app/blob/4af747695016174dfbe4502d0754da7ea1b4807b/pkg/app/gen/app.css#L52-L54

**Comment by omani** [comment]
that worked. thank you.

**Comment by omani** [comment]
and what about the NAN100% when I remove the loading label? I guess it needs to know the header of the wasm? which I have in my header. thought it's because of gzipped content but disabling gzip doesnt fix it. on a second thought I think I dont want any label. so how can I remove the loading percentage when no label is specified?

**Comment by omani** [comment]
btw even the go-app.dev loading label goes up to 400% (above 100%) when loading. I think something is wrong with the percentage calculation or I am missing something.

**Comment by mlctrez** [comment]
> and what about the NaN% when I remove the loading label?

Try `handler.LoadingLabel = " "` to suppress the loading label.  If it is empty go-app will use the default:
https://github.com/maxence-charriere/go-app/blob/4af747695016174dfbe4502d0754da7ea1b4807b/pkg/app/http.go#L337-L339

> even the go-app.dev loading label goes up to 400%

[go-app.dev](https://go-app.dev) is hosted on github pages and the wasm is served using gzip compression. I don't believe there is a way on github pages to add the custom header for `WasmContentLengthHeader`. So yea, that's going to be broken.

**Comment by omani** [comment]
thanks for your help.
