### ISSUE TITLE
Htmx 

### ISSUE THREAD

**Issue by gedw99** [maxence-charriere/go-app#885]
Does this have a notion of htmx ? 

At the moment it renders every page in full ? 

It makes it possible to run the app server side for initial fast load and then transaction sone of the app to client side ..

app.RunWhenOnBrowser()

https://go-app.dev/seo

the htmx aspect is that you can send the html to the client from the server but also send fragments. 

This
Thanks

**Comment by maxence-charriere** [comment]
There is no htmx.
