### ISSUE TITLE
Already Mounted.

### ISSUE THREAD

**Issue by nathanhack** [maxence-charriere/go-app#895]
```
panic: {"line":"html.go:208","message":"appending child failed","tags":{"child":{},"index":3},"wrap":{"line":"html.go:263","message":"mounting element failed","tags":{"element":{}},"wrap":{"line":"component.go:278","message":"mounting component failed","tags":{"kind":3,"name":"*Node","reason":"already mounted"}}}}
```

I have a parent app.Compo with a list of sub-app.Compo's (*Node).

In the parent Render() I essentially have:
```
elems := []app.UI{}

//list of some stuff (app.ELem's)

//then add all the sub-app.Compo's

return app.Elem().Body( elems...)
   ```
But if the `list of some stuff` grows then I get the above panic.

**Comment by JulienLecoq** [comment]
If one of the child is already mounted somewhere in your website, you can't mount it another time. You have to create a new instance of this child to be able to mount it.
