### ISSUE TITLE
Latest onDragStart,onDragLeave example

### ISSUE THREAD

**Issue by shaktisource** [maxence-charriere/go-app#898]
I am a newbie , trying to implement Drag and drop functionality but not able to do so , can anyone please give an example on how to use listeners in go-app . Quick response would be appreciated as its delaying my work

**Comment by mlctrez** [comment]
Which parts of [HTML_Drag_and_Drop_API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API) are you trying to implement? 
There are drag operations and file upload operations. 

If you implement the functionality in plain JS/HTML and provide that it will make questions like this easier to answer.
