### ISSUE TITLE
support hash based routing

### ISSUE THREAD

**Issue by alvarolm** [maxence-charriere/go-app#899]
when there is no connection and trying to access any route directly we will see an error, hash based routing instead will always work as its based on the same root path.

**Comment by oderwat** [comment]
You can use hash based routing in the frontend if you want.

We have our own routing and use path and hash "routes" together in the frontend. In a PWA (installed) there is also no entry field for a URL, so "nobody" should use them directly anyway.

As I understand it, @maxence-charriere wants to make the PWA SEO friendly, and you can't do this with hash based routing.

**Comment by alvarolm** [comment]
I have implemented a redirect using one "hash entry point" solving my problem, it was easy using the [Navigator](https://go-app.dev/reference#Navigator) interface. thanks for the information @oderwat !
