### ISSUE TITLE
Can't make scrollbar follow new content added to overflow bottom.

### ISSUE THREAD

**Issue by RadiactoR** [maxence-charriere/go-app#901]
Since this is traditionally worked around using JavaScript, and there isn't any css property for it, there's currently no way (that I could find) to make an element's overflowing content make the scrollbar follow the newest content getting added at the bottom. For example, I have an element that is displaying live .log files, but as the div fills up, the scroll stays at the top of the list.

Is this an issue with go-app, or am I missing something?

**Comment by RadiactoR** [comment]
The second option is the only one I can work with atm, what would an "app.Window()" line manipulating elements look like?

**Comment by oderwat** [comment]
I am very busy right now. I think I can show you some code later.

**Comment by RadiactoR** [comment]
That would be great, thx.

**Comment by RadiactoR** [comment]
@oderwat I actually managed to solve it by using:
**app.Script().Text(`
			var scrollable = document.querySelector('.scrollable');
			function addScrollFocus() {
				scrollable.scrollTop = scrollable.scrollHeight;
			}
			setInterval(addScrollFocus, 1000);
		`),**
But still, thanks for the replies and help! :)

**Comment by RadiactoR** [comment]
I actually managed to solve it by simply using app.Script.Text:
`
app.Script().Text(`
			var scrollable = document.querySelector('.node-output-div');
			function addContent() {
				scrollable.scrollTop = scrollable.scrollHeight;
			}
			setInterval(addContent, 100);
		`),

`

**Comment by RadiactoR** [comment]
Thank you, but I actually solved it myself earlier today. I called "app.Script().Text()" and inside of Text() I wrote some simple JS code. Wish there would be a simpler way to interact with JS comands.

**Comment by oderwat** [comment]
@RadiactoR I think it is pretty simple to handle JS, it is more that the interfacing code is not that great, so we end up writing JavaScript and call it from Go at times. Emitting script from the renderer would not be my way to handle stuff. I think this is prone to edge cases, because of how the DOM is compared and updated with what you "Render()". But if it works like that, it is probably good enough.
