### ISSUE TITLE
Ssr to make the google gods happy

### ISSUE THREAD

**Issue by gedw99** [maxence-charriere/go-app#905]
Anyone got any thoughts about how to also do SSR.

My take is that we run the same code on backend and frontend . Every html endpoint on the server could render the html using go-app and send back the standard go-app.

the client can then render the html and then async background load the go-app Client.

**Comment by gedw99** [comment]
I heard decent reviews of https://github.com/mailjet/mailjet-apiv3-go but have not used it yet

**Comment by mlctrez** [comment]
@gedw99  

> Anyone got any thoughts about how to also do SSR.

go-app already handles server side rendering, leveraging the same UI component structure used on the client. See https://go-app.dev/seo

> mailjet-apiv3-go

mailjet looks interesting, but I'm not sure what it has to do with go-app

**Comment by gedw99** [comment]
thanks @mlctrez  

oopsy about the mail-jet. - was tired and posted in wrong tab :)

About SSR, this is great. I will try it.
