### ISSUE TITLE
FuncOf return value

### ISSUE THREAD

**Issue by alvarolm** [maxence-charriere/go-app#906]
I need to return as string from an FuncOf, so far I have tried with:

```
app.FuncOf(func(this app.Value, args []app.Value) any {
				return app.ValueOf("mystring")
})
```

but it crashes with:

> panic: ValueOf: invalid value
> wasm_exec.js:22 
> wasm_exec.js:22 goroutine 7 [running]:
> wasm_exec.js:22 syscall/js.ValueOf({0x788a0, 0x14f2990})
> wasm_exec.js:22 	/home/alvarolm/dev/globaldep/go/src/syscall/js/js.go:209 +0xf6
> wasm_exec.js:22 syscall/js.Value.Set({{}, 0x7ff80001000001a0, 0x14e0ad8}, {0x8a7a8, 0x6}, {0x788a0, 0x14f2990})
> wasm_exec.js:22 	/home/alvarolm/dev/globaldep/go/src/syscall/js/js.go:306 +0x8
> wasm_exec.js:22 syscall/js.handleEvent()
> wasm_exec.js:22 	/home/alvarolm/dev/globaldep/go/src/syscall/js/func.go:103 +0x27

any help is appreciated

**Comment by mlctrez** [comment]
If you are wanting to pass back a string to the calling javascript, you don't need to use `app.ValueOf`
```go
app.Window().Set("customFunction", app.FuncOf(func(this app.Value, args []app.Value) any {
    return "hello world"
}))
```
Calling from console:
![image](https://github.com/maxence-charriere/go-app/assets/885489/a446dcc5-b472-4877-a10f-a42a8986fe95)

Unless there is something more complex you are trying to do..

**Comment by alvarolm** [comment]
thanks! @mlctrez  I was following syscall/js for some reason.
