### ISSUE TITLE
[Question] What's the best way to handle form submission data?

### ISSUE THREAD

**Issue by Skarlso** [maxence-charriere/go-app#910]
So I'm re-doing my website (https://crd.cronohub.org) which has to fields to submit some data. A textarea or an input for a URL.

I'm not finding too many examples on the doc website on how to do this stuff, so I'm struggling to figure out things.

I have to main components, the index and the submit which handles the display.

Now, on the index's form I'm doing this:

```go
// form is the form in which the user will submit their input.
type form struct {
	app.Compo
}

func (f *form) Render() app.UI {
	return app.Div().Class("mt-md-20").Body(
		app.Form().Action("/submit").Method("POST").Body(
			app.Div().Class("mb-3").Body(
				&textarea{},
				&input{},
			),
			app.Button().Class("btn btn-primary").Type("submit").Style("margin-top", "15px").Text("Submit"),
		).OnSubmit(f.OnSubmit),
	)
}

func (f *form) OnSubmit(ctx app.Context, e app.Event) {
	// TODO: set state here and then get that value in the other component.
}
```

route is like this:

```go
	app.Route("/", &index{})
	app.Route("/submit", &crdView{})
```

So I was thinking that upon form submit, I will set a `State` with the value gathered somehow ( probably through ByDocumentId or something unless there is a better way? ) and then in the submit code the `crdView` upon `Mount` I will see if the State exists and gather the value through that.

Is that the right way of doing this or is there another way?

**Comment by Skarlso** [comment]
It looks like the submit event isn't allowing for the `OnSubmit` to fire.

```go
func (f *form) OnSubmit(ctx app.Context, e app.Event) {
	app.Log("I'm called")
	ctx.SetState("crdData", "Sending this", app.Persist)
}
```

`I'm called` isn't working.

**Comment by oderwat** [comment]
Reading your message again, if you want to output "Raw()" HTML you can do that. What strikes me is that a lot of people want to use go-app in a way that it is not meant to be used for. Modifying the DOM should be done with `Render()` and declarative. Using `Raw()` or other ways to update the DOM will likely cause problems in the long run.

**Comment by Skarlso** [comment]
No I don't want that. :D I would like to understand how go-app is meant to be used. I find that difficult by just reading the docs to be honest. :D :D 

So.. I'm rendering something using a component, and then I update the component's structure and call update.. ? 🤔  Or what's the flow here? :D 

I create an onClick for my button, read in the user input, do my parsing, which is done completely using the component! I build up an actual component and call Render which works perfectly BTW. But what I'm struggling with is how I would go from one view to the other basically. So first, get the user input, second display the next component which is the rendered output.

**Comment by Skarlso** [comment]
Thanks, I will check out the code for that todo! Hopefully that will lift my fog of understanding a little. :D

**Comment by oderwat** [comment]
To switch between different views, you could set up a root component that has some "viewID" and make the `Render()` of this component to render the component that is representing that view (which will be a component too). There is a caveat though. If your different components have the same type (like a "Page" or a "TabContent" component) the way Go-App is updating the DOM may surprise you, as it does not replace a component but updates the first component that was rendered with the component you switched too. Well, to make a long story short: You may need to use something like the "mountpoint" I created which is also in github.com/metatexx/go-app-pkgs/. This then goes in the place where you have the swap able part (based on current viewID) of the root node and makes sure that Go-App sees the switched component as being new and recreate the DOM that represents it.

**Comment by Skarlso** [comment]
Hm. What would be the go-app way here that can take user input and then output something based on such input?

I've seen usage of `If` for example. I could imagine something like and If based on a `State` for example? I could set the state to the content that user is providing and based on that use a different component?

**Comment by oderwat** [comment]
I advise against using `If()` at all, just use a `func(condition bool) app.UI{}` instead (`If()` will evaluate all branches always in the current Go-App release).

If you have some input and output, you can create one component which has both as internal state (c.input, c.output), let the Render() decide what to show and have for example a `Button()` with an `OnClick()` `app.EventHandler` which grabs the input in some way. We usually do something like `OnInput(c.ValueTo(c.input))` for the text area. Then you calculate the new state, put it into the internal variable. This handler will automatically update by calling `Render()` and update the DOM with the new outcome. While the `ToValue()`

**Comment by Skarlso** [comment]
Doesn't OnInput fire on each and every character...?

**Comment by Skarlso** [comment]
>This handler will automatically update by calling Render()

The handler can call `Render()`? 😲

**Comment by oderwat** [comment]
From that code it is unclear how `form` will update `i.content()` but that may be where you use an action handler or (what I would do) add a callback function to `form` as an external field and call that (if non null) when the content is set.

**Comment by Skarlso** [comment]
Thanks a lot. I'm heading home now and will try to internalize all this. 🤣

**Comment by oderwat** [comment]
Maybe that has to do with `Render()` is called twice when setting up the component? Once before `OnMount()` and once after `OnMount()`. Only `OnInit()` will be called before the first render and is guaranteed to only run once for a component (even if dismounted and remounted). So what we usually do is letting Render check for `c.IsMounted()` and `return app.Div()` in that case.

**Comment by Skarlso** [comment]
I really like this approach. It makes the site easy to follow and render, I think.

Now I just have to get that data from the textarea or the input and I'm golden. :D 🥇 

Yah some more real world code and explanation of the structure would be super duper helpful. I really really enjoy working with go-app. :)

**Comment by Skarlso** [comment]
@oderwat

> So what we usually do is letting Render check for c.IsMounted() and return app.Div() in that case.

Errr... how do you do that? Do you implement it with something like this?

```go

func (i *index) OnMount(ctx app.Context) {
	i.isMounted = true
}

func (i *index) Render() app.UI {
	if i.isMounted {
		return app.Div()
	}
	...
}
```


Or is there something specific for it?

**Comment by oderwat** [comment]
There is `i.Mounted()` you do not need to implement it yourself I wrote most of that from memory, so excuse me giving the wrong method name.

**Comment by oderwat** [comment]
Getting the data can be done in different way:

1. You use that `c.ValueTo(&c.anything)` which is a standard event handler that takes the "value" of the JavaScript element and evaluates it as string and place it in the destination. When you look up the code for it, you find what I usually do where others are using the ID of the JS element
2. `ctx.JSSrc()` is the DOM node that was created for the component. So `ctx.JSSrc().Get("src")` would give you the source of an image in an `OnClick()` handler. Basically it is as if you set an ID on that element and then use `window.GetElementByID('theTID')` to get that DOM node.
3. Using IDs and `app.Window().GetElementByID("someID").Get("value").String()` also gets you the element with a little roundtrip to JS (and this is why I try to avoid it).
4. You can also use all the other JS selectors, like so: 
   ```go
   divs := container.Call("getElementsByClassName", "item")
   for i := 0; i < divs.Length(); i++ {
     div := divs.Index(i)
    dbg.Logc(div)
   }
   ```
    This is using `dbg.Logc()` from our packages, which will output the JS object into the dev console so you can inspect it.
5. You can just store a component or a reference to it inside your component and the just use `c.items[i].JSValue()` which also references the DOM node that was created for the component.

**Comment by Skarlso** [comment]
Thanks again!

The event based approaches aren't working because the event source isn't the input field or the textarea. For now I went with the ID approach:

```go
func (i *index) OnClick(ctx app.Context, e app.Event) {
	ta := app.Window().GetElementByID("crd_data").Get("value")
	if v := ta.String(); v != "" {
		if len(v) > maximumBytes {
			i.err = errors.New("content exceeds maximum length of 200KB")

			return
		}

		i.content = []byte(v)

		return
	}

	inp := app.Window().GetElementByID("url_to_crd").Get("value")
	if inp.String() == "" {
		return
	}

	f := fetcher.NewFetcher(http.DefaultClient)
	content, err := f.Fetch(inp.String())
	if err != nil {
		i.err = err

		return
	}
	if len(content) > maximumBytes {
		i.err = errors.New("content exceeds maximum length of 200KB")

		return
	}

	i.content = content
}
```

But number 5 sounds intriguing, actually! I didn't think about that. :D Thanks, I shall try that. :)

**Comment by Skarlso** [comment]
Regardless the question is answered I think. :) Thank you very much for ALL the help in this. :)
