### ISSUE TITLE
Makes the generated HTML available without having to mount the elements.

### ISSUE THREAD

**Issue by JulienLecoq** [maxence-charriere/go-app#939]
I built some components (tables) using this library and wanted to export them as a string to send them via emails but those components must be mounted in order to export them otherwise it panics.

To reproduce, you can simply do this:

```go
element := app.Div().Text("Hello")
str := element.JSValue().Get("outerHTML").String()
```

Doing so requires the element to be mounted in the Dom.
I would like to not have this restriction so that I can export my components with a style slightly modified from the one generated on the website.

**Comment by maxence-charriere** [comment]
You can use https://github.com/maxence-charriere/go-app/blob/master/pkg/app/node.go#L156

**Comment by JulienLecoq** [comment]
It works, perfect. Thanks!
