### ISSUE TITLE
Render calls before OnMount

### ISSUE THREAD

**Issue by gmax79** [maxence-charriere/go-app#945]
```
func Render() app.UI  {
  app.Log("Render")
}

func OnMount(ctx app.Context) {
  app.Log("OnMount")
}
```

Log output:
Render
OnMount
Render

I think OnMount should always be called first

**Comment by oderwat** [comment]
You need something that you can mount, so you need to call render, before you can mount it. 

You look for ´OnInit()` (or you need to check the state of you component in Render() and act accordingly).
