### ISSUE TITLE
debug go-app in nowasm

### ISSUE THREAD

**Issue by gepengscu** [maxence-charriere/go-app#946]
The difficulty in debugging wasm has limited the development of go-app. Here are a few suggestions for debugging wasm in nowasm mode. I'm not sure if they are feasible or not.
1. Public the private methods in app.Value interface, or permit registering callback functions which are called by the private functions.
2. Define a DOM object for running unit test in nowasm mode.

**Comment by oderwat** [comment]
I guess you mean it limits your development using Go-App?

Could you give an example what is problematic for you to get right? Are you trying to combine "normal" JavaScript libraries with Go-App?

We generally do not have problems with debugging and bug fixing for our steadily growing applications that are from using WASM / Go-App. Sure, a step debugger that links back to the Go source would be nice, but using our print logging with stack traces works very well for us and writing smaller example applications before using new functionalities in a larger project makes things also more manageable.

P.S.: If you need some private Methods, just check out the Go-App code and use a "go.work" file in the project. Then you can add all the debugging you need. This possibility is one of the reasons why we use Go in the company.

**Comment by oderwat** [comment]
What is 'go-app nowasm mode'? Do you mean using the Go-App declarative HTML generation? Isn't this a totally bloated way to create a standard HTML web server?

**Comment by gepengscu** [comment]
Go.work is a good idea.Thank you @oderwat very much.

**Comment by pancsta** [comment]
> a step debugger that links back to the Go source would be nice

Ive made one, well kinda. It's a state machine time travel debugger which I use to orchestrate go-app instances. This infra also allows to easily control the browser from the server. The [code is here](https://github.com/pancsta/secai/blob/main/web/browser/browser.go), and theres also [a live demo of the debugging session](https://ai-gents.work/dbg-cook).

From other news, Swift now has a [fully functional vscode WASM debugger](https://fosdem.org/2026/schedule/event/87ZLQV-wasm-debugging-lldb/), so it is technically possible.
