### ISSUE TITLE
tiny hamburger on mobile

### ISSUE THREAD

**Issue by gedw99** [maxence-charriere/go-app#948]
in safari its tiny in the top left.

<img width="1515" alt="Screenshot 2024-05-01 at 22 52 25" src="https://github.com/maxence-charriere/go-app/assets/53147028/cf610ca0-a5c0-43fe-96c9-9d8acc2731b0">

**Comment by oderwat** [comment]
How is that related to Go-App?

**Comment by gedw99** [comment]
The docs app is built with go-app

**Comment by oderwat** [comment]
Lol, I was not noticing that that is from the documentation. A CSS quirk I guess.

**Comment by gedw99** [comment]
can confirm its fixed too.
