### ISSUE TITLE
Issue Cleanup and Focus for Go-app v10

### ISSUE THREAD

**Issue by maxence-charriere** [maxence-charriere/go-app#952]
Hello everyone,

Thanks for using Go-app. I just released [v10](https://github.com/maxence-charriere/go-app/releases/tag/v10.0.0) and realized there are a lot of issues. I feel overloaded by this and need to clean things up to help me focus on what needs to be done!.

Here are the issues I'm closing:
- Already resolved
- Documentation related: I'm planning to move the documentation code into its own repository
- Issues that I think are not related to Go-app: Go, WASM, and browser issues
- Issues that I don't understand

If I close something that you think is very important and still ongoing, feel free to reopen it.

**Comment by thejezzi** [comment]
Thanks for the hard work mate! 💯
