### ISSUE TITLE
Route regex like containing `?param=` is not routing

### ISSUE THREAD

**Issue by Skarlso** [maxence-charriere/go-app#955]
I have a routing regex like this `app.RouteWithRegexp("^/share?url=[a-zA-Z]+$", &crdView{})` and it's not routing. It says 404.

If I change it to `app.RouteWithRegexp("^/share/[a-zA-Z]+$", &crdView{})` it routes fine.

Any ideas what's happening?

**Comment by oderwat** [comment]
First, you have an unescaped `?` in your regular expression, which will match one an `e` or nothing, but not the question mark itself like this:

<img width="274" alt="image" src="https://github.com/maxence-charriere/go-app/assets/719156/e43f0a81-9873-4f7f-9ebc-eccd77fda17e">

Second, I believe the match is against the path and the query parameters are not part of it.

**Comment by Skarlso** [comment]
Yeah I figured question mark and escaped it. And indeed, the equal sign is the one breaking the whole thing.

**Comment by Skarlso** [comment]
BTW, if I do escape it, it doesn't work. :D `app.RouteWithRegexp("^/share\\?.*$", &crdView{})` Something like this, for example doesn't match `share?asdf`.

**Comment by oderwat** [comment]
It matches the path, not the full URL. You can't match onto the GET parameters this way.

I also think you should update to V10 of Go-App. It looks like you use an older one.

**Comment by Skarlso** [comment]
>It matches the path, not the full URL.

Oh I see, so it ignores the Query side completely. Gotcha. Is there a better way to get to them? I saw that you are using chai router somewhere after... or something like that. I'm not sure how that works. Anyways, I got around it for now by doing `share.*` and then parsing in `OnNav`.

I'm am using v10. I literally just updated. What made you think I'm not? Am I doing something differently that I shouldn't be doing with v10?

**Comment by Skarlso** [comment]
Ah you're right. I didn't actually update to 10 because I was still importing v9.

**Comment by Skarlso** [comment]
The website is still using the old format. :(

```go
func main() {
    // Go-app component routing (client-side):
	app.Route("/", &hello{})
	app.Route("/hello", &hello{})
```

**Comment by oderwat** [comment]
You will get the "GET" variables from inside your component using the JS bridge. You could do this in different ways.

Example using 'net/url' in `OnNav()` (Navigator interface). This is the place where you will get navigation if the app was loaded and is navigated. This will be called after the component was mounted (`OnMount()`) but is already available in it and in `OnInit()` when the page was loaded from the server.

```go
var _ app.Navigator = (*Overview)(nil)

func (c *Overview) OnNav(_ app.Context) {
	href := app.Window().Get("location").Get("href").String()
	app.Logf("url: %q", href)
	pageURL, err := url.ParseRequestURI(href)
	if err == nil {
		app.Logf("query: %#v", pageURL.Query())
	}
}
```

P.S.: I often wonder newcomers do know that this call is processed inside the browser, which is the whole point of a PWA. You mentioned me using other routers. We have them in the backend. If you want to process those routes in the backend you need to catch them before `app.Route()`.

**Comment by oderwat** [comment]
@maxence-charriere Updating the example to the new routing would be a good idea I guess :)

**Comment by Skarlso** [comment]
Actually, I did this:

```go
u := ctx.Page().URL().Query().Get("url")
```

In `OnNav`. This works fine. However, now my problem is that locally everything worked perfectly, and on the deployed site, the routing isn't working anymore. I verified it's the latest version by setting `Version` and checking on the deployed site for that version. It is the latest deployed wasm app, yet routing isn't... routing. :) It's a 404 once it's deployed.

It's deployed as a static wasm app on GitHub. Is that a problem for routing?

**Comment by oderwat** [comment]
Using `ctx` makes it easier. I was creating that example in `OnInit()` originally and when changing it to `OnNav()` I forgot that there is the page interface :)

I did not use the static sites stuff myself, so I can't really help with that. I think it should basically work the same. Maybe you can see something in the developer tools (navigation) or use something like "ProxyMan" which can help to figure out what is really happening.

**Comment by Skarlso** [comment]
It's super weird. It's like GitHub is there first before the wasm app can even load.

I'm getting a 404 github page and not from the app. That is super weird.

https://crdtoyaml.com/share?url=asdf -> this URL is not working in GitHub

http://localhost:8000/share?url=asdf -> this localhost page does work though when I'm playing with it locally. So definitely something up there. I'll create a separate issue. :)

**Comment by Skarlso** [comment]
I think I'm trying to use it incorrectly? The routing section of the doc says that once the go app is loaded, that's when routing happens. But I thought that would work with the Javascript routing or something. Not sure how that works in the background. Maybe it's a bug or maybe I'm trying to do something that's simply not supported statically?

**Comment by Skarlso** [comment]
Yeah I think what I'm looking for might be HTTP routing, and not APP routing. 🤔

**Comment by Skarlso** [comment]
Oh interesting... When choosing `Route("/share")` it generated a `share.html` but the regex routing didn't do that.

**Comment by Skarlso** [comment]
Ugh, I give up. I don't know why it's not routing to the configured address. :(

**Comment by maxence-charriere** [comment]
What do you use to generate the static files for GitHub pages? Do you use it with github page url or you have it resolved to tou own domain name?

**Comment by Skarlso** [comment]
Own domain. Under https://crdtoyaml.com.

**Comment by Skarlso** [comment]
OMG!!! I Got it to work :D

**Comment by maxence-charriere** [comment]
What about the way you generate the static files?

**Comment by Skarlso** [comment]
This is my setup: https://github.com/Skarlso/crd-to-sample-yaml/blob/main/wasm/main.go#L114

Okay, so regex routing didn't work! BUT! I set up static routing with simply:

```go
	app.Route("/share", func() app.Composer {
		return &crdView{}
	})
```

And then the rest is `OnNav`. It still accepts a url like this:

https://crdtoyaml.com/share?url=https://raw.githubusercontent.com/Skarlso/crd-to-sample-yaml/main/sample-crd/infrastructure.cluster.x-k8s.io_awsclusters.yaml

Which wouldn't work with the regex thing, but works with plain routing. :D

**Comment by Skarlso** [comment]
Yep, I was about to close this too. Thanks for all the help folks. :)
