### ISSUE TITLE
goappGetenv is not a function, got undefined

### ISSUE THREAD

**Issue by elfprince13** [maxence-charriere/go-app#959]
main.main() panics in `app.RunWhenOnBrowser` when running even a trivial example.

```console
panic: syscall/js: Value.Call: property goappGetenv is not a function, got undefined [recovered]
wasm_exec.js:22 	panic: syscall/js: Value.Call: property goappGetenv is not a function, got undefined
```

**Comment by elfprince13** [comment]
If I upgrade from v9 to v10 I instead get:

```console
panic: JavaScript error: Failed to execute 'replaceChild' on 'Node': parameter 2 is not of type 'Node'. [recovered]
wasm_exec.js:22 	panic: JavaScript error: Failed to execute 'replaceChild' on 'Node': parameter 2 is not of type 'Node'.
```

**Comment by oderwat** [comment]
Well. I guess you need to show us the code for that trivial example. 

I currently have no V10 based public project (but we use V10 since months for our products). Maybe try something we published with V9 in the meantime:

- https://github.com/oderwat/go-guess-the-number-app
- https://github.com/metatexx/go-app-todo
- https://github.com/oderwat/go-nats-app

**Comment by elfprince13** [comment]
> Well. I guess you need to show us the code for that trivial example.
> 
> I currently have no V10 based public project (but we use V10 since months for our products). Maybe try something we published with V9 in the meantime:
> 
>     * https://github.com/oderwat/go-guess-the-number-app
> 
>     * https://github.com/metatexx/go-app-todo
> 
>     * https://github.com/oderwat/go-nats-app
> 
> 
> I think the only needed change for V10 is using `app.NewZeroComponentFactory(&component{}))` with the `app.RouteX()` but there may be other little things to adjust.

I literally just copy-pasted the examples from the site and renamed the module for a project I'm testing.

I checked out and built your `go-guess-the-number-app` with no errors, but running `app` and navigating to localhost:8000 shows a page with a broken image that says:

```console
TypeError: import object field 'gojs' is not an Object
```

**Comment by oderwat** [comment]
Let me check https://github.com/oderwat/go-guess-the-number-app .. this is very old and I forgot that I had this there.

**Comment by elfprince13** [comment]
In case it makes a difference, I'm compiling with `go version go1.22.3 darwin/arm64`, but not getting any compilation errors, only runtime errors.

**Comment by oderwat** [comment]
That is the reason for this one error. The gojs changend between the time my code was written and now. This can't easily be captured by the package.

I quickly rewrote my `https://github.com/oderwat/go-guess-the-number-app` for V10. Use `make run` and open http://127.0.0.1:8000

**Comment by elfprince13** [comment]
For posterity - it seems the cluster of related issues here is that there are a bunch of files needed to serve the site statically which can only be generated with `app.GenerateStaticWebsite`.
