### ISSUE TITLE
https://go-app.dev updates are lacking latest releases

### ISSUE THREAD

**Issue by JensRantil** [maxence-charriere/go-app#970]
https://go-app.dev lists the following updates:

<img width="342" alt="image" src="https://github.com/maxence-charriere/go-app/assets/730342/a09aaac7-06d4-4bf8-819d-ed1d824f0ea2">

where version 9.4.0 is announced.

...but I am seeing the latest release is 10.0.5 [here](https://github.com/maxence-charriere/go-app).

**Comment by mlctrez** [comment]
@JensRantil  - see https://github.com/maxence-charriere/go-app/issues/952 
I believe @maxence-charriere is moving the documentation to a new repository so the go-app.dev site may be out of date for a short amount of time.

**Comment by JensRantil** [comment]
@mlctrez 👍 Feel free to close this if so.

**Comment by mlctrez** [comment]
I don't have permissions, so @maxence-charriere will have to weigh in / close this.
