### ISSUE TITLE
type app.BrowserWindow has no field or method AddEventListener

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#973]
Following up with https://github.com/maxence-charriere/go-app/issues/832,

> app.Window().AddEventListener("keyup", func(ctx app.Context, e app.Event) {
>   // sent some HTTP request on key press
> }

which [had been working before in v9](https://github.com/mlctrez/imgtofactbp/blob/d2b159a921d4611bff5d6b5fbdf9e5cf13f82e65/components/clipboard/clipboard.go#L48), but now, with v10 (v10.0.5), I'm getting:

`app.Window().AddEventListener undefined (type app.BrowserWindow has no field or method AddEventListener)`

How to make it work again please?

**Comment by oderwat** [comment]
Just use 

```go
    app.Window().Call("addEventListener", "online", app.FuncOf(func(this app.Value, args []app.Value) any {
        dbg.Log("network status: online")
        return nil
    }))
```

**Comment by suntong** [comment]
Thanks Hans,

I tried to put in the missing pieces myself with the help of the code from:
https://github.com/maxence-charriere/go-app/issues/717#issuecomment-1095108907

and this is the change to [clipboard.go](https://github.com/mlctrez/imgtofactbp/blob/d2b159a921d4611bff5d6b5fbdf9e5cf13f82e65/components/clipboard/clipboard.go#L48) I came up with -- https://www.diffchecker.com/iWkWYIZm/

![image](https://github.com/user-attachments/assets/7a8f3107-cb73-40db-b9bb-f3e4d869f509)

(_Changed text_ at bottom half)

![image](https://github.com/user-attachments/assets/6eccfc15-e6cd-4982-96c2-bdba4dc138df)

It passes compilation but errored out on execution:

![image](https://github.com/user-attachments/assets/316c17b0-6e4d-46a1-9abe-c04a7c5baa68)

Am I close? How to make it fully working please? thx.

**Comment by oderwat** [comment]
Well, I think you need to extract the event from the data you get. I have some WIP snippet here that I used somewhere while prototyping. You would need to remove the event listener and call the release function that gets returned when you dismount the component that uses it. I guess it could return a function that also removes the event listener itself.

```go
func OnPaste(fn func(string)) func() {
	hFn := func(this app.Value, args []app.Value) any {
		event := args[0]
		clipboardData := event.Get("clipboardData")
		text := clipboardData.Call("getData", "text").String()
		fn(text)
		return nil
	}
	fo := app.FuncOf(hFn)
	app.Window().Call("addEventListener", "paste", fo)
	return fo.Release
}
```

**Comment by suntong** [comment]
Hmm.. I try to see where to put `func OnPaste(fn func(string))`  into [clipboard.go](https://github.com/mlctrez/imgtofactbp/blob/d2b159a921d4611bff5d6b5fbdf9e5cf13f82e65/components/clipboard/clipboard.go#L48), but realized that it's beyond me. 

So I opened https://github.com/mlctrez/imgtofactbp/issues/1, and hope @mlctrez can fix either there or here...

Thanks everyone!

**Comment by oderwat** [comment]
Well that is just a function to catch any paste and call a function for it. The part that you are missing in your adaption seems to me, that you so not get the event but add a fake empty one `app.Event()` instead of using `event := args[0]`.

**Comment by suntong** [comment]
THX! OK, I've changed the code to:

```go
	app.Window().Call("addEventListener", "paste", app.FuncOf(func(this app.Value, args []app.Value) any {
		event := args[0]
		c.pasteEventListener(ctx, event)
		return nil
	}))
```

But I'm still getting 

```
Uncaught Error: Go program has already exited
    at globalThis.Go._resume
```

I guess that I need to _"remove the event listener and call the release function that gets returned when you dismount the component that uses it"_, but it involves a deeper methodology change, as the 

```go
func (c *Clipboard) OnMount(ctx app.Context) {
	app.Window().AddEventListener("paste", c.pasteEventListener)
}
```

Has been working in V9, and the `AddEventListener` was only done _once_ on the clipboard component being mounted, while your code above, the `func OnPaste(fn func(string))`, remove the event listener _on every paste_. 

For such deeper methodology change, it's way beyond me, I'll wait to see what Matt would say...

**Comment by suntong** [comment]
Hi @maxence-charriere, I'm thinking, 

```go
func (c *Clipboard) OnMount(ctx app.Context) {
	app.Window().AddEventListener("paste", c.pasteEventListener)
}
```

If there is no easy way to make the above V9-working code work again in V10 easily, we should consider adding the `AddEventListener` feature back into V10.

**Comment by oderwat** [comment]
@suntong this was suggested and afair @maxence-charriere showed that this is not a good way to support event handler like that.

And I also do not see any problem. The code I gave to you (`OnPaste()`) works very well. It only handles the "string" case, but one could add the file case easily I think.

Why do you insist on updating (and using) another persons package without understanding it? I don't want to be rude (but I probably sound like that). It is just, that many years of coding and working with new team members made me realize that the "copy & paste" style of coding brings you back to those issues again and again. This results in every increasing dependence on other people. If you were in my team I would take your concern and go into it while using pair programming and nudging into the right directions. Maybe even not fully understanding the difficulties myself.

Updating the `clippboard.go` my end up quite trivial in the end. But if the maintainer does not react (he may be on a vacation, or is not interested in go-app anymore), you are left alone with that code on every occasion a problem appears.

I am pretty sure there is no magic involved with the V9 add event listener. It just defers the result into the go app context which is actually not even needed for some implementations and can easily be added by using `app.Dispatch()` and maybe something else.

So my advice would be that you check out go app v9 and analyze that function and implement something yourself.

**Comment by suntong** [comment]
Hmm..., I'm sorry if I have in any way offended you, but aren't we all using other packages/libs without understanding how exactly they work under the hood, until there's a problem? Well, at least me has been doing that for every packages/libs that I use.

Anyway, I'm not insist on updating it, just I saw, with my limited understanding, that it _was_ a short path.

**Comment by oderwat** [comment]
@suntong I am not offended (maybe stressed by other influences). Using other packages for us is usually not about the understanding, but the limited time to write everything ourselves. 

Having the possibility to continue (most) packages because they are written in Go is a big part of how we chose what we use in development. Which also leads to upstream PRs for many projects that we/I use. 

Of course there are situations where we lack the knowledge for implementing something from scratch (most likely security related stuff). 

I wanted to point out here, is that there is a lot of information available to solve the problem you face. I am sincerely sad, that I come through as annoyed instead of motivating you to dig a bit deeper to find a solution. That is possibly a skill I lack even with 40+ years developing software, or because of that. 🥹

**Comment by suntong** [comment]
No, sir, I'm sorry that I had been trying to find a quick fix, while in fact that I should sit down and look deeply into the matter and try to solve it myself. 

I will try...
