### ISSUE TITLE
TypeError: WebAssembly.instantiate(): Import #0 module="gojs": module is not an object or function

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#974]
Exactly as reported in #835, I'm getting

`TypeError: WebAssembly.instantiate(): Import #0 module="gojs": module is not an object or function`

even after I cleaned everything from the server side and the client side. Happened to two of my machines and all of my go-app projects. 

This started happening after I've upgraded my go-app V10, then back down compiling V9 code, i.e., the exact same code that was working before failed to be working after my new compilation.

I know this is slightly OT, but I've been fighting this problem for over two days, and have now exhausted all my ideas. I'm putting my code that was working before at

https://github.com/suntong/go-app-hello-0A2

but now _it fails to run on both of my machines_, which I believe should not be the case for anyone else. Any help appreciated. 

```
$ go run mage.go run
> Building WASM...
go: downloading github.com/google/uuid v1.3.0
github.com/google/uuid
github.com/maxence-charriere/go-app/v9/pkg/app
project
> Building App...
github.com/google/uuid
github.com/maxence-charriere/go-app/v9/pkg/app
project
2024/07/19 11:37:07 Listening on http://:8000
^C
cancelling mage targets, waiting up to 5 seconds for cleanup...
Error: failed to run "bin/demo : signal: interrupt"
exit status 1
```

![image](https://github.com/user-attachments/assets/3b95ee41-8f92-406b-a2a7-5a2dd2f55056)

**Comment by oderwat** [comment]
You are using a V9 which was before the change to Go 1.21. Which means you would need to use the v1.19 compiler. But you can simply update it like this:

![image](https://github.com/user-attachments/assets/b0b9861c-9bfb-4637-b779-32e891406135)

**Comment by suntong** [comment]
Ah~~~, indeed! THANKS!
