### ISSUE TITLE
OnPaste Mechanism

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#975]
Following up with https://github.com/maxence-charriere/go-app/issues/973, trying to fix

```go
func (c *Clipboard) OnMount(ctx app.Context) {
	app.Window().AddEventListener("paste", c.pasteEventListener)
}
```

and this is the change to [clipboard.go](https://github.com/mlctrez/imgtofactbp/blob/d2b159a921d4611bff5d6b5fbdf9e5cf13f82e65/components/clipboard/clipboard.go#L48) I came up with -- https://www.diffchecker.com/c8tBOv10/

![image](https://github.com/user-attachments/assets/44e8e204-c86e-4d8d-8279-cae1714604ac)

(_Changed text_ at bottom half, besides using v10 lib)

![image](https://github.com/user-attachments/assets/6eccfc15-e6cd-4982-96c2-bdba4dc138df)

The logic should be exactly the same I believe, but the `OnPaste` is not triggered during execution.

Is it because the `OnPaste` is not triggered at the component but app level, and I somehow have to cascade the triggering down myself? I.e., there must be a reason why the [clipboard.go](https://github.com/mlctrez/imgtofactbp/blob/d2b159a921d4611bff5d6b5fbdf9e5cf13f82e65/components/clipboard/clipboard.go#L48) didn't use `OnPaste` but did the `AddEventListener` itself.

How to make it fully working please? thx.

**Comment by oderwat** [comment]
`app.Window().AddEventListener("paste", c.pasteEventListener)` adds the even listener globally to the window and your code adds the `OnPaste()` method onto the component, which does nothing. It should be used on something like `app.Textarea().OnPaste(...)`

Did you try to use something like this? I did not check syntax/types. But something similar to this should work.

```go
func (c *Clipboard) OnMount(ctx app.Context) {
    app.Window().Call("addEventListener", "paste", app.FuncOf(func(this app.Value, args []app.Value) any {
        ctx.Dispatch(func(ctx app.Context) {
             c.pasteEventListener(ctx, args[0])
        }
        return nil
    }))
}
```

**Comment by suntong** [comment]
Thanks for the reply. I tried the following:

```go
func (c *Clipboard) OnMount(ctx app.Context) {
	// app.Window().Call("addEventListener", "online", app.FuncOf(func(this app.Value, args []app.Value) any {
	// 	app.Log("network status: online")
	// 	return nil
	// }))

	app.Window().Call("addEventListener", "paste", app.FuncOf(func(this app.Value, args []app.Value) any {
		ctx.Dispatch(func(ctx app.Context) {
			c.pasteEventListener(ctx, args[0].(app.Event))
		})
		return nil
	}))
}
```

It passes compilation but errored out on execution:

![image](https://github.com/user-attachments/assets/4dc83137-58e1-4894-9b5d-e44105b25158)

**Comment by oderwat** [comment]
Well, I do not believe that `args[0]` is of type app.Event. More like `app.Event{Value: args[0]}`. Did you look at the v9 implementation?

**Comment by suntong** [comment]
No I didn't, ... know where to start...

Yep, your `app.Event{Value: args[0]}` make it work. 

THANKS A LOT!
