### ISSUE TITLE
How to make app installable

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#976]
...So effectively `IsAppInstallable` should only be checked by a component that implements `app.AppInstaller` :

```go
var _ app.AppInstaller = (*InstallButton)(nil)
```

...

_Originally posted by @mlctrez in https://github.com/maxence-charriere/go-app/issues/868#issuecomment-1678030366_
            

Are aboves still hold? Seems not (i.e., seems that the whole https://go-app.dev/install#detect-install-support section no longer applies any more). Anyway, 

How to make an app installable? Thx!

More details, as per [desktop doc](https://go-app.dev/install#desktop):

> - Open the app in [Chrome](https://www.google.com/chrome) or [Edge](https://www.microsoft.com/edge)
> - Click on the Install button on the right inside the search bar
> - In the install popup, click on the Install button

But I didn't see such Install button on the right inside my search bar, for my project https://github.com/suntong/go-app-hello, and I've just tried the latest https://github.com/oderwat/go-nats-app too, which is V10 based, but didn't see such Install button either.

**Comment by oderwat** [comment]
The `IsAppInstallable` is just to tell the user that it in fact is installable for example by showing a message in the GUI. The app itself is installable automatically if the requirements are met: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable

Basically: You need to run it on `localhost` or with `HTTS`. It won't work with some basic HTTP server or forwarding.

There may be some other requirements for iOS though, because we encountered that it is sometimes not installable when it is being some kind of "warp" setup, where the frontend runs HTTPS and connects to a developer server.

Besides being installable, there is also the question of running offline. For this you need to add all static data to the `CacheableResources` of the handler that is not already included like the icons, the WASM module and the web manifest. So basically all the JS-scripts, images and other data that it loads.

**Comment by suntong** [comment]
Oh, 

My go-nats-app was running neither on localhost nor with HTTPS, but from my local net. 

Thanks for the clarification.

**Comment by suntong** [comment]
Hmm... there's still something that's off, like my https://github.com/suntong/go-app-hello app, which is hosted with HTTPS at https://suntong.github.io/go-app-hello/, but I don't see such Install button there. 

Let me try to figure it out myself first, like updating to V10 as the first step...

**Comment by oderwat** [comment]
Hint: Look and think about the error shown in the console.

**Comment by suntong** [comment]
Ah, yes, _checking the errors in the console_ is the key, and I'm seeing the Install button this time.

However, there are two more installable app related problems I'm encountering at https://suntong.github.io/go-app-hello/:

![image](https://github.com/user-attachments/assets/59a219eb-ea0b-43a9-84c0-4bab295b9f19)

The first one, 

`Manifest: property 'scope' ignored. Start url should be within scope of scope URL.`

Might this be an issue of V10? As Manifest is auto-generated:

```
  "scope": "/go-app-hello/",
  "start_url": "/go-app-hello",
````

And the old `"start_url"` was `"/go-app-hello/"` before, when there isn't such issue.

For the second one, 

`Uncaught (in promise) DOMException: Cache.addAll() encountered a network error`

I have no idea what causes it, and how to fix. please help. thx.

**Comment by oderwat** [comment]
I have no experience with sub paths and/or static deployments of Go-App created PWAs. There may be such a problem when running in a sub path. Can you please look into this @maxence-charriere?

About the network error with Cache.addAll(). This does not happen when I open your site with my Google Chrome on an iMac. So I can't reproduce it easily.

**Comment by suntong** [comment]
> About the network error with Cache.addAll(). This does not happen when I open your site 

Ahh, both problems seems to be my browser's problems, as I tried in private mode and everything load fine. So, 

Case closed. 

Thanks for checking!!

**Comment by oderwat** [comment]
Did you try to add a "/" to the page prefix as an experiment? I wonder what it will create in that case.

**Comment by suntong** [comment]
> And the old `"start_url"` was `"/go-app-hello/"` before, when there isn't such issue.

Making the following single change alone fixed the problem:

https://github.com/suntong/go-app-hello/commit/300d1c81e672321614c58cccf5426cebcc360262

So I think this is a new V10 issue -- `"start_url"` should have the ending slash. 

However, the 2nd error, the network error with Cache.addAll(), comes back. I don't know if it is related with the above modification. Please check if you get the same error at your end @oderwat. thx.

**Comment by oderwat** [comment]
"https://suntong.github.io/go-app-hello/" as of now works for me without errors in the console on Google Chrome, Safari and Firefox with my iMac. So I guess there is definitely a problem with the path generation for the manifest in V10 @maxence-charriere

**Comment by maxence-charriere** [comment]
I think the scope should not be resolved at all.

```go
func (h *Handler) makeManifestJSON() []byte {
	scope := h.Resources.Resolve("/") // <------
	if scope != "/" && !strings.HasSuffix(scope, "/") {
		scope += "/"
	}
	// ...
}
```

**Comment by maxence-charriere** [comment]
can you try with this:


```sh
go get -u github.com/maxence-charriere/go-app/v10@adb6a03
```

**Comment by suntong** [comment]
Yes, the initially reported problem is now gone, but the following Cache.addAll() error problem come back again:

`Uncaught (in promise) NetworkError: Failed to execute 'addAll' on 'Cache': Cache.addAll() encountered a network error`

![image](https://github.com/user-attachments/assets/2037940b-cd34-432b-9ad0-127ac75a253b)


> Updated my chrome from 119.0.6045.159-1 to 123.0.6312.105-1, and yes, the network error with Cache.addAll() is now gone.

I tried it again this time, upgraded from 114.0.5735.198-1 to 128.0.6613.84-1 but the problem remains.

```sh
# was:
$ apt-cache policy google-chrome-stable
google-chrome-stable:
  Installed: 114.0.5735.198-1
  Candidate: 122.0.6261.69-1
  Version table:
     122.0.6261.69-1 500
        500 https://dl.google.com/linux/chrome/deb stable/main amd64 Packages

# Now:
$ apt-cache policy google-chrome-stable
google-chrome-stable:
  Installed: 128.0.6613.84-1
  Candidate: 128.0.6613.84-1
  Version table:
 *** 128.0.6613.84-1 500
        500 https://dl.google.com/linux/chrome/deb stable/main amd64 Packages
        100 /var/lib/dpkg/status
```

I'll leave you with the decision whether to open another issue for it or not.

**Comment by maxence-charriere** [comment]
@suntong, are you certain that all the cached files are reachable? Could you please copy and paste the list of files from the top of app-worker.js?

**Comment by maxence-charriere** [comment]
mmm, I don't see any errors when I m going on your online website. can even install it.

**Comment by suntong** [comment]
hmm, what's your browser and version?

If @oderwat doesn't have problem either, I think we can just close it.

**Comment by maxence-charriere** [comment]
use latest chrome

**Comment by oderwat** [comment]
I do not get any error with the site. Not with latest Chrome, Firefox or Safari (all on OSX).

**Comment by suntong** [comment]
Thanks, so it's my own problem then, and I'm closing it.
