### ISSUE TITLE
Survey: What UI framework do you use?

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#979]
I know [go-app](https://github.com/maxence-charriere/go-app) can build fancy sites like [Lofimusic.app](https://lofimusic.app/collegemusic-lonely), but do you guys use it to build _normal_ web app as well, those web _forms_ with different _gadgets_ and _buttons_? 

What UI framework do you build your go-apps on top of please.

**Comment by maxence-charriere** [comment]
I use it mainly for https://murlok.io

**Comment by oderwat** [comment]
> What UI framework do you build your go-apps on top of please.

We do not use any frameworks for our PWA. We build our own UI Elements using a combination of Go-App declarative syntax components that are basically HTML5 elements and TailwindCSS. What "framework" could possibly be used anyway? You should not (can't) mix JS frameworks that modify the DOM with Go-App. For CSS frameworks there are some options but many of them need extra JavaScript and webpack. I am already not happy needing NodeJS to make TailwindCSS "work". We have to deal with AngularJS and React based legacy apps and that makes me sick, every time we need to touch them.

Out PWA are actually also no "Websites", they are applications that happen to be distributed as PWA. I would probably not create a "normal" website using Go-App, as the WASM is much too big for that. We also fight against memory and storage limitations in iPad/iPhone. Stuff is pretty shaky to be used in production. But so far we have good results.

**Comment by suntong** [comment]
> they are applications that happen to be distributed as PWA

So in your applications, are there any input controls, gadgets and buttons?  They're mostly decorated by TailwindCSS?

**Comment by oderwat** [comment]
As long as they are not based on canvas elements they, they are created with HTML and styled with CSS. TailwindCSS is just a helper for that.
