### ISSUE TITLE
Stop chrome from refreshing tabs

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#980]
Having updated my chrome from 119.0.6045.159-1 to 123.0.6312.105-1, I noticed one behavior that has changed in chrome --

I'm used to open many chrome tabs, and leave them open. After my chrome update, when I click back to the go-app tab that I have left open, chrome is now doing a refresh, whereas previously it would not. 

This is devastate to me, for e.g., if I run https://github.com/oderwat/go-nats-app, then all my previous conversation would be gone. 

Has anyone noticed such behaviour? Any idea how to fix it please? thx.

Hmm, It might be related my chrome setting that actively put tabs to sleeps (which is a must have to me).. errh..., we cannot have both, right? Looking more into it...

**Comment by oderwat** [comment]
You can't put them to sleep and expect the app to remember stuff that it does not store. In a real application you would probably store the data and reloading will go to the same or at least a defined state, just like a game is getting saved and loaded at the same position or into a hub, depending on how that was implemented.

**Comment by suntong** [comment]
Right. 

I've config them to be not going into sleep, but somehow such configuration is no longer working in my new chrome, which is my own problem to look into. Closing it.

**Comment by oderwat** [comment]
Not related to Go-App but maybe something you would like to check out: I use workona.com since some months to manage multiple workspaces with tabs and resources. This also has it own "put to sleep" (which will not help you) but using the resources and having workspace focused tabs is a big deal for me (also the global search).
