### ISSUE TITLE
Error while trying to compile intro code

### ISSUE THREAD

**Issue by ViK0s** [maxence-charriere/go-app#981]
Hello,
I have a problem while running the code from ["Getting Started"](https://go-app.dev/getting-started) page of the docs. I get the error:
 _./main.go:31:17: cannot use &hello{} (value of type *hello) as func() app.Composer value in argument to app.Route_
I'm running go version go1.22.5 linux/amd64 on ubuntu 22.04.3 on wsl, but I tried running the code on windows and I had the same error.

**Comment by mlctrez** [comment]
@ViK0s 

See https://github.com/maxence-charriere/go-app/issues/970 

The documentation is current for V9 of go-app.. V10 documentation is coming.

**Comment by oderwat** [comment]
Sadly the documentation is still outdated with the current release V10. Please use `app.NewZeroComponentFactory(hello{})` instead of `&hello{}`

**Comment by ViK0s** [comment]
Sorry, probably should have read the whole doc and not skipped straight to the getting started page :sweat: .
Thank you for the fast help.
