### ISSUE TITLE
How to prevent redundant data fetching when the page is fully loaded?

### ISSUE THREAD

**Issue by slegrand45** [maxence-charriere/go-app#998]
Hi,

First of all, congratulations for this amazing package. It's really an impressive work. go-app certainly deserves to be better known.

I'm currently developing an application where I need to fetch data from the backend server. I'm using [Connect] (https://connectrpc.com/) for this purpose.

According to my understanding, the data fetching code should reside within either the OnMount() or OnNav() methods of the components. However, I've observed that when the page fully loads, the fetching code gets called twice: once during what I presume to be pre-rendering, and again when OnMount()/OnNav() is triggered on the client-side.

Is there a way to prevent this redundant data fetching? This issue, of course, doesn't occur after the initial application load as pre-rendering is no longer a factor.

Thank you for your help.

**Comment by maxence-charriere** [comment]
I think a more suitable would be to use action and state. Available from context

**Comment by maxence-charriere** [comment]
Thanks for the kind words too.

**Comment by oderwat** [comment]
@slegrand45 do you need a fetch at pre-render (in the back end)?

I think you could check `app.IsServer()` / `app.IsClient()` or use different code for the server and the backend routes. The latter is what we do for basically all application we made with go-app. See this example (which also demonstrates NATS, which we prefer over other ways to connect to a backend): https://github.com/oderwat/go-nats-app

**Comment by slegrand45** [comment]
Thank you very much for your responses. @oderwat, I'll definitely examine the go-nats-app example. Ideally, I'd like to set the value of a component field within the OnPreRender() method and then be able to retrieve that value **on the client-side** within the OnMount() or OnNav() methods. Something like this:

```go
type hello struct {
	app.Compo
	Name string
}

func (h *hello) OnPreRender(ctx app.Context) {
    h.Name = "myvalue"
}

func (h *hello) OnMount(ctx app.Context) {
    // display "myvalue" even when running on the client
    // so no need to call the server again to retrieve that value
    app.Log(h.Name)
}
```

I may be wrong but that seems impossible at this time.

**Comment by oderwat** [comment]
@slegrand45 What you do in PreRender is not accessible by the frontend. It will be replaced with the actual loader if the JS is run. PreRender is meant for SEO only.

Ways to share variables between backend and frontend (after compilation) which I am aware of are:

- `app.Handler { Env: map[string]string{ "Test": "Value" } }` with `app.GetEnv("Test")`
- You could add something to `app.Handler { RawHeaders: `<script>document.GlobalTest</script>" }` which then could be picked up through something like`app.Get("document").Get("GlobalTest").String()`  (or without the document. Not sure)
- Making a call to the backend through HTTP/S (JS fetch) or a WebSocket (WASM implementations).

There is nothing else how you could get data to the frontend after compilation afaik.

Using "Env" or "RawHeaders" will also only work on installation/updating of the App in the Hosts Browser Engine (not on reloads). This means: You can't change this in the backend without bumping `app.Handler { Version string }` and have the App(s) update to this new version. If you needed a lot of data to be updated you could also compile a new WASM file and bake data into that and have the server send a new version.

Just as a reminder: This is a framework for PWAs and therefore will use caching of all the data in such a way, that it works without a network connection after it got installed. So any kind of "backend" access is basically an "add on" which needs to be maintained by the developer of the application itself.

@maxence-charriere I hope I am right with those claims. Please confirm and correct me when needed.

**Comment by maxence-charriere** [comment]
@oderwat is on point (as always).

i would just add that in general, yeah, a ui with go-app is built more like an app than a traditional website. 

For Murlok.io, it is a client and all data goes through a REST api. It use in memory and local storage to avoid fetching multiple time a resource. Avoid relying on local storage though since the size is limited.

**Comment by slegrand45** [comment]
Thanks a lot for your explanations. I'll keep experimenting with go-app.
